<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class TeacherPaymentBill extends \Application\Entity\TeacherPaymentBill implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Application\\Entity\\TeacherPaymentBill' . "\0" . 'id', '' . "\0" . 'Application\\Entity\\TeacherPaymentBill' . "\0" . 'refNumber', '' . "\0" . 'Application\\Entity\\TeacherPaymentBill' . "\0" . 'date', '' . "\0" . 'Application\\Entity\\TeacherPaymentBill' . "\0" . 'paymentAmount', '' . "\0" . 'Application\\Entity\\TeacherPaymentBill' . "\0" . 'paymentStatus', '' . "\0" . 'Application\\Entity\\TeacherPaymentBill' . "\0" . 'totalTime', '' . "\0" . 'Application\\Entity\\TeacherPaymentBill' . "\0" . 'overtime', '' . "\0" . 'Application\\Entity\\TeacherPaymentBill' . "\0" . 'vacationDeduction', '' . "\0" . 'Application\\Entity\\TeacherPaymentBill' . "\0" . 'totalTimePreviouslyBilled', '' . "\0" . 'Application\\Entity\\TeacherPaymentBill' . "\0" . 'totalTimeCurrentlyBilled', '' . "\0" . 'Application\\Entity\\TeacherPaymentBill' . "\0" . 'contract', '' . "\0" . 'Application\\Entity\\TeacherPaymentBill' . "\0" . 'teacher'];
        }

        return ['__isInitialized__', '' . "\0" . 'Application\\Entity\\TeacherPaymentBill' . "\0" . 'id', '' . "\0" . 'Application\\Entity\\TeacherPaymentBill' . "\0" . 'refNumber', '' . "\0" . 'Application\\Entity\\TeacherPaymentBill' . "\0" . 'date', '' . "\0" . 'Application\\Entity\\TeacherPaymentBill' . "\0" . 'paymentAmount', '' . "\0" . 'Application\\Entity\\TeacherPaymentBill' . "\0" . 'paymentStatus', '' . "\0" . 'Application\\Entity\\TeacherPaymentBill' . "\0" . 'totalTime', '' . "\0" . 'Application\\Entity\\TeacherPaymentBill' . "\0" . 'overtime', '' . "\0" . 'Application\\Entity\\TeacherPaymentBill' . "\0" . 'vacationDeduction', '' . "\0" . 'Application\\Entity\\TeacherPaymentBill' . "\0" . 'totalTimePreviouslyBilled', '' . "\0" . 'Application\\Entity\\TeacherPaymentBill' . "\0" . 'totalTimeCurrentlyBilled', '' . "\0" . 'Application\\Entity\\TeacherPaymentBill' . "\0" . 'contract', '' . "\0" . 'Application\\Entity\\TeacherPaymentBill' . "\0" . 'teacher'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (TeacherPaymentBill $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setRefNumber($refNumber = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRefNumber', [$refNumber]);

        return parent::setRefNumber($refNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getRefNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRefNumber', []);

        return parent::getRefNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setDate($date = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDate', [$date]);

        return parent::setDate($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDate', []);

        return parent::getDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaymentAmount($paymentAmount = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaymentAmount', [$paymentAmount]);

        return parent::setPaymentAmount($paymentAmount);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaymentAmount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaymentAmount', []);

        return parent::getPaymentAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaymentStatus($paymentStatus = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaymentStatus', [$paymentStatus]);

        return parent::setPaymentStatus($paymentStatus);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaymentStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaymentStatus', []);

        return parent::getPaymentStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotalTime($totalTime = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotalTime', [$totalTime]);

        return parent::setTotalTime($totalTime);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalTime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalTime', []);

        return parent::getTotalTime();
    }

    /**
     * {@inheritDoc}
     */
    public function setOvertime($overtime = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOvertime', [$overtime]);

        return parent::setOvertime($overtime);
    }

    /**
     * {@inheritDoc}
     */
    public function getOvertime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOvertime', []);

        return parent::getOvertime();
    }

    /**
     * {@inheritDoc}
     */
    public function setVacationDeduction($vacationDeduction = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVacationDeduction', [$vacationDeduction]);

        return parent::setVacationDeduction($vacationDeduction);
    }

    /**
     * {@inheritDoc}
     */
    public function getVacationDeduction()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVacationDeduction', []);

        return parent::getVacationDeduction();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotalTimePreviouslyBilled($totalTimePreviouslyBilled = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotalTimePreviouslyBilled', [$totalTimePreviouslyBilled]);

        return parent::setTotalTimePreviouslyBilled($totalTimePreviouslyBilled);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalTimePreviouslyBilled()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalTimePreviouslyBilled', []);

        return parent::getTotalTimePreviouslyBilled();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotalTimeCurrentlyBilled($totalTimeCurrentlyBilled = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotalTimeCurrentlyBilled', [$totalTimeCurrentlyBilled]);

        return parent::setTotalTimeCurrentlyBilled($totalTimeCurrentlyBilled);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalTimeCurrentlyBilled()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalTimeCurrentlyBilled', []);

        return parent::getTotalTimeCurrentlyBilled();
    }

    /**
     * {@inheritDoc}
     */
    public function setContract(\Application\Entity\Contract $contract = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContract', [$contract]);

        return parent::setContract($contract);
    }

    /**
     * {@inheritDoc}
     */
    public function getContract()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContract', []);

        return parent::getContract();
    }

    /**
     * {@inheritDoc}
     */
    public function setTeacher(\Application\Entity\Teacher $teacher = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTeacher', [$teacher]);

        return parent::setTeacher($teacher);
    }

    /**
     * {@inheritDoc}
     */
    public function getTeacher()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTeacher', []);

        return parent::getTeacher();
    }

}
