<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Teacher extends \Application\Entity\Teacher implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Application\\Entity\\Teacher' . "\0" . 'id', '' . "\0" . 'Application\\Entity\\Teacher' . "\0" . 'civility', '' . "\0" . 'Application\\Entity\\Teacher' . "\0" . 'name', '' . "\0" . 'Application\\Entity\\Teacher' . "\0" . 'surname', '' . "\0" . 'Application\\Entity\\Teacher' . "\0" . 'birthDate', '' . "\0" . 'Application\\Entity\\Teacher' . "\0" . 'maritalStatus', '' . "\0" . 'Application\\Entity\\Teacher' . "\0" . 'phoneNumber', '' . "\0" . 'Application\\Entity\\Teacher' . "\0" . 'email', '' . "\0" . 'Application\\Entity\\Teacher' . "\0" . 'highDegree', '' . "\0" . 'Application\\Entity\\Teacher' . "\0" . 'speciality', '' . "\0" . 'Application\\Entity\\Teacher' . "\0" . 'currentEmployer', '' . "\0" . 'Application\\Entity\\Teacher' . "\0" . 'livingCity', '' . "\0" . 'Application\\Entity\\Teacher' . "\0" . 'livingCountry', '' . "\0" . 'Application\\Entity\\Teacher' . "\0" . 'nationality', '' . "\0" . 'Application\\Entity\\Teacher' . "\0" . 'contactInEmergency', '' . "\0" . 'Application\\Entity\\Teacher' . "\0" . 'type', '' . "\0" . 'Application\\Entity\\Teacher' . "\0" . 'status', '' . "\0" . 'Application\\Entity\\Teacher' . "\0" . 'idendityDocument', '' . "\0" . 'Application\\Entity\\Teacher' . "\0" . 'coverLetter', '' . "\0" . 'Application\\Entity\\Teacher' . "\0" . 'resume', '' . "\0" . 'Application\\Entity\\Teacher' . "\0" . 'highestDegree', '' . "\0" . 'Application\\Entity\\Teacher' . "\0" . 'actOfAppointment', '' . "\0" . 'Application\\Entity\\Teacher' . "\0" . 'password', '' . "\0" . 'Application\\Entity\\Teacher' . "\0" . 'isFirstConnection', '' . "\0" . 'Application\\Entity\\Teacher' . "\0" . 'academicRanck', '' . "\0" . 'Application\\Entity\\Teacher' . "\0" . 'faculty'];
        }

        return ['__isInitialized__', '' . "\0" . 'Application\\Entity\\Teacher' . "\0" . 'id', '' . "\0" . 'Application\\Entity\\Teacher' . "\0" . 'civility', '' . "\0" . 'Application\\Entity\\Teacher' . "\0" . 'name', '' . "\0" . 'Application\\Entity\\Teacher' . "\0" . 'surname', '' . "\0" . 'Application\\Entity\\Teacher' . "\0" . 'birthDate', '' . "\0" . 'Application\\Entity\\Teacher' . "\0" . 'maritalStatus', '' . "\0" . 'Application\\Entity\\Teacher' . "\0" . 'phoneNumber', '' . "\0" . 'Application\\Entity\\Teacher' . "\0" . 'email', '' . "\0" . 'Application\\Entity\\Teacher' . "\0" . 'highDegree', '' . "\0" . 'Application\\Entity\\Teacher' . "\0" . 'speciality', '' . "\0" . 'Application\\Entity\\Teacher' . "\0" . 'currentEmployer', '' . "\0" . 'Application\\Entity\\Teacher' . "\0" . 'livingCity', '' . "\0" . 'Application\\Entity\\Teacher' . "\0" . 'livingCountry', '' . "\0" . 'Application\\Entity\\Teacher' . "\0" . 'nationality', '' . "\0" . 'Application\\Entity\\Teacher' . "\0" . 'contactInEmergency', '' . "\0" . 'Application\\Entity\\Teacher' . "\0" . 'type', '' . "\0" . 'Application\\Entity\\Teacher' . "\0" . 'status', '' . "\0" . 'Application\\Entity\\Teacher' . "\0" . 'idendityDocument', '' . "\0" . 'Application\\Entity\\Teacher' . "\0" . 'coverLetter', '' . "\0" . 'Application\\Entity\\Teacher' . "\0" . 'resume', '' . "\0" . 'Application\\Entity\\Teacher' . "\0" . 'highestDegree', '' . "\0" . 'Application\\Entity\\Teacher' . "\0" . 'actOfAppointment', '' . "\0" . 'Application\\Entity\\Teacher' . "\0" . 'password', '' . "\0" . 'Application\\Entity\\Teacher' . "\0" . 'isFirstConnection', '' . "\0" . 'Application\\Entity\\Teacher' . "\0" . 'academicRanck', '' . "\0" . 'Application\\Entity\\Teacher' . "\0" . 'faculty'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Teacher $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCivility($civility = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCivility', [$civility]);

        return parent::setCivility($civility);
    }

    /**
     * {@inheritDoc}
     */
    public function getCivility()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCivility', []);

        return parent::getCivility();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setSurname($surname = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSurname', [$surname]);

        return parent::setSurname($surname);
    }

    /**
     * {@inheritDoc}
     */
    public function getSurname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSurname', []);

        return parent::getSurname();
    }

    /**
     * {@inheritDoc}
     */
    public function setBirthDate($birthDate = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBirthDate', [$birthDate]);

        return parent::setBirthDate($birthDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getBirthDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBirthDate', []);

        return parent::getBirthDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setMaritalStatus($maritalStatus = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMaritalStatus', [$maritalStatus]);

        return parent::setMaritalStatus($maritalStatus);
    }

    /**
     * {@inheritDoc}
     */
    public function getMaritalStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMaritalStatus', []);

        return parent::getMaritalStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhoneNumber($phoneNumber = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhoneNumber', [$phoneNumber]);

        return parent::setPhoneNumber($phoneNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhoneNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhoneNumber', []);

        return parent::getPhoneNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setHighDegree($highDegree = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHighDegree', [$highDegree]);

        return parent::setHighDegree($highDegree);
    }

    /**
     * {@inheritDoc}
     */
    public function getHighDegree()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHighDegree', []);

        return parent::getHighDegree();
    }

    /**
     * {@inheritDoc}
     */
    public function setSpeciality($speciality = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSpeciality', [$speciality]);

        return parent::setSpeciality($speciality);
    }

    /**
     * {@inheritDoc}
     */
    public function getSpeciality()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSpeciality', []);

        return parent::getSpeciality();
    }

    /**
     * {@inheritDoc}
     */
    public function setCurrentEmployer($currentEmployer = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCurrentEmployer', [$currentEmployer]);

        return parent::setCurrentEmployer($currentEmployer);
    }

    /**
     * {@inheritDoc}
     */
    public function getCurrentEmployer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCurrentEmployer', []);

        return parent::getCurrentEmployer();
    }

    /**
     * {@inheritDoc}
     */
    public function setLivingCity($livingCity = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLivingCity', [$livingCity]);

        return parent::setLivingCity($livingCity);
    }

    /**
     * {@inheritDoc}
     */
    public function getLivingCity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLivingCity', []);

        return parent::getLivingCity();
    }

    /**
     * {@inheritDoc}
     */
    public function setLivingCountry($livingCountry = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLivingCountry', [$livingCountry]);

        return parent::setLivingCountry($livingCountry);
    }

    /**
     * {@inheritDoc}
     */
    public function getLivingCountry()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLivingCountry', []);

        return parent::getLivingCountry();
    }

    /**
     * {@inheritDoc}
     */
    public function setNationality($nationality = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNationality', [$nationality]);

        return parent::setNationality($nationality);
    }

    /**
     * {@inheritDoc}
     */
    public function getNationality()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNationality', []);

        return parent::getNationality();
    }

    /**
     * {@inheritDoc}
     */
    public function setContactInEmergency($contactInEmergency = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContactInEmergency', [$contactInEmergency]);

        return parent::setContactInEmergency($contactInEmergency);
    }

    /**
     * {@inheritDoc}
     */
    public function getContactInEmergency()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContactInEmergency', []);

        return parent::getContactInEmergency();
    }

    /**
     * {@inheritDoc}
     */
    public function setType($type = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', [$type]);

        return parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', []);

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdendityDocument($idendityDocument = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdendityDocument', [$idendityDocument]);

        return parent::setIdendityDocument($idendityDocument);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdendityDocument()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdendityDocument', []);

        return parent::getIdendityDocument();
    }

    /**
     * {@inheritDoc}
     */
    public function setCoverLetter($coverLetter = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCoverLetter', [$coverLetter]);

        return parent::setCoverLetter($coverLetter);
    }

    /**
     * {@inheritDoc}
     */
    public function getCoverLetter()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoverLetter', []);

        return parent::getCoverLetter();
    }

    /**
     * {@inheritDoc}
     */
    public function setResume($resume = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setResume', [$resume]);

        return parent::setResume($resume);
    }

    /**
     * {@inheritDoc}
     */
    public function getResume()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResume', []);

        return parent::getResume();
    }

    /**
     * {@inheritDoc}
     */
    public function setHighestDegree($highestDegree = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHighestDegree', [$highestDegree]);

        return parent::setHighestDegree($highestDegree);
    }

    /**
     * {@inheritDoc}
     */
    public function getHighestDegree()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHighestDegree', []);

        return parent::getHighestDegree();
    }

    /**
     * {@inheritDoc}
     */
    public function setActOfAppointment($actOfAppointment = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActOfAppointment', [$actOfAppointment]);

        return parent::setActOfAppointment($actOfAppointment);
    }

    /**
     * {@inheritDoc}
     */
    public function getActOfAppointment()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActOfAppointment', []);

        return parent::getActOfAppointment();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword($password = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', [$password]);

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', []);

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsFirstConnection($isFirstConnection = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsFirstConnection', [$isFirstConnection]);

        return parent::setIsFirstConnection($isFirstConnection);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsFirstConnection()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsFirstConnection', []);

        return parent::getIsFirstConnection();
    }

    /**
     * {@inheritDoc}
     */
    public function setAcademicRanck(\Application\Entity\AcademicRanck $academicRanck = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAcademicRanck', [$academicRanck]);

        return parent::setAcademicRanck($academicRanck);
    }

    /**
     * {@inheritDoc}
     */
    public function getAcademicRanck()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAcademicRanck', []);

        return parent::getAcademicRanck();
    }

    /**
     * {@inheritDoc}
     */
    public function setFaculty(\Application\Entity\Faculty $faculty = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFaculty', [$faculty]);

        return parent::setFaculty($faculty);
    }

    /**
     * {@inheritDoc}
     */
    public function getFaculty()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFaculty', []);

        return parent::getFaculty();
    }

}
