<script src="js/app/department/department.component.js"></script>
<link rel="stylesheet" href='js/datatables-plugins/dataTables.bootstrap.css'>


<style> 
.md-datepicker-calendar-pane{
z-index: 120000}

.md-select-menu-container {z-index: 120000;}

li.active a.ng-binding {
  color: #000 !important;
	background-color: #eeeeee !important;
	text-decoration: none;
}

</style>


<div class="well"  style="margin-left: -30px; margin-right: -30px;" ng-init="$ctrl.init()">
        
            <div class="row">
                <div class='col-md-4'>

                    <button  ng-show=" <?=($this->access('global.system.admin', null))||($this->access('exam.create', null))?true:false?> && !$ctrl.isUpdate" type="button" ng-click="$ctrl.newExam()" class="btn btn-danger" ng-disabled="examForm.$invalid" >Enrégistrer</button>
                    <span> <a href="#!/department">Retour</a></span>
                </div>
                <div class="col-md-2"></div>

                

                
            </div>
</div>

<div class="form-view-main">
    <div class="form-view">
        <div   ng-cloak class="md-inline-form">


    <md-content layout-padding >
        <form   name="dptForm">

   
      <div class="md-dialog-content"  ng-init="init()">
        
            <div layout="row">

                    <md-select name="faculty" placeholder="Choisir la établissement" ng-model="dpt.fac_id"  style="min-width: 400px;" required>
                         <md-option ng-disabled="true"><em>---Choix de l'établissement---</em></md-option>
                        <md-option ng-value="faculty.id" ng-repeat="faculty in faculties">{{faculty.name}}</md-option>
                    </md-select>
            </div>
            <div layout layout-sm="column">
                <md-input-container flex="flex" style="width: 60%" >
                    <label>Nom du département:</label>
                    <input type='text'  name='name' ng-model="dpt.name" width='80%' md-no-asterisk required />
                        <div ng-messages="dptForm.name.$error">
                            <div ng-message="required">le champ code département est obligatoire</div>
                            <div ng-message="minlength">le code doit avoir au moins 3 caractères</div>
                        </div>                    
        
                </md-input-container>
                <md-input-container flex="flex" style="width: 20%" >
                  
                    <label>Code département:</label>
                    <input type='text'  name="code" ng-model="dpt.code" width='80%' minlength="2" md-no-asterisk required />
                        <div ng-messages="dptForm.code.$error">
                            <div ng-message="required">le champ code département est obligatoire</div>
                            <div ng-message="minlength">le code doit avoir au moins 3 caractères</div>
                        </div>
                </md-input-container> 
            </div>

           <md-checkbox ng-model="dpt.status" aria-label="Actif ?" md-no-ink >Actif ?</md-checkbox>


      </div>
     
         




        </form>
  </md-content>
</div>
        

        
<p>&nbsp;</p>
              <!--tabs widget-->
              
    <uib-tabset>
      <uib-tab >
          <uib-tab-heading>
              <span>Liste des département</span>
          </uib-tab-heading>
        <div class="tab-container">              
                <div class="row" >
                    <table class="table table-striped table-condensed">
                         <thead>
                             <tr class="bg-primary">
                                 <th>Num</th>
                                 <th>Matricule</th>
                                 <th>Nom</th>
                                 <th >Classe</th>
                                 <th >Présence</th>
                                 <th>Anonymat</th>
                                 <th>Note_E</th>
                                 <th>Note_V</th>
                                 <th>Note_F</th>

                             </tr>
                         </thead>
                         <tbody>
                             <tr ng-repeat="std in $ctrl.registeredStd" >
                               <td ng-bind="std.num"></td>
                               <td ng-bind="std.matricule"></td>
                               <td ng-bind="std.nom"></td>
                               <td ng-bind="std.studentCurrentClasse"></td>
                               <td ng-bind='std.attendance==="P"?"":"A"' ng-class="{'zf-green fa fa-check': std.attendance==='P','zf-red': std.attendance==='A' }"> </td>
                               <td ng-bind="std.anonymat"></td>
                               <td ng-bind='std.isMarkFromCatchUpExam===1?std.registeredMark+"[R]":std.registeredMark' ng-class="{'zf-red': std.isMarkFromCatchUpExam===1}"></td>
                               <td ng-bind='(std.isMarkFromCatchUpExam===1&&std.isMarkValidated===1)?std.validatedMark+"[R]":std.validatedMark' ng-class="{'zf-red': (std.isMarkFromCatchUpExam===1&&isMarkValidated===1)}"></td>
                               <td ng-bind='(std.isMarkFromCatchUpExam===1&&std.isMarkConfirmed===1)?std.confirmedMark+"[R]":std.confirmedMark' ng-class="{'zf-red': (std.isMarkFromCatchUpExam===1&&std.isMarkConfirmed===1)}" ></td>

                             </tr>
                         </tbody>
                     </table>
                 </div>
                <!--End tab-->
                
            </div>  
            </uib-tab>
              <uib-tab>
                <uib-tab-heading>
                    <span>Liste des Responsables</span>
                </uib-tab-heading>
                <div class="tab-container"> 
                </div>
            </uib-tab>
        </div>

