
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<?php



//($this->typeExam=="CC")||($this->typeExam=="CCTP")?$width="16.6%":$width="12.5%";
$width="9%";

$codeUe = $students[0]['codeUe']; 
$nomUe  = $students[0]['nomUe']; 
$tblBody = '
<html>
<head>
<style>
body {font-family: sans-serif;
	font-size: 10pt;
}
p {	margin: 0pt; }

.main {
	border: 0.1mm solid #000000;
        border-collapse: collapse;
       
}
.main th{
        color: #ffffff;
	border-left: 0.1mm solid #000000;
        border-top: 0.1mm solid #000000;
        vertical-align: middle;
        padding: 5px;
}

.main td {
	border-left: 0.1mm solid #000000;
        /*border-top: 0.1mm solid #000000;*/
        border-bottom: 0.1mm solid #000000; 
        
        
}

.backlog {
	border: 0.1mm solid #000000;
        border-collapse: collapse;
       
}

.backlog th{
        color: #ffffff;
	border-left: 0.1mm solid #000000;
        border-top: 0.1mm solid #000000;
        vertical-align: middle;
    
}
.backlog td {
	border-left: 0.1mm solid #000000;
        /*border-top: 0.1mm solid #000000;*/
        border-bottom: 0.1mm solid #000000;  
        color : #000000;
        
        
}


</style>
</head>
<body>
<!--mpdf
<htmlpageheader name="myheader">
<table width="100%"><tr>
<td></td><td width="50%" style="color:#0000BB;  vertical-align: middle;"><span style="font-weight: bold; font-size: 14pt;">'.$this->school.'</span><br />'.$this->faculty.'<br />'.$this->filiere.'<br /></td>
<td width="50%" style="text-align: right; vertical-align: middle;"><img src="'.$this->logo.'" width="75px" height="75x"></td>
</tr></table>
<hr>
</htmlpageheader>

<htmlpagefooter name="myfooter">
<span style="font-size: 10pts; color: #428bca;">TCC: Total crédits capitalisés,  TCI: Total crédits inscrits, MPS: Moyenne pondérée semestrielle, MPC: Moyenne pndérée cumulée, ADM: Admis(e), AJR:Ajourné(e), RED: , EXC: Exclu(e.)<span>
<div style= "border-top: 1px solid #000000; font-size: 9pt; text-align: right; padding-top: 3mm; ">
<span>Page {PAGENO}/{nb}</span>
</div>
<div style=" font-size: 6pt; text-align: center;  ">'.$this->brandInfo.'</div>
</htmlpagefooter>

<sethtmlpageheader  name="myheader" value="on" show-this-page="1" />
<sethtmlpagefooter  name="myfooter" value="on"  />
mpdf-->

<table width="100%" style="font-family: serif; "  cellpadding="2">

<tr style="background-color:#dfe4ea;">
<td style=" width: 15%; border: 0.1mm solid #888888;  text-align: center; "><span style="font-size: 16pt; font-weight: bold;">'.$this->classe.'</span></td> 


<td width="25%" style="border: 0.1mm solid #888888; text-align: center;"><span style="font-size: 16pt; font-weight: bold;  font-family: sans; "> Année Académique <br />'.$this->acadYr.' </span></td>
    <td width="25%" style="border: 0.1mm solid #888888; text-align: center;"><span style="font-size: 16pt; font-weight: bold;  font-family: sans; text-align: center;"> '.$this->semestre.' </span></td>
</tr>
<tr style="background-color:#F4F3F4;"><td colspan="3" style="text-align: center;"><strong>PROCES VERBAL RECAPITULATIF</td></tr>
</table>
';
$students = $this->students;
$subjects = $this->subjects;
$ranking = $this->semRanking;

//create header
if($students)
    $numColumns = sizeof($students[0]);
              
                $width_col_1 = "7%";
                $width_col_2 = "20%";
                $width_mps = "3.5%";
                $width_grd = "3.5%";
                $font_header_size = "10px";
                $font_size = "10px;";
                $font_mark_size = "10px;";
                $width_sem_1 = "3%";
                $sem = $this->semestre;
                //echo $numColumns; exit;
            if($numColumns<=25) $width_col_suject = "5%";
            elseif($numColumns<=28) $width_col_suject = "4%";
            elseif($numColumns<=34) $width_col_suject = "3.5%";
            elseif($numColumns<=46)
            {
                $width_col_suject = "3.2%";
                $font_header_size = "8px";
            }
            elseif($numColumns<=57){
            $width_col_suject = "2.4%";
            $font_header_size = "8px";
            }
            else{
            $width_col_suject = "2.1%";
            $font_header_size = "8px"; 
            $font_mark_size = "9px;";
            }
            
  //Create first header          
    $tblHeader = '<tr style="background-color:#428bca;  color: #ffffff;  ">';
    $counter = 0;
    $tblHeader_2 ='<tr   style="background-color:#428bca;  color: #ffffff;  ">';
    $tblHeader_3 ='<tr   style="background-color:#428bca;   ">';
    
    foreach($students[0] as $key=>$values)
    {
        if(strtolower($key)==strtolower("MPCPREV"))
        {   
            
            $tblHeader.= '<th rowspan="2" style = " " >MPC </th>';
            //Doing nothing
        }
        if(strtolower($key)==strtolower("CrV"))
        {   
            
            $tblHeader.= '<th rowspan="2" style = "  "  >TCC </th>';
            //Doing nothing
        }
        if(strtolower($key)==strtolower("tcis"))
        {   
            
            $tblHeader.= '<th rowspan="2" style = " " >TCI </th>';
            //Doing nothing
        }
        if(strtolower($key)==strtolower("tcvs"))
        {   
            
            $tblHeader.= '<th rowspan="2" style = " " >TCC </th>';
            //Doing nothing
        }    
         if(strtolower($key)==strtolower("tcia"))
        {  
            if(($ranking%2)==0)
                $tblHeader.= '<th rowspan="2" style = " " >TCI </th>';
            //Doing nothing
        }
        if(strtolower($key)==strtolower("tcva"))
        {   
            if(($ranking%2)==0)
                $tblHeader.= '<th rowspan="2" style = " " >TCC </th>';
            //Doing nothing
        } 
        if(strtolower($key)==strtolower("tcic"))
        {   

            $tblHeader.= '<th rowspan="2" style = " ">TCI </th>';
            //Doing nothing
        }        
        if(strtolower($key)==strtolower("tcc"))
        {   

            $tblHeader.= '<th rowspan="2" style = "  ">TCC </th>';
            //Doing nothing
        } 
        if(strtolower($key)==strtolower("percent"))
        {   

            $tblHeader.= '<th rowspan="2" style = "  ">%val </th>';
            //Doing nothing
        }         
       // $tblHeader.= '<th rowspan="2" style = "height: 20px; text-align: center; width: '.$width_col_1.' text-align: center;"><strong>'.ucwords(strtoupper($key)).'</strong></th>';

       
    }
   
    $tblHeader =$tblHeader.'</tr>';
    
    foreach($students[0] as $key=>$values)
    {
       
        $colspan = "1";
        if(strtolower($key)=="matricule" )
        {

            $tblHeader_2.= '<th style="text-rotate: 90;" rowspan="3" align="center" >Num</th><th rowspan="3"   style = "text-align: center;  text-align: center;"><strong>Matricule</strong></th>';
        }
        elseif(strtolower($key)=="nom" )
        {
            $width = "22%;";
             $tblHeader_2.= '<th rowspan="3"  style = "text-align: center; " ><strong>Nom</strong></th>';
             $tblHeader_2.= '<th  colspan="2"  style="text-rotate: 90;"><strong>SEM N-1</strong></th>';
        }
        elseif(strtolower($key)=="mps" || strtolower($key)=="mpc" )
        {
             $tblHeader_2.= '<th rowspan="3"  style = "text-rotate: 90;   text-align: center;"><strong>'.$key.'</strong></th>';
        }
        elseif(strtolower($key)=="tcis")
        {
             $tblHeader_2.= '<th colspan="2"  style = "text-rotate: 90;   text-align: center;"><strong>'.$sem.'</strong></th>';
        }     
        elseif(strtolower($key)=="tcia"  )
        {
            if(($ranking%2)==0)
                $tblHeader_2.= '<th colspan="2"  style = "text-rotate: 90;  text-align: center;"><strong>Année</strong></th>';
        } 
        elseif(strtolower($key)==strtolower("tcic")) {//Doing nothing

            $tblHeader_2.= '<th colspan="3"  style = " text-rotate: 90;  text-align: center;"><strong>Cycle</strong></th>';            
        }        
        elseif(strtolower($key)==strtolower("note".$counter))
        {   
            $counter++;
            //Doing nothing
        }
        elseif(strtolower($key)==strtolower("credits".$counter))
        {   
            //$counter++;
            //Doing nothing 
            
            $tblHeader_3.='<th align="center" color="#ffffff">'.$values.'</th>';
        }        
        elseif( strtolower($key)==strtolower("MPCPREV")||strtolower($key)==strtolower("CrV") || strtolower($key)=="tcvs" || strtolower($key)=="tcva"|| strtolower($key)=="tcc"|| strtolower($key)=="percent")
        {   
            
        
            //Doing nothing
        }

        elseif(strtolower($key)==strtolower("MENTION")) {//Doing nothing
            $tblHeader_2.= '<th rowspan="3"  style = "text-rotate: 90;  text-align: center;"><strong>MENTION</strong></th>';
        } 
        elseif(strtolower($key)==strtolower("DECISION")) {//Doing nothing
            if(($ranking%2==0))
                $tblHeader_2.= '<th rowspan="3"  style = "text-rotate: 90;    text-align: center;"><strong>DECISION</strong></th>';
        }        
        else
        { 

             $tblHeader_2.= '<th rowspan="2" style = " text-rotate: 90;   text-align: center;"><strong>'.ucwords(strtoupper($key)).'</strong></th>';
             
             
             
        }       // else $width = "";
        //Table header
       
    }
$tblHeader_2 =$tblHeader_2.'</tr>';
$tblHeader_3 =$tblHeader_3.'</tr>';    

$tblHeader =$tblHeader_2.$tblHeader.$tblHeader_3;
$tblBody .= '<table class="main"><thead>'.$tblHeader.'</thead>';

$i=0;
$k=0;

foreach($students as $stud)
{
    $tblBody.='<tr nobr="true">';
    $counter = 0;
    $k++;
    
    foreach($stud as $key=>$value)
    {
        //Table header
        $align = "center";
        $color = "#ffffff;";
        
        if(strtolower($key)=="matricule" )
        {

            $tblBody.= '<td align="center" width="30px">'.$k.'</td><td style = "  text-align: '.$align.'; "> '.$value.'</td>'; 
        }
        elseif(strtolower($key)=="nom" )
        {
            
            $align = "left;";
            $tblBody.= '<td style = " width: 30%; text-align:left">'.$value.'</td>'; 
        }
        elseif(strtolower($key)==strtolower("CrV") )
        {
            
            $align = "left;";
            $tcc = $value;
            $tblBody.= '<td style = " ; text-align: center; ">'.$value.'</td>'; 
        } 
        elseif(strtolower($key)==strtolower("MPCPREV") )
        {
            
            $align = "left;";
            $tblBody.= '<td style = "  text-align:center; ">'.$value.'</td>'; 
        }        
        elseif(strtolower($key)=="tci" || strtolower($key)=="mps" || strtolower($key)=="mpc" )
        {
            
            if(strtolower($key)=="tci")  $color_1= "#dcdde1;"; 
            if(strtolower($key)=="tcc")  $color_1= "#c8d6e5;";  
            if(strtolower($key)=="mps")   $color_1= "#7f8fa6;";
            if(strtolower($key)=="mpc")   $color_1= "#718093;";
            $tblBody.= '<td style = "font-weight: bold;  background-color:'.$color_1.'  text-align: center;">'.$value.'</td>'; 
        
        }
        elseif(strtolower($key)=="tcis" || strtolower($key)=="tcvs")
        {
            
            if(strtolower($key)=="tci")  $color_1= "#dcdde1;"; 
            if(strtolower($key)=="tcis")  $color_1= "#c8d6e5;";  
            if(strtolower($key)=="mps")   $color_1= "#7f8fa6;";
            if(strtolower($key)=="mpc")   $color_1= "#718093;";
            $tblBody.= '<td style = "font-weight: bold;  background-color:'.$color_1.'  text-align: center;">'.$value.'</td>'; 
        
        }  
        elseif(strtolower($key)=="tcia" || strtolower($key)=="tcva" )
        {
            
             
            if(strtolower($key)=="tcc")  $color_1= "#c8d6e5;";  
            if(strtolower($key)=="tcia")   $color_1= "#7f8fa6;";
            if(strtolower($key)=="mpc")   $color_1= "#718093;";
            
            if(($ranking%2==0))
            $tblBody.= '<td style = "font-weight: bold;   background-color:'.$color_1.'  text-align: center;">'.$value.'</td>'; 
        
        }  
        elseif(strtolower(strtolower($key)=="tcic"|| strtolower($key)=="tcc"))
        {
            
            if(strtolower($key)=="percent")  $value= $value."%"; 
            $width = "30px";
            //if(strtolower($key)=="tcc")  $color_1= "#c8d6e5;";  
            if(strtolower($key)=="percent")   $width= "30px";
            $color_1= "#dcdde1;";
            $tblBody.= '<td style = "background-color:'.$color_1.';  text-align: '.$align.'">'.$value.'</td>'; 
        }         
        elseif(strtolower($key)=="percent")
        {
            
            if(strtolower($key)=="percent")  $value= $value."%"; 
            $width = "30px";
            //if(strtolower($key)=="tcc")  $color_1= "#c8d6e5;";  
            if(strtolower($key)=="percent")   $width= "30px";
            $color_1= "#dcdde1;";
            $tblBody.= '<td style = "background-color:'.$color_1.';  text-align: '.$align.'">'.$value.'</td>'; 
        }        
        elseif(strtolower($key)==strtolower("note".$counter) )
        {
            $color_font = "#000000;";
           
          if($value["grd"]=="F"||$value["grd"]=="E") {$color = "#bb1924;"; $color_font ="#ffffff;";}
          //$tblBody.= '<td style = "color:'.$color_font.'  font-size: '.$font_mark_size.' background-color:'.$color.' width: '.$width_moy.'; text-align: '.$align.'"> &nbsp; '.$value["moy"].'</td>'; 
          $tblBody.= '<td style = "color: '.$color_font.'  width: '.$width_col_suject.'; background-color:'.$color.'   text-align: '.$align.'">'.$value["grd"].'</td>'; 
          $counter++;
        }
        elseif(strtolower($key)==strtolower("MENTION")) $mention = $value;
       // elseif(strtolower($key)==strtolower("PERCENTAGE")) $percentage = $value;
        elseif(strtolower($key)==strtolower("DECISION"))
        {
            $decision = $value;
            $bgColor = "#ffffff";
            $color_d = "#212F3D";
            if($decision=="RED"||$decision=="AJR")
            {
                $bgColor = "#000000";
                $color_d="#ffffff;";
            }
            elseif ($decision =="EXC") { $bgColor = "#bb1924;"; $color_d="#ffffff;"; }
             
        }

      
        
    }
   // $tblBody.= '<td style = "color: '.$color_font1.' font-size: '.$font_mark_size.' width: '.$width_mps.' background-color:'.$color.'   text-align: '.$align.'"> &nbsp;'.(number_format($percentage,1)).'%</td>';
    $tblBody.= '<td style = "color: '.$color_font1.'  background-color:'.$color.'   text-align: '.$align.'"> &nbsp;<strong>'.$mention.'</strong></td>';
    if(($ranking%2==0))
        $tblBody.= '<td style = " color: '.$color_d.';  background-color:'.$bgColor.';   text-align: '.$align.';"> &nbsp;<strong>'.$decision.'</strong></td>';
    $tblBody.='</tr>';
}



///Create Header for students with backlogs
if ($studentsWithBaclogs)
     $numColumns = sizeof($studentsWithBaclogs[0]);

    $counter = 0;
    $tblHeader_2 ='<tr   style="background-color:#428bca;">';

   
   
    
    foreach($studentsWithBaclogs[0] as $key=>$values)
    {
       
        $colspan = "1";
        if(strtolower($key)=="matricule" )
        {

            $tblHeader_2.= '<th style = " text-align: center;"><strong>Matricule</strong></th>';
        }
        elseif(strtolower($key)=="nom" )
        {
            $width = "22%;";
             $tblHeader_2.= '<th   style = " text-align: center;"><strong>Nom</strong></th>';
             //$tblHeader_2.= '<th  colspan="2"><strong>SEM N-1</strong></th>';
        }
        elseif(strtolower($key)=="tci" || strtolower($key)=="tcc" || strtolower($key)=="mps" || strtolower($key)=="mpc" )
        {
             $tblHeader_2.= '<th   style = " text-align: center;"><strong>'.$key.'</strong></th>';
        }
        elseif(strtolower($key)==strtolower("note".$counter))
        {   
            $counter++;
            //Doing nothing
        }
       /* elseif(strtolower($key)==strtolower("MPCPREV")||strtolower($key)==strtolower("CrV"))
        {   
            
         
            //Doing nothing
        } */       
      
        else{ 

             $tblHeader_2.= '<th  style = " text-rotate: 90;  text-align: center;"><strong>'.ucwords(strtoupper($key)).'</strong></th>';
        }       // else $width = "";
        //Table header
   }
   $tblHeader_2.='</tr>';     
        
$tbl2Body = '';
foreach($studentsWithBaclogs as $stud)
{
    $tbl2Body.='<tr nobr="true">';
    $counter = 0;
    foreach($stud as $key=>$value)
    {
        //Table header
        $align = "center";
        $color = "#ffffff;";
        
        if(strtolower($key)=="matricule" )
        {

            $tbl2Body.= '<td style = "text-align: '.$align.'; "> &nbsp;'.$value.'</td>'; 
        }
        elseif(strtolower($key)=="nom" )
        {
            
            $align = "left;";
            $tbl2Body.= '<td > &nbsp;'.$value.'</td>'; 
        }
        elseif(strtolower($key)=="tci" || strtolower($key)=="tcc" || strtolower($key)=="mps" || strtolower($key)=="mpc" )
        {
            
            if(strtolower($key)=="tcri")  $color_1= "#dcdde1;"; 
            if(strtolower($key)=="tcrv")  $color_1= "#c8d6e5;";  
            if(strtolower($key)=="mps")   $color_1= "#7f8fa6;";
            if(strtolower($key)=="mpc")   $color_1= "#718093;";
            $tbl2Body.= '<td style = " background-color:'.$color_1.';"> &nbsp;'.$value.'</td>'; 
        
        }
        elseif(strtolower($key)==strtolower("note".$counter) )
        {
            $color_font = "#000000;";
           
          if($value["grd"]=="F"||$value["grd"]=="E") {$color = "#bb1924;"; $color_font ="#ffffff;";}
          if($value["grd"]==""||$value["grd"]=="") {$color = "#E8E8E8;"; $color_font ="#ffffff;";}
          $tbl2Body.= '<td style = "width:35px; color:'.$color_font.' background-color:'.$color.'; text-align: center;"> &nbsp;'.(($value["grd"])?$value["grd"]:$value["moy"]).'</td>'; 
         // $tbl2Body.= '<td style = "color: '.$color_font.' font-size: '.$font_mark_size.' background-color:'.$color.'  width: '.$width_grd.'; text-align: '.$align.'"> &nbsp;'.$value["grd"].'</td>'; 
          $counter++;
        }
      
        
    }
    $tbl2Body.='</tr>';        
}        

$tblBody.= '</table><br />'
        .(($studentsWithBaclogs)? '<p style="font-size: 16pts; font-weight: bold;"> UNITES D\'ENSEIGNEMENTS REPRISES</p><br /> '
        . '<table class="backlog"><thead>'.$tblHeader_2.'</thead>'.$tbl2Body.'</table>':'');   


///Creating Legend

    $counter=0;
    
    //$header='<tr><th style="width:10%">Num</th><th style="width:25%">Code UE</th><th style="width:65%">Nome UE</th></tr>';
    $header='';
    $table1='';
    $table2='';
    foreach($subjects as $sub)
    { 
        $counter++;
       //if($counter%2<>0) 
       $table1.='<tr><td style="width:15%">'.$sub["codeUe"].'</td><td style="width:85%">'.$sub["nomUe"].'</td></tr>'; 
       //else
       //$table2.='<tr><td style="width:15%">'.$sub["codeUe"].'</td><td style="width:85%">'.$sub["nomUe"].'</td></tr>';
       
    }
    $table2='<tr style="background-color:#000000; color:#ffffff;"><td align="center" colspan="6"></td></tr>';
    $table2.='<tr style="background-color:#000000; color:#ffffff;"><td><strong>NoteMin/20</strong></td><td><strong>NoteMax/20</strong></td><td><strong>NoteMin/100</strong></td><td><strong>NoteMax/100</strong></td>'
            . '<td><strong>Grade</strong></td><td><strong>Points</strong></td></tr>';
    foreach($grade as $sub)
    { 
        $counter++;
       //if($counter%2<>0) 
        
       $table2.='<tr><td align="center">'.$sub["minsur20"].'</td><td align="center">'.$sub["maxsur20"].''
               . '</td><td align="center">'.$sub["minsur100"].'</td><td align="center">'.$sub["maxsur100"].'</td>'
               . '<td align="center">'.$sub["gradeValue"].'</td><td align="center">'.$sub["gradePoints"].'</td></tr>'; 
       //else
       //$table2.='<tr><td style="width:15%">'.$sub["codeUe"].'</td><td style="width:85%">'.$sub["nomUe"].'</td></tr>';
       
    }
    $table1='<table>'.$header.'<tbody>'.$table1.'</tbody></table>';
    $table2='<table border="1">'.$header.'<tbody>'.$table2.'</tbody></table>';
    $table='<table ><tr nobr="true"  ><td>'.$table1.'</td><td>'.$table2.'</td></tr></table>';
    
    $tblBody.='<br />'.$table;
    
    $tblBody.="<br />"
            . '<table width="100%" style="font-family: serif; font-size: 18pt;" nobr="true" >
                <tr tr nobr="true" style="background-color:#dfe4ea; "><td colspan="2" style="border: 1px solid #000000; font-weight: bold; text-align: center;">PRESIDENT DU JURY</td>
                <td colspan="2" style="border: 1px solid #000000; font-weight: bold; text-align: center;"> RAPPORTEUR(S)</td>
                <td colspan="2" style="border: 1px solid #000000; font-weight: bold; text-align: center;"> MEMBRE(S) DU JURY</td>
                </tr>
                <tr tr nobr="true" >
                <br /><br /><br /><br />
                </tr>
</table>';
    
    

$mpdf = new \Mpdf\Mpdf([
	'margin_left' => 20,
	'margin_right' => 15,
	'margin_top' => 35,
	'margin_bottom' => 25,
	'margin_header' => 2,
        'orientation' => 'L',
	'margin_footer' => 5
]);

$mpdf->SetProtection(array('print'));
$mpdf->SetTitle("Acme Trading Co. - Invoice");
$mpdf->SetAuthor("W-TECH");
$mpdf->SetWatermarkText($this->schoolName);
$mpdf->showWatermarkText = true;
$mpdf->watermark_font = 'DejaVuSansCondensed';
$mpdf->watermarkTextAlpha = 0.1;
$mpdf->SetDisplayMode('fullpage');

$mpdf->WriteHTML($tblBody);

ob_end_clean();
//Close and output PDF document
$mpdf->Output($_SERVER["DOCUMENT_ROOT"].'/impressions/'.preg_replace('/\s+/', '',"PV_RECAP".'_'.$this->classe.'_'.$this->semestre.'_').date("d-m-Y-H-i").'.pdf', 'F');
?>

        <style> 
.md-datepicker-calendar-pane{
z-index: 120000}

.md-select-menu-container {z-index: 120000;}
</style>

   <md-dialog style="max-width: 100%;
            max-height: 100%;
    width: 100%;
    height: 100%;
    border-radius: 0;" aria-label="Mango (Fruit)">
  <form ng-cloak>
    <md-toolbar>
      <div class="md-toolbar-tools">
        <h2>Impression PV Individuel</h2>
        <span flex></span>
        <md-button class="md-icon-button" ng-click="cancel()">
          <md-icon md-svg-src="img/ic_close_24px.svg" aria-label="Close dialog"></md-icon>
        </md-button>
      </div>
    </md-toolbar>

    <md-dialog-content>
      <div  class="md-dialog-content">

          <embed src=<?=$this->serverUrl().'/impressions/'.preg_replace('/\s+/', '',"PV_RECAP".'_'.$this->classe.'_'.$this->semestre.'_').date("d-m-Y-H-i").'.pdf';?> type="application/pdf" style="width:100%;height:600px;"  />
                     


      </div>
    </md-dialog-content>

    <md-dialog-actions layout="row">

      <span flex></span>
      <md-button ng-click="cancel()">
       Fermer
      </md-button>

    </md-dialog-actions>
  </form>
</md-dialog>