
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<?php



//($this->typeExam=="CC")||($this->typeExam=="CCTP")?$width="16.6%":$width="12.5%";
$width="9%";


$tblBody = '
<html>
<head>
<style>
body {font-family: sans-serif;
	font-size: 10pt;
}
p {	margin: 0pt; }
table.items {
	border: 0.1mm solid #000000;
}
td { vertical-align: middle; }
.items td {
	border: 0.1mm solid #000000;;
	border-right: 0.1mm solid #000000;
        
}
table thead td { background-color: #EEEEEE;
	text-align: center;
	border: 0.1mm solid #000000;
	font-variant: small-caps;
        height: 30px;
        color: #0047AB;
       
}
.headlbl{

	font-variant: small-caps;
        font-size: 8pts;

}


  table.subtable { 
    border-collapse: collapse; 
    border: 1px solid #EEEEEE;
    font-size: 12pts;
    width: 100%;
  }
  .subtable td, 
  .subtable th  { 
    border-bottom: 0.1mm solid #000000; 
    border-top: 0.1mm solid #000000;
    border-right: 0.1mm solid #000000;
    height: 15px; 
    text-align: left;
    font-size: 10pts;
    color: #0047AB;
  }
    input.Checkbox {
      width: 140px;
      height: 140px;
    }
        
.eval thead td { 
	text-align: center;
	border: 0.1mm solid #000000;
	font-variant: small-caps;
  font-size: 12pt;
  height: 15px;
       
}
.eval td { 
	text-align: left;
	border: 0.1mm solid #000000;
        padding-left: 5px;
	
        
        font-size: 7pt;
}

.items td.blanktotal {
	background-color: #EEEEEE;
	border: 0.1mm solid #000000;
	background-color: #FFFFFF;
	border: 0mm none #000000;
	border-top: 0.1mm solid #000000;
	border-right: 0.1mm solid #000000;
}
.items td.totals {
	text-align: right;
	border: 0.1mm solid #000000;
}
.items td.cost {
	text-align: "." center;
}
</style>
</head>
<body>
<!--mpdf
<htmlpageheader name="myheader">
<table width="100%"><tr>
<td></td><td width="50%" style="color:#0000BB;  vertical-align: middle;"><span style="font-weight: bold; font-size: 14pt;">'.$this->school.'</span><br />'.$this->faculty.'<br />'.$this->filiere.'<br /></td>
<td width="50%" style="text-align: right; vertical-align: middle;"><img src="'.$this->logo.'" width="75px" height="75x"></td>
</tr></table>
<hr>
</htmlpageheader>

<htmlpagefooter name="myfooter">
<div style= "border-top: 1px solid #000000; font-size: 9pt; text-align: right; padding-top: 3mm; ">
<span>Page {PAGENO}/{nb}</span>
</div>
<div style=" font-size: 6pt; text-align: center;  ">'.$this->brandInfo.'</div>
</htmlpagefooter>

<sethtmlpageheader  name="myheader" value="on" show-this-page="1" />
<sethtmlpagefooter  name="myfooter" value="on"  />
mpdf-->

<table width="100%" style="font-family: serif; "  cellpadding="2">

<tr style="background-color:#dfe4ea;">
<td style=" width: 15%; border: 0.1mm solid #000000;  text-align: center; "><span style="font-size: 16pt; font-weight: bold;">'.$this->classe.'</span></td> 


<td width="25%" style="border: 0.1mm solid #000000; text-align: center;"><span style="font-weight: bold; font-size: 16pt;  font-family: sans; "> Année Académique '.$this->acadYr.' </span></td>
    <td width="25%" style="border: 0.1mm solid #000000; text-align: center;"><span style="font-weight: bold; font-size: 16pt; font-family: sans; text-align: center;"> '.$this->semestre.' </span></td>
</tr>
<tr style="background-color:#F4F3F4;"><td colspan="3" style="text-align: center;">NOTES D\'EVALUATION</td></tr>
</table>
<table class="items" width="100%" style="font-size: 9pt; border-collapse: collapse; " >'
.'<thead>


<!-- ITEMS HERE -->
';

$tblBody.=  '<tr><td colspan="3">'
       
   .'.<table  class="subtable" >'
        . '<tr><td style="text-align: left; font-variant: small-caps;"><strong>Date</strong></td><td  colspan="3">'.$this->date.'</td></tr> '
         . '<tr><td style="text-align: left; font-variant: small-caps;"><strong>Intitule de l\'UE</strong></td><td style="font-variant: normal;" colspan="3">  '.$this->codeUe.'('.$this->nomUe.')    </td></tr> '
        .'<tr><td style="text-align: left; font-variant: small-caps; width: 150px;"><strong>Code Evaluation</strong></td><td colspan="3">'.$this->codeExam.'</td></tr>'
        . '<tr><td style="text-align: left; font-variant: small-caps;"><strong>Type Evaluation</strong></td><td colspan="3">'.$this->typeExam.'</td>'
        . '</tr>'
        . '<tr><td style="text-align: left; font-variant: small-caps;"><strong>Nom de  l\'enseignant</strong></td><td colspan="3"> &nbsp;   </td></tr> '
        . '</table></td>'   

        . '<td rowspan="2" style="text-rotate: 90;"><strong>Notes</strong></td></tr>';
$tblBody.= '<tr>';
foreach($students[0] as $key=>$values) $tblBody .=($key!="note")?'<td ><strong>'.$key.'</strong></td>':"";
$tblBody .='</tr>'
            .'</thead>'
            .' <tbody>';


$i=1;
foreach($students as $stud)
{
   // print_r($stud); exit;
    
    $tblBody.= '<tr nobr="true" >';
    $tblBody.='<td style = "width: 5%; text-align: center;">'.($i++).'</td>';
    $tblBody.='<td style = "width: 12%; text-align: center;">'.$stud['matricule'].'</td>';
    $tblBody.='<td style = "width: 73%; text-align: left;"> '.$stud['nom'].'</td>';
    $tblBody.='<td style = "width: 10%; text-align: center;">'.$stud['note'].'</td>';
    //$tblBody.='<td style = "width: 10%; text-align: center;"></td>';

    /*foreach($stud as $std)
    {
        //Table header
        
        $tblBody.= '<td>'.$values.'</td>';
    }*/
    $tblBody.='</tr>';
}


$tblBody.='
</tbody>
</table>
<BR />
<table width="100%" style="font-family: serif;" nobr="true" >

<tr tr nobr="true" style="background-color:#dfe4ea;"><td colspan="2" style="border: 0.1mm solid #000000; text-align: center;">Signatures</td></tr>
<tr tr nobr="true" ><td colspan="2" style="border: 0.1mm solid #000000; text-align: center;"><br /><br /><br /><br /><br /></td></tr></table>


</body>
</html>
';



$mpdf = new \Mpdf\Mpdf([
	'margin_left' => 20,
	'margin_right' => 15,
	'margin_top' => 35,
	'margin_bottom' => 25,
	'margin_header' => 2,
	'margin_footer' => 5
]);

$mpdf->SetProtection(array('print'));
$mpdf->SetTitle("Acme Trading Co. - Invoice");
$mpdf->SetAuthor("W-TECH");
$mpdf->SetWatermarkText($this->school);
$mpdf->showWatermarkText = true;
$mpdf->watermark_font = 'DejaVuSansCondensed';
$mpdf->watermarkTextAlpha = 0.1;
$mpdf->SetDisplayMode('fullpage');

$mpdf->WriteHTML($tblBody);



ob_end_clean();
//Close and output PDF document
$mpdf->Output($_SERVER["DOCUMENT_ROOT"].'/impressions/'.preg_replace('/\s+/', '',"notes").'-'.date("d-m-Y-H-i").'.pdf', 'F');
?>

        <style> 
.md-datepicker-calendar-pane{
z-index: 120000}

.md-select-menu-container {z-index: 120000;}
</style>

   <md-dialog style="max-width: 100%;
            max-height: 100%;
    width: 100%;
    height: 100%;
    border-radius: 0;" aria-label="Mango (Fruit)">
  <form ng-cloak>
    <md-toolbar>
      <div class="md-toolbar-tools">
        <h2>Impression PV Individuel</h2>
        <span flex></span>
        <md-button class="md-icon-button" ng-click="cancel()">
          <md-icon md-svg-src="img/ic_close_24px.svg" aria-label="Close dialog"></md-icon>
        </md-button>
      </div>
    </md-toolbar>

    <md-dialog-content>
      <div  class="md-dialog-content">

          <embed src=<?=$this->serverUrl().'/impressions/'.preg_replace('/\s+/', '',"notes").'-'.date("d-m-Y-H-i").'.pdf';?> type="application/pdf" style="width:100%;height:600px;"  />
                     


      </div>
    </md-dialog-content>

    <md-dialog-actions layout="row">

      <span flex></span>
      <md-button ng-click="cancel()">
       Fermer
      </md-button>

    </md-dialog-actions>
  </form>
</md-dialog>