
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<?php


$totalAdmis = $this->totalStudent - $this->totalFailure;


$tblBody = '
<html>
<head>
<style>
body {font-family: sans-serif;
	font-size: 10pt;
}
p {	margin: 0pt; }
table.items {
	border: 0.1mm solid #000000;
}
td { vertical-align: middle; }
.items td {
	border: 0.1mm solid #888888;;
	/*border-right: 0.1mm solid #000000;*/
}
table thead td { background-color: #EEEEEE;
	text-align: center;
	border: 0.1mm solid #000000;
	font-variant: small-caps;
        height: 30px;
       
}
.eval thead td { 
	text-align: center;
	border: 0.1mm solid #EEEEEE;
	font-variant: small-caps;
  font-size: 7pt;
  height: 15px;
       
}
.eval td { 
	text-align: left;
	border: 0.1mm solid #EEEEEE;
        padding-left: 5px;
	
        
        font-size: 7pt;
}

.items td.blanktotal {
	background-color: #EEEEEE;
	border: 0.1mm solid #000000;
	background-color: #FFFFFF;
	border: 0mm none #000000;
	border-top: 0.1mm solid #000000;
	border-right: 0.1mm solid #000000;
}
.items td.totals {
	text-align: right;
	border: 0.1mm solid #000000;
}
.items td.cost {
	text-align: "." center;
}
</style>
</head>
<body>
<!--mpdf
<htmlpageheader name="myheader">
<table width="100%"><tr>
<td><img src="'.$this->logo.'" width="125px" height="100px"></td><td width="50%" style="color:#0000BB;  vertical-align: middle;"><span style="font-weight: bold; font-size: 14pt;">'.$this->school.'</span><br />'.$this->faculty.'<br />'.$this->filiere.'<br /></td>
<td width="50%" style="text-align: right; vertical-align: middle;">Année Académique<br /><span style="font-weight: bold; font-size: 12pt;">'.$this->acadYr.'<br />'.$this->semestre.'</span></td>
</tr></table>
<hr>
</htmlpageheader>
<htmlpagefooter name="myfooter">
<div style="border-top: 1px solid #000000; font-size: 9pt; text-align: right; padding-top: 3mm; ">
<span>Page {PAGENO}/{nb}</span>
</div>
<div style=" font-size: 6pt; text-align: center;  ">Report generated with UdMAcademy By ppwangun (' . date("d-m-Y H:i") .')</div>
</htmlpagefooter>
<sethtmlpageheader name="myheader" value="on" show-this-page="1" />
<sethtmlpagefooter name="myfooter" value="on" />
mpdf-->

<table width="100%" style="font-family: serif;" cellpadding="2">
<tr><td colspan="3" style="text-align: center;">PROCES VERBAL RECAPTITULATIF DU MODULE</td></tr>
<tr>
<td style="text-rotate: 90; width: 5%; border: 0.1mm solid #888888; text-align: center; padding:10px;"><span style="font-size: 16pt; font-weight: bold;">'.$this->classe.'</span></td>
<td width="70%" style="border: 0.1mm solid #888888; "><span style="font-size: 10pt; color: #555555; font-family: sans;"><strong> Module:</strong> '.$this->module.'<br /><strong>UE: </strong>'.$this->subjectCode.' ('.$this->subjectName.')<br /><strong>Inscrits:&nbsp; </strong>'.$this->totalStudent.'&nbsp;&nbsp;&nbsp;&nbsp;<b>Admis:</b>&nbsp;'.$totalAdmis.'&nbsp;&nbsp;&nbsp;&nbsp;<b>Echecs:</b>&nbsp;'.$this->totalFailure.'&nbsp;&nbsp;&nbsp;<b>Taux de réussite:</b>&nbsp;'. number_format(($totalAdmis/$this->totalStudent)*100,2) .'%</td>

<td width="25%" style="border: 0.1mm solid #888888;"><span style="font-size: 7pt; color: #555555; font-family: sans;"> </span></td>
</tr></table>
<br />
<table class="items" width="100%" style="font-size: 9pt; border-collapse: collapse; " >
<thead>


<!-- ITEMS HERE -->
';


$tblBody.= '<tr>';
foreach($students[0] as $key=>$values) $tblBody .='<td style="" >'.$key.'</td>';
$tblBody .='</tr>'
            .'</thead>'
            .' <tbody>';

foreach($students as $stud)
{
    $tblBody.="<tr>";
    foreach($stud as $key=>$values) $tblBody .= '<td style="'.(($key=="grade"||$key=="points")&&($stud["grade"]=="F"||$stud["grade"]=="E")? "background-color: #bb1924; color: #ffffff; font-weight: bold;" : "").'">'.$values.'</td>';
    $tblBody.=  "</tr>";
    //print_r($stud); exit;

    /*foreach($stud as $std)
    {
        //Table header
        
        $tblBody.= '<td>'.$values.'</td>';
    }*/
 
}


$tblBody.='
</tbody>
</table>
<div style="text-align: center; font-style: italic;">Le delais de soumission des requêtes est fixés à 2 semaines après publication</div>
</body>
</html>
';



$mpdf = new \Mpdf\Mpdf([
	'margin_left' => 20,
	'margin_right' => 15,
	'margin_top' => 38,
	'margin_bottom' => 25,
	'margin_header' => 5,
	'margin_footer' => 10
]);

$mpdf->SetProtection(array('print'));
$mpdf->SetTitle("Acme Trading Co. - Invoice");
$mpdf->SetAuthor("W-TECH");
$mpdf->SetWatermarkText("Version d'evaluation");
$mpdf->showWatermarkText = true;
$mpdf->watermark_font = 'DejaVuSansCondensed';
$mpdf->watermarkTextAlpha = 0.1;
$mpdf->SetDisplayMode('fullpage');

$mpdf->WriteHTML($tblBody);



ob_end_clean();
//Close and output PDF document
$mpdf->Output($_SERVER["DOCUMENT_ROOT"].'/impressions/'.preg_replace('/\s+/', '',"test").'-'.date("d-m-Y-H-i").'.pdf', 'F');
?>

        <style> 
.md-datepicker-calendar-pane{
z-index: 120000}

.md-select-menu-container {z-index: 120000;}
</style>

   <md-dialog style="max-width: 100%;
            max-height: 100%;
    width: 100%;
    height: 100%;
    border-radius: 0;" aria-label="Mango (Fruit)">
  <form ng-cloak>
    <md-toolbar>
      <div class="md-toolbar-tools">
        <h2>Impression PV Individuel</h2>
        <span flex></span>
        <md-button class="md-icon-button" ng-click="cancel()">
          <md-icon md-svg-src="img/ic_close_24px.svg" aria-label="Close dialog"></md-icon>
        </md-button>
      </div>
    </md-toolbar>

    <md-dialog-content>
      <div  class="md-dialog-content">

          <embed src=<?=$this->serverUrl().'/impressions/'.preg_replace('/\s+/', '',"test").'-'.date("d-m-Y-H-i").'.pdf';?> type="application/pdf" style="width:100%;height:600px;"  />
                     


      </div>
    </md-dialog-content>

    <md-dialog-actions layout="row">

      <span flex></span>
      <md-button ng-click="cancel()">
       Fermer
      </md-button>

    </md-dialog-actions>
  </form>
</md-dialog>