
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<?php
//============================================================+
// File name   : example_048.php
// Begin       : 2009-03-20
// Last Update : 2013-05-14
//
// Description : Example 048 for TCPDF class
//               HTML tables and table headers
//
// Author: Nicola Asuni
//
// (c) Copyright:
//               Nicola Asuni
//               Tecnick.com LTD
//               www.tecnick.com
//               info@tecnick.com
//============================================================+

/**
 * Creates an example PDF TEST document using TCPDF
 * @package com.tecnick.tcpdf
 * @abstract TCPDF - Example: HTML tables and table headers
 * @author Nicola Asuni
 * @since 2009-03-20
 */

class PDF extends TCPDF {
    //
    // This class extends FPDF so we may customize the header and footer
    // of the PDFs that are created
    //

    function Footer() {
        $footertext="Report generated with UdMAcademy By ppwangun (" . date("d-m-Y H:i") . ")";
        // Position at 15 mm from bottom
        $this->SetY(-15);
        $this->SetFont('helvetica', '', 6);
        // Page number
         
        $this->Cell(0, 5, 'Page '.$this->getAliasNumPage().'/'.$this->getAliasNbPages(), 0, false, 'C', 0, '', 0, false, 'T', 'M');
        $html ='<hr>';
        $this->writeHTML($html, true, false, true, false, '');
        $this->writeHTML($footertext, false, true, false, true);
        $this->SetY(-20);
        $this->SetFont('freesans','I',8);
        $this->SetTextColor(34,68,136);
        $this->Cell(0, 5, 'TCC: Total crédits capitalisés sur le cycle TCI Total crédits inscrits sur le semestre'
                . ' MPS: Moyenne pondérée semestrielle MPC: Moyenne pndérée cumulée ', 0, false, 'L', 0, '', 0, false, 'T', 'M');
    
        
    }  // end of the Footer function
    
    public function Test( $ae ) {
        if( !isset($this->xywalter) ) {
            $this->xywalter = array();
        }
        $this->xywalter[] = array($this->GetX(), $this->GetY());
    }    
    
}

// create new PDF document
$pdf = new PDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);

// set document information
$pdf->SetCreator(PDF_CREATOR);
$pdf->SetAuthor('Nicola Asuni');
$pdf->SetTitle('Universté des Montagnes');
$pdf->SetSubject('TCPDF Tutorial');
$pdf->SetKeywords('TCPDF, PDF, example, test, guide');


// set default header data
$pdf->SetHeaderData('', 0, 'Universté des Montagnes', $this->faculty."\n".$this->filiere."\n".$this->acadYr."/".$this->semestre);

// set header and footer fonts
$pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
$pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));

// set default monospaced font
$pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);

// set margins
$pdf->SetMargins(PDF_MARGIN_LEFT, PDF_MARGIN_TOP, PDF_MARGIN_RIGHT);
$pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
$pdf->SetFooterMargin(PDF_MARGIN_FOOTER);

// set auto page breaks
$pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);

// set image scale factor
$pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);

// set some language-dependent strings (optional)
if (@file_exists(dirname(__FILE__).'/lang/eng.php')) {
    require_once(dirname(__FILE__).'/lang/eng.php');
    $pdf->setLanguageArray($l);
}

// ---------------------------------------------------------

// set font
$pdf->SetFont('helvetica', 'B', 12);

// add a page
$pdf->AddPage('L','A4');
//$pdf->Write(0, $this->classe, '', 0, 'L', true, 0, false, false, 0);
//$pdf->Write(0, $nomUe.':    '.$codeUe, '', 0, 'L', true, 0, false, false, 0);
$pdf->SetFont('helvetica', '', 2);
$pdf->Write(0, '', '', 0, 'L', true, 0, false, false, 0);
$pdf->SetFont('helvetica', '', 8);

// set Rotate
$params = $pdf->serializeTCPDFtagParameters(array(90));

// other configs
$pdf->setOpenCell(0);
$pdf->SetCellPadding(0);
$pdf->setCellHeightRatio(1.25);

function createHeader($students,$width_sem_1,$width_col_1,$width_col_2,$width_mps,$font_header_size,$font_size,$width_grd,$width_moy,$width_col_suject,$font_mark_size)
{
    $width_span1= ($width_col_1+$width_col_2+6); 
    $width_span2 = $width_col_suject*9;
    $width_span3 = ($width_mps*6)+6;
    
    $color= "#dcdde1;";
    $tblHeader_1 = '<tr style="font-size: 12px; color:#000080;"><th  colspan="3" style="height: 60px; vertical-align:center; width:'.$width_span1.'%;"></th>'
            . '<th colspan="'.$totalSubjects.'" align="center"  style=" width:'.$width_span2.'%; background-color:'.$color.';" ><br />EXAMEN DE SYNTHESE CLINIQUE ET THEURAPETIQUE<br /></th>'
            .'<th colspan="2" align="center"  style="width:'.($width_col_suject*2).'%; background-color:'.$color.';">THESE</th>'
            . '<th colspan="6" style=" width:'.$width_span3.'%; background-color:'.$color.';"></th></tr>';
    $tblHeader = '<tr style="background-color:#428bca; font-size: 8px;">';
    $counter = 0;
    $tblHeader_2 ='<tr   style="background-color:#428bca; font-size: '.$font_header_size.' ">';
    foreach($students[0] as $key=>$values)
    {
        if(strtolower($key)==strtolower("MPCPREV"))
        {   
            
            $tblHeader.= '<th style = " font-size: '.$font_header_size.';" width='.$width_sem_1.'% >MPC </th>';
            //Doing nothing
        }
        if(strtolower($key)==strtolower("CrV"))
        {   
            
            $tblHeader.= '<th style = " font-size: '.$font_header_size.'; " width:'.$width_sem_1.'% >TCC </th>';
            //Doing nothing
        }
       // $tblHeader.= '<th rowspan="2" style = "height: 20px; text-align: center; width: '.$width_col_1.' text-align: center;"><strong>'.ucwords(strtoupper($key)).'</strong></th>';

       
    }
   
    
    $tblHeader =$tblHeader.'</tr>';
    
    foreach($students[0] as $key=>$values)
    {
       
        $colspan = "1";
        if(strtolower($key)=="matricule" )
        {

            $tblHeader_2.= '<th rowspan="2"   style = "height: 20px; text-align: center; font-size: '.$font_header_size.'; width: '.$width_col_1.'% text-align: center;"><strong>Matricule</strong></th>';
        }
        elseif(strtolower($key)=="nom" )
        {
            $width = "22%;";
             $tblHeader_2.= '<th rowspan="2"  style = "height: 20px; text-align: center; font-size: '.$font_header_size.'; width: '.$width_col_2.'% text-align: center;"><strong>Nom(s) et Prénom(s)</strong></th>';
             $tblHeader_2.= '<th  colspan="2" width ="6%"><strong>SEM N-1</strong></th>';
        }
        elseif(strtolower($key)=="tci" || strtolower($key)=="tcc" || strtolower($key)=="mps" || strtolower($key)=="mpc" )
        {
             $tblHeader_2.= '<th rowspan="2"  style = "height: 20px; padding:8px; width: '.$width_mps.'%; text-align: center;"><strong>'.$key.'</strong></th>';
        }
        elseif(strtolower($key)==strtolower("note".$counter))
        {   
            $counter++;
            //Doing nothing
        }
        elseif(strtolower($key)==strtolower("MPCPREV")||strtolower($key)==strtolower("CrV"))
        {   
            
         
            //Doing nothing
        }
        elseif(strtolower($key)==strtolower("PERCENTAGE")) {//Doing nothing
            $tblHeader_2.= '<th rowspan="2"  style = "height: 20px;  width:5.5%; text-align: center;"><strong>Décision</strong></th>';            
        }
        elseif(strtolower($key)==strtolower("MENTION")) {//Doing nothing
            $tblHeader_2.= '<th rowspan="2"  style = "height: 20px;  width:7.5%; text-align: center;"><strong>Mention</strong></th>';
        }        
        else{ 
            if($counter==7||$counter==9||$counter==0||$counter==11) $key = preg_replace("/[0-9]/", "", $key);
                    
            $tblHeader_2.= '<th rowspan="2" style = " font-size: '.$font_header_size.'; height: 20px; padding:8px; width: '.$width_col_suject.'%; text-align: center;"><tcpdf method="Test" params="'.$params.'" />'.$key.'</th>';
        }       // else $width = "";
        //Table header
       
    }
$tblHeader_2 =$tblHeader_2.'</tr>';
    

$tblHeader =$tblHeader_1.$tblHeader_2.$tblHeader;
return $tblHeader;
}

$students = $this->students;

//report template configuration
//we are going to construc the template by considering the number of the column to display

//Number of columns

$numColumns = sizeof($students[0]);

                $width_col_1 = "5";
                $width_col_2 = "20";
                $width_mps = "3.5";
                $font_header_size = "10px";
                $font_size = "10px;";
                $font_mark_size = "10px;";
                $width_sem_1 = "3";
                //echo $numColumns; exit;
            if($numColumns<=25) $width_col_suject = "6";
            elseif($numColumns<=28) $width_col_suject = "5";
            elseif($numColumns<=32) $width_col_suject = "4";
            else $width_col_suject = "3";
                
       

$tblHeader = createHeader($students,$width_sem_1,$width_col_1,$width_col_2,$width_mps,$font_header_size,$font_size,$width_grd,$width_moy,$width_col_suject,$font_mark_size);



$tblBody = '';
$i=0;

foreach($students as $stud)
{
    $tblBody.='<tr nobr="true">';
    $counter = 0;
    
    foreach($stud as $key=>$value)
    {
        //Table header
        $align = "center";
        $color = "#ffffff;";
        
        if(strtolower($key)=="matricule" )
        {

            $tblBody.= '<td style = "font-size: '.$font_size.' width: '.$width_col_1.'%; text-align: '.$align.'; "> &nbsp;'.$value.'</td>'; 
        }
        elseif(strtolower($key)=="nom" )
        {
            
            $align = "left;";
            $tblBody.= '<td style = "font-size: '.$font_size.' width: '.$width_col_2.'%; text-align: '.$align.'"> &nbsp;'.$value.'</td>'; 
        }
        elseif(strtolower($key)==strtolower("CrV") )
        {
            
            $align = "left;";
            $color= "#D8BFD8;";
            $tcc = $value;
            $tblBody.= '<td style = "font-size: '.$font_size.'; background-color: '.$color.'; text-align: '.$align.'; width: '.$width_sem_1.'%"> &nbsp;'.$value.'</td>'; 
        } 
        elseif(strtolower($key)==strtolower("MPCPREV") )
        {
            
            $align = "left;";
            $color= "#D8BFD8;";
            $tblBody.= '<td style = "font-size: '.$font_size.'; background-color: '.$color.';  text-align: '.$align.'; width: '.$width_sem_1.'%"> &nbsp;'.$value.'</td>'; 
        }        
        elseif(strtolower($key)=="tci" || strtolower($key)=="mps" || strtolower($key)=="mpc"  || strtolower($key)=="tcc")
        {
            
            if(strtolower($key)=="tci")  $color_1= "#dcdde1;"; 
            if(strtolower($key)=="tcc")  $color_1= "#c8d6e5;";  
            if(strtolower($key)=="mps")   $color_1= "#7f8fa6;";
            if(strtolower($key)=="mpc")   $color_1= "#718093;";
            $tblBody.= '<td style = "font-weight: bold; font-size: '.$font_size.' background-color:'.$color_1.' width: '.$width_mps.'%; text-align: '.$align.'"> &nbsp;'.$value.'</td>'; 
        
        }
       
        elseif(strtolower($key)==strtolower("note".$counter) )
        {
            $color_font = "#000000;";
            $color = "#fff;";
            if($counter==9||$counter==10)  $color= "#D8BFD8;";
            if($counter==8||$counter==7)  $color= "#dcdde1;";
           
          if($value["grd"]=="F"||$value["grd"]=="E") {$color = "#bb1924;"; $color_font ="#ffffff;";}
          //$tblBody.= '<td style = "color:'.$color_font.'  font-size: '.$font_mark_size.' background-color:'.$color.' width: '.$width_moy.'; text-align: '.$align.'"> &nbsp; '.$value["moy"].'</td>'; 
          $tblBody.= '<td style = "color: '.$color_font.' font-size: '.$font_mark_size.' width: '.$width_col_suject.'%; background-color:'.$color.'   text-align: '.$align.'"> &nbsp;'.$value["grd"].'</td>'; 
          $counter++;
        }
        elseif(strtolower($key)==strtolower("MENTION")) $mention = $value;
        elseif(strtolower($key)==strtolower("PERCENTAGE")) $percentage = (($value<100)?"REDOUBLE":"ADMIS");

      
        
    }
    $tblBody.= '<td style = "color: '.$color_font.' font-size: 8px; width:5.5%; color:'.(strcmp($percentage,"REDOUBLE")==0?"#4B0082":"#4B0082").';   text-align: '.$align.'"> &nbsp;'.$percentage.'</td>';
    $tblBody.= '<td style = "color: '.$color_font.' font-size:8px; width: 7.5%; color:#000080;"> &nbsp;'.$mention.'</td>';
    
    $tblBody.='</tr>';
}

function createHeader2($students,$numColumns,$width_col_1,$width_col_2,$width_mps,$font_header_size,$font_size,$width_grd,$width_moy,$width_col_suject,$font_mark_size)
{
    
    $counter = 0;
    $tblHeader_2 ='<tr   style="background-color:#428bca; font-size: '.$font_header_size.' ">';

   
   
    
    foreach($students[0] as $key=>$values)
    {
       
        $colspan = "1";
        if(strtolower($key)=="matricule" )
        {

            $tblHeader_2.= '<th style = " text-align: center; font-size: '.$font_header_size.'; width: '.$width_col_1.' text-align: center;"><strong>Matricule</strong></th>';
        }
        elseif(strtolower($key)=="nom" )
        {
            $width = "22%;";
             $tblHeader_2.= '<th   style = " text-align: center; font-size: '.$font_header_size.'; width: '.$width_col_2.' text-align: center;"><strong>Nom(s) et Prénom(s)</strong></th>';
             //$tblHeader_2.= '<th  colspan="2"><strong>SEM N-1</strong></th>';
        }
        elseif(strtolower($key)=="tci" || strtolower($key)=="tcc" || strtolower($key)=="mps" || strtolower($key)=="mpc" )
        {
             $tblHeader_2.= '<th   style = " padding:8px; width: '.$width_mps.'; text-align: center;"><strong>'.$key.'</strong></th>';
        }
        elseif(strtolower($key)==strtolower("note".$counter))
        {   
            $counter++;
            //Doing nothing
        }
       /* elseif(strtolower($key)==strtolower("MPCPREV")||strtolower($key)==strtolower("CrV"))
        {   
            
         
            //Doing nothing
        } */       
      
        else{ 

             $tblHeader_2.= '<th  style = " font-size: '.$font_header_size.'; height: 20px; padding:8px; width: '.$width_col_suject.'; text-align: center;"><strong>'.ucwords(strtoupper($key)).'</strong></th>';
        }       // else $width = "";
        //Table header
       
    }
$tblHeader_2 =$tblHeader_2.'</tr>';
    

$tblHeader =$tblHeader_2;
return $tblHeader;
}

$tblHeader = createHeader($students,$numColumns,$width_col_1,$width_col_2,$width_mps,$font_header_size,$font_size,$width_grd,$width_moy,$width_col_suject,$font_mark_size);

$tbl2Body = '';
foreach($studentsWithBaclogs as $stud)
{
    $tbl2Body.='<tr nobr="true">';
    $counter = 0;
    foreach($stud as $key=>$value)
    {
        //Table header
        $align = "center";
        $color = "#ffffff;";
        
        if(strtolower($key)=="matricule" )
        {

            $tbl2Body.= '<td style = "font-size: '.$font_size.' width: '.$width_col_1.'; text-align: '.$align.'; "> &nbsp;'.$value.'</td>'; 
        }
        elseif(strtolower($key)=="nom" )
        {
            
            $align = "left;";
            $tbl2Body.= '<td style = "font-size: '.$font_size.' width: '.$width_col_2.'; text-align: '.$align.'"> &nbsp;'.$value.'</td>'; 
        }
        elseif(strtolower($key)=="tci" || strtolower($key)=="tcC" || strtolower($key)=="mps" || strtolower($key)=="mpc" )
        {
            
            if(strtolower($key)=="tcri")  $color_1= "#dcdde1;"; 
            if(strtolower($key)=="tcrv")  $color_1= "#c8d6e5;";  
            if(strtolower($key)=="mps")   $color_1= "#7f8fa6;";
            if(strtolower($key)=="mpc")   $color_1= "#718093;";
            $tbl2Body.= '<td style = "font-size: '.$font_size.' background-color:'.$color_1.' width: '.$width_mps.'; text-align: '.$align.'"> &nbsp;'.$value.'</td>'; 
        
        }
        elseif(strtolower($key)==strtolower("note".$counter) )
        {
            $color_font = "#000000;";
           
          if($value["grd"]=="F"||$value["grd"]=="E") {$color = "#bb1924;"; $color_font ="#ffffff;";}
          if($value["grd"]==""||$value["grd"]=="") {$color = "#E8E8E8;"; $color_font ="#ffffff;";}
          $tbl2Body.= '<td style = "color: '.$color_font.' font-size: '.$font_mark_size.' width: '.$width_col_suject.'; background-color:'.$color.'   text-align: '.$align.'"> &nbsp;'.(($value["grd"])?$value["grd"]:$value["moy"]).'</td>'; 
         // $tbl2Body.= '<td style = "color: '.$color_font.' font-size: '.$font_mark_size.' background-color:'.$color.'  width: '.$width_grd.'; text-align: '.$align.'"> &nbsp;'.$value["grd"].'</td>'; 
          $counter++;
        }
      
        
    }
    $tbl2Body.='</tr>';
}



$numColumns = sizeof($studentsWithBaclogs[0]);
$tblHeader2 = createHeader2($studentsWithBaclogs,$numColumns,$width_col_1,$width_col_2,$width_mps,$font_header_size,$font_size,$width_grd,$width_moy,$width_col_suject,$font_mark_size);
$tbl = '<thead>'.$tblHeader.'</thead>'.$tblBody;
$tbl2 = '<thead>'.$tblHeader2.'</thead>'.$tbl2Body;
//

//$pdf->SetY(50);
$pdf->SetFont('helvetica', '', 14);

$tbl1 = <<<EOD
    <table border="1" cellspacing="0" cellpadding="1">

        <tbody><tr style="background-color:#dcdde1;" ><td width="965px"  style="font-size:14px; font-weight:bold; text-align:center" align="center">
            VALIDATION DU CURSUS DES ETUDIANTS DE MEDECINE DE L'INSTITUT SUPERIEUR DES SCIENCES DE LA SANTE DE BANGANGTE A L'ISSUE DE L'EXAMEN
      NATIONAL DE SYNTHESE CLINIQUE ET THERAPEUTIQUE ET DES SOUTENANCES DE THESES
    </td></tr></tbody>
        </table>
EOD;

$pdf->writeHTML($tbl1, true, false,true, false, 'c');
$date = date("d-m-Y");
$tbl1 = <<<EOD
    <table cellspacing="0" cellpadding="1">

        <tbody><tr width="975px" ><td  width="700px"  style="font-size:14px;">
            <b>ANNEE ACADEMIQUE:</b>$this->acadYr</td> <td><b>REF:</b></td></tr>
        <tr><td style="font-size:14px;">
            <b>PROCES VERBAL DE DELIBERATION FINALE:</b> $date
    </td><td></td></tr></tbody>
        </table>
EOD;

$pdf->writeHTML($tbl1, true, false,true, false, 'c');

$pdf->SetFont('helvetica', 'B', 16);
//echo $numColumns; exit;
$tbl = <<<EOD
       
        <table cellspacing="0" cellpadding="1" border="1" margin="15px">
    $tbl
        </table>
EOD;
$pdf->writeHTML($tbl, true, false,true, false, 'c');
if(!empty($this->studentsWithBaclogs))
{
$pdf->addPage();
$pdf->SetFont('helvetica', 'B', 16);
$pdf->Cell(0, 0, 'DETTES', 0, 0, '');
$pdf->SetY(50);


$pdf->SetFont('helvetica', '', 8);
$tbl = <<<EOD
        <table cellspacing="0" cellpadding="1" border="1" margin="15px">
    $tbl2
        </table>   
EOD;

$pdf->writeHTML($tbl, true, false,true, false, 'c');
}

$tbl = <<<EOD

        <table cellspacing="0" cellpadding="1" border="0" margin="15px" >
    <td style = "text-align: center; font-weight: bold; font-style: italic;">  Le président du jury </td><td style="text-align: center; font-weight: bold; font-style: italic;"> Les membres du jury</td><td style="text-align: center; font-weight: bold; font-style: italic;">Le rapporteur</td>
        </table>
EOD;

$pdf->SetFont('helvetica', '', 12);
$pdf->writeHTML($tbl, true, false, false, false, '');

$pdf->Cell(0, 50, '', 1, 1, 'C', 0, '', 0);

$pdf->SetFont('helvetica', '', 8);
// array with names of columns
/*$arr_nomes = array(
    array("ABRANGÃŠNCIA", 106, 89), // array(name, new X, new Y);
    array("SIGNIFICÃ‚NCIA", 8, 59),
    array("FÃSICO", 4, 52),
    array("BIÃ“TICO", 4, 52),
    array("SOCIOECONÃ”MICO", 4, 52),
    array("NATUREZA", 4, 52),
    array("ORIGEM", 4, 52),
    array("DURAÃ‡ÃƒO", 4, 52),
    array("OCORRÃŠNCIA / TEMPORALIDADE", 4, 52),
    array("FREQUÃŠNCIA", 4, 52),
    array("ESPACIALIZAÃ‡ÃƒO", 4, 52),
    array("REVERSIBILIDADE", 4, 52),
    array("MAGNITUDE", 4, 52),
    array("RELEVÃ‚NCIA", 4, 52)
);

// num of pages
$ttPages = $pdf->getNumPages();
for($i=1; $i<=$ttPages; $i++) {
    // set page
    $pdf->setPage($i);
    // all columns of current page
    foreach( $arr_nomes as $num => $arrCols ) {
        $x = $pdf->xywalter[$num][0] + $arrCols[1]; // new X
        $y = $pdf->xywalter[$num][1] + $arrCols[2]; // new Y
        $n = $arrCols[0]; // column name
        // transforme Rotate
        $pdf->StartTransform();
        // Rotate 90 degrees counter-clockwise
        $pdf->Rotate(90, $x, $y);
        $pdf->Text($x, $y, $n);
        // Stop Transformation
        $pdf->StopTransform();
    }
}*/

ob_end_clean();
//Close and output PDF document

$pdf->Output($_SERVER["DOCUMENT_ROOT"].'impressions/'.preg_replace('/\s+/', '',$this->classe.$this->semestre).'-'.date("d-m-Y-H-i").'.pdf', 'F');
?>

        <style> 
.md-datepicker-calendar-pane{
z-index: 120000}

.md-select-menu-container {z-index: 120000;}
</style>

   <md-dialog style="max-width: 100%;
            max-height: 100%;
    width: 100%;
    height: 100%;
    border-radius: 0;" aria-label="Mango (Fruit)">
  <form ng-cloak>
    <md-toolbar>
      <div class="md-toolbar-tools">
        <h2>Impression PV Individuel</h2>
        <span flex></span>
        <md-button class="md-icon-button" ng-click="cancel()">
          <md-icon md-svg-src="img/ic_close_24px.svg" aria-label="Close dialog"></md-icon>
        </md-button>
      </div>
    </md-toolbar>

    <md-dialog-content>
      <div  class="md-dialog-content">

          <embed src=<?=$this->serverUrl().'/impressions/'.preg_replace('/\s+/', '',$this->classe.$this->semestre.'-').date("d-m-Y-H-i").'.pdf';?> type="application/pdf" style="width:100%;height:600px;"  />
                     


      </div>
    </md-dialog-content>

    <md-dialog-actions layout="row">

      <span flex></span>
      <md-button ng-click="cancel()">
       Fermer
      </md-button>

    </md-dialog-actions>
  </form>
</md-dialog>