
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<?php

$totalAdmis = $this->totalStudent - $this->totalFailure;
$grode_of_failures = ["F","E"];
//if($this->cycle_level == 1)  $grode_of_failures = ["F","E","D","D+","C-"];
//else $grode_of_failures = ["F","E","D","D+","C-","C","C+"];

if(sizeof($this->exams)>0)
{
    $tbHeader = '<table class="eval" cellspacing="0"  margin="15px">'
            . '<thead>'
            . '<tr><td colspan="3" >EVALUATIONS REALISEES:</td></tr>';
    $tbHeader .= '</thead>';
   $tbBody = "";
    foreach($exams as $value)
    {
        //$date1 = new \DateTime($value["date"]);
        //$date = $date1->format('Y-m-d');
        $tbBody.='<tr><td style="width: 10%">'.$value["type"].'</td><td style="width: 50%" >'.$value["code"].'</td><td style="width: 20%">'.$value["date"]->format("d/m/Y").'</td></tr>';
        
    }
    $tbExams=$tbHeader.$tbBody.'</table>';



//$pdf->writeHTML($tb, true, false, false, false, '');
    
}
$totalAdmis = $this->totalStudent - $this->totalFailure;
//($this->typeExam=="CC")||($this->typeExam=="CCTP")?$width="16.6%":$width="12.5%";
$width="9%";

$codeUe = $students[0]['codeUe']; 
$nomUe  = $students[0]['nomUe']; 
$tblBody = '
<html>
<head>
<style>
body {font-family: sans-serif;
	font-size: 10pt;
}
p {	margin: 0pt; }
table.items {
	border: 1px solid #000000;
}
td { vertical-align: middle; }
.items td {
	border: 1px solid #000000;;
	border-right: 0.1mm solid #000000;
        
}
table thead td { background-color: #EEEEEE;
	text-align: center;
	border: 1px solid #888888;
	font-variant: small-caps;
        height: 30px;
       
}
#exam {
    border-collapse: collapse; 
    border: 1px solid #000000;
    width: 100%;
}

#exam td,th {
    border: 1px solid #000000;
    text-align: center;
    color: #0047AB;
}

#stats td,#stats th {
    border: 0.1mm solid #000000;
    text-align: center;
    color: #0047AB;
}
  table.subtable { 
    border-collapse: collapse; 
    border: 1px solid #000000;
    width: 100%;
  }
  table.subtable td, 
  table.subtable th { 
    border: 0.1mm solid #000000; 
    font-size: 10pts;
    height: 15px; 
    text-align: left;
    font-variant: normal;
  }
    input.Checkbox {
      width: 140px;
      height: 140px;
    }
        
.eval thead td { 
	text-align: center;
	border: 0.1mm solid #EEEEEE;
	font-variant: small-caps;
  font-size: 7pt;
  height: 15px;
       
}
.eval td { 
	text-align: left;
	border: 0.1mm solid #EEEEEE;
        padding-left: 5px;
	
        
        font-size: 7pt;
}

.items td.blanktotal {
	background-color: #EEEEEE;
	border: 0.1mm solid #000000;
	background-color: #FFFFFF;
	border: 0mm none #000000;
	border-top: 0.1mm solid #000000;
	border-right: 0.1mm solid #000000;
}
.items td.totals {
	text-align: right;
	border: 0.1mm solid #000000;
}
.items td.cost {
	text-align: "." center;
}
</style>
</head>
<body>
<!--mpdf
<htmlpageheader name="myheader">
<table width="100%"><tr>
<td></td><td width="50%" style="color:#0000BB;  vertical-align: middle;"><span style="font-weight: bold; font-size: 14pt;">'.$this->school.'</span><br />'.$this->faculty.'<br />'.$this->filiere.'<br /></td>
<td width="50%" style="text-align: right; vertical-align: middle;"><img src="'.$this->logo.'" width="75px" height="75x"></td>
</tr></table>
<hr>
</htmlpageheader>

<htmlpagefooter name="myfooter">
<div style= "border-top: 1px solid #000000; font-size: 9pt; text-align: right; padding-top: 3mm; ">
<span>Page {PAGENO}/{nb}</span>
</div>
<div style=" font-size: 6pt; text-align: center;  ">'.$this->brandInfo.'</div>
</htmlpagefooter>

<sethtmlpageheader  name="myheader" value="on" show-this-page="1" />
<sethtmlpagefooter  name="myfooter" value="on"  />
mpdf-->

<table width="100%" style="font-family: serif; "  cellpadding="2">

<tr style="background-color:#dfe4ea;">
<td style=" width: 15%; border: 1px solid #000000;  text-align: center; "><span style="font-size: 14pt; font-weight: bold;">'.$this->classe.'</span></td> 


<td width="25%" style="border: 1px solid #000000; text-align: center;"><span style="font-size: 14pt; font-weight: bold;  font-family: sans; "> Année Académique '.$this->acadYr.' </span></td>
    <td width="25%" style="border: 1px solid #000000; text-align: center;"><span style="font-size: 14pt; font-weight: bold;  font-family: sans; text-align: center;"> '.$this->semestre.' </span></td>
</tr>
<tr style="background-color:#F4F3F4;"><td colspan="3" style="text-align: center;"><strong>PROCES VERBAL DE LA MATIERE</strong>:  '.$subjectName. '('.$subjectCode.')</td></tr>
</table>
';
$students = $this->students;
$subjects = $this->subjects;
$exams = $this->exams;

if(sizeof($exams)>0)
{
    $tbHeader = '<tr><th colspan="4" >Evaluations effectuées:</th></tr>';
    $tbHeader .= '<tr><th align="center" style=""><strong> Type </strong></th><th style="" align="center"><strong> Code </strong></th><th style="" align="center"><strong> Matière </strong></th><th style="" align="center"> Date</th></tr>';
   $tbBody = "";
    foreach($exams as $value)
    {

        $tbBody.='<tr><td style="">'.$value["type"].'</td><td style="width: 50%" >'.$value["code"].'</td><td style="">'.$value["subject"].'</td><td style="">'.$value["date"]->format('d-m-Y').'</td></tr>';
        
    }
    $tb=$tbHeader.$tbBody;

    
    
$tb1 = '<table id ="exam "style=" width:100%">'.$tb.'</table>';
}
$totalAdmis = $this->totalStudent - $this->totalFailure;
$tbHeader = '<tr><th style=" color: red; font-style: normal; font-weight: bold;">Crédits: '.$this->credits.'</th><th style="border: 0px;" colspan="3"></th></tr>'
        . '<tr style="color: #0c4c8c; font-style: italic;"><th align="center" ><strong>Inscrits</strong></th><th align="center" ><strong>Admis</strong></th><th align="center" ><strong>Echecs</strong></th><th align="center"><strong>Taux de reussite</strong></th></tr>';
$tbBody='<tr style="color:#0c4c8c; font-style: italic;"><td align="center">'.$this->totalStudent.'</td><td align="center" >'.$totalAdmis.'</td><td align="center">'.$this->totalFailure.'</td><td align="center">'. number_format(($totalAdmis/$this->totalStudent)*100,2) .'%</td></tr>';
$tb=$tbHeader.$tbBody; 

$tb2 = '<table id="stats"  style="width:100%" >'.$tb.'</table>';

$tblBody.='<table width="100%" style="font-size: 8pts; " ><tr style="background-color: #edf0f5;">'
        . '<td style="text-align:left; width: 60% ">'.$tb2.'</td>'
        . '<td  style="text-align:right; width: 40% ">'.$tb1.'</td>'
        . '</tr></table>

<!-- ITEMS HERE -->
';


$tblBody.=  '<table  class="subtable" >
        <thead>
            <tr style="background-color:#F4F3F4;">
            <th style = "width: 4%; height: 20px; text-align: center;"><strong>N°</strong></th>
            <th style = "width: 10%; text-align: center;"><strong>Matricule</strong></th>
            <th style = "width: 41%; text-align: center; "><strong>Nom et Prénoms</strong></th>
            <th style = "width: 6%; text-align: center;"><strong>CC</strong></th>
            <th style = "width: 6%; text-align: center;"><strong>CCTP</strong></th>
            <th style = "width: 9%; text-align: center;"><strong>EXAMTP</strong></th>
            <th style = "width: 7%; text-align: center;"><strong>EXAM</strong></th>
            <th style = "width: 7%; text-align: center;"><strong>MOY</strong></th>
            <th style = "width: 5%; text-align: center;"><strong>GRD</strong></th>
            <th style = "width: 5%; text-align: center;"><strong>PTS</strong></th></tr>'
        . '</thead>'
        .' <tbody>';


$i=0;
foreach($students as $stud)
{
   // print_r($stud); exit;
    $tblBody.= '<tr nobr="true" style ="'.(($stud["grade"]=="F")? "background-color: #FFF" : ""). '">';
    $tblBody.='<td style = "width: 4%; text-align: center;">'.(++$i).'</td>';
    $tblBody.='<td style = "width: 10%; text-align: center;">'.$stud['matricule'].'</td>';
    $tblBody.='<td style = "width: 41%; text-align:left;"> '.$stud['nom'].'</td>';
    $tblBody.='<td style = "width: 6%; text-align: center;"> '.$stud['noteCc'].'</td>';
    $tblBody.='<td style = "width: 6%; text-align: center;"> '.$stud['noteCctp'].'</td>';
    $tblBody.='<td style = "width: 9%; text-align: center;"> '.$stud['noteExamtp'].'</td>';
    $tblBody.='<td style = "width: 7%; text-align: center;"> '.$stud['noteExam'].'</td>';
    $tblBody.='<td style = "width: 7%; text-align: center; '.(($stud["grade"]=="F"||$stud["grade"]=="E")? "background-color: #bb1924; color: #ffffff; font-weight: bold;" : ""). '">'.(number_format($stud['noteFinal'],2)).'%</td>';
    $tblBody.='<td style = "width: 5%; text-align: center; '.(($stud["grade"]=="F"||$stud["grade"]=="E")? "background-color: #bb1924; color: #ffffff; font-weight: bold;" : ""). '">'.$stud['grade'].'</td>';
    $tblBody.='<td style = "width: 5%; text-align: center;"> '.$stud['points'].'</td>';
    /*foreach($stud as $std)
    {
        //Table header
        
        $tblBody.= '<td>'.$values.'</td>';
    }*/
    $tblBody.='</tr>';
}


$tblBody.='
</tbody>
</table>
<br />
<table width="100%" style="font-family: serif;" nobr="true" >
<tr tr nobr="true" style="background-color:#dfe4ea;">
<td  style="border: 1px solid #000000; font-weight: bold; text-align: center;"> VICE DOYEN</td>
<td  style="border: 1px solid #000000; font-weight: bold; text-align: center;"> COORDONATEUR</td>
<td  style="border: 1px solid #000000; font-weight: bold; text-align: center;"> RESP ACAEMIQUE</td>
<td colspan="2" style="border: 1px solid #000000; font-weight: bold; text-align: center;"> CHEF UNITE</td>
</tr>
<tr tr nobr="true" >
<br /><br /><br /><br />
</tr>
</table>


</body>
</html>
';



$mpdf = new \Mpdf\Mpdf([
	'margin_left' => 20,
	'margin_right' => 15,
	'margin_top' => 35,
	'margin_bottom' => 25,
	'margin_header' => 2,
	'margin_footer' => 5
]);

$mpdf->SetProtection(array('print'));
$mpdf->SetTitle("Acme Trading Co. - Invoice");
$mpdf->SetAuthor("W-TECH");
$mpdf->SetWatermarkText($this->school);
$mpdf->showWatermarkText = true;
$mpdf->watermark_font = 'DejaVuSansCondensed';
$mpdf->watermarkTextAlpha = 0.1;
$mpdf->SetDisplayMode('fullpage');

$mpdf->WriteHTML($tblBody);



ob_end_clean();
//Close and output PDF document
$mpdf->Output($_SERVER["DOCUMENT_ROOT"].'/impressions/'.preg_replace('/\s+/', '',"PV_MATIERE").'-'.date("d-m-Y-H-i").'.pdf', 'F');
?>

        <style> 
.md-datepicker-calendar-pane{
z-index: 120000}

.md-select-menu-container {z-index: 120000;}
</style>

   <md-dialog style="max-width: 100%;
            max-height: 100%;
    width: 100%;
    height: 100%;
    border-radius: 0;" aria-label="Mango (Fruit)">
  <form ng-cloak>
    <md-toolbar>
      <div class="md-toolbar-tools">
        <h2>Impression PV Individuel</h2>
        <span flex></span>
        <md-button class="md-icon-button" ng-click="cancel()">
          <md-icon md-svg-src="img/ic_close_24px.svg" aria-label="Close dialog"></md-icon>
        </md-button>
      </div>
    </md-toolbar>

    <md-dialog-content>
      <div  class="md-dialog-content">

          <embed src=<?=$this->serverUrl().'/impressions/'.preg_replace('/\s+/', '',"PV_MATIERE").'-'.date("d-m-Y-H-i").'.pdf';?> type="application/pdf" style="width:100%;height:600px;"  />
                     


      </div>
    </md-dialog-content>

    <md-dialog-actions layout="row">

      <span flex></span>
      <md-button ng-click="cancel()">
       Fermer
      </md-button>

    </md-dialog-actions>
  </form>
</md-dialog>