<script src="js/app/department/department.component.js"></script>
<link rel="stylesheet" href='js/datatables-plugins/dataTables.bootstrap.css'>


<style> 
.md-datepicker-calendar-pane{
z-index: 120000}

.md-select-menu-container {z-index: 120000;}

li.active a.ng-binding {
  color: #000 !important;
	background-color: #eeeeee !important;
	text-decoration: none;
}

</style>


<div class="well"  style="margin-left: -30px; margin-right: -30px; " ng-init="init()">
        
            <div class="row">
                <div class='col-md-4'>
                    <div></div>
                    <button ng-show=" <?=($this->access('global.system.admin', null))?true:false?> && !isUpdate"   type="button" ng-click="newBareme(grade)" class="btn btn-danger" ng-disabled="myForm.$invalid" ><span class="fa fa-plus-square"></span>&nbsp;Ajouter un barème</button>
                    <button  ng-show=" <?=($this->access('global.system.admin', null))?true:false?> && isUpdate" type="button" ng-click="updateBareme(grade)" class="btn btn-danger" ng-disabled="myForm.$invalid" ><span class="fa fa-edit"></span>&nbsp;Modifier le barème</button>
                    <span> <a href="#!/academicRankConfig">Retour</a></span>
                </div>
                <div class="col-md-8" > <h4>Barème de règlement des frais de vacation</h4></div>

                

                
            </div>
</div>

<div class="form-view-main">
    <div class="form-view">
        <div   ng-cloak class="md-inline-form">


    <md-content layout-padding >
        <form   name="myForm">

   
      <div class="md-dialog-content"  ng-init="init()">
        
        
            <div layout layout-sm="row">
                <md-input-container flex="flex " style="width: 60%; margin-top: 15px;" >
                    <label>Nom du grade:</label>
                    <input type='text'  name='name' ng-model="grade.name" width='80%' md-no-asterisk required />
                        <div ng-messages="myForm.name.$error">
                            <div ng-message="required">le champ nom du grade est obligatoire</div>
                            <div ng-message="minlength">le code doit avoir au moins 3 caractères</div>
                        </div>                    
        
                </md-input-container>
                <md-input-container class="md-block" flex-gt-sm></md-input-container>
            </div>
            <div layout layout-sm="row">
                <md-input-container flex="flex" style="width: 60%; margin-top: 15px;" >
                    <label>Code du grade:</label>
                    <input type='text'  name='code' ng-model="grade.code" width='80%'  md-no-asterisk required />
                        <div ng-messages="myForm.code.$error">
                            <div ng-message="required">le champ code est obligatoire</div>
                            <div ng-message="minlength">le code doit avoir au moins 3 caractères</div>
                        </div>                    
        
                </md-input-container> 
        
                                <md-input-container flex="flex" style="width: 20%; margin-top: 15px;" >
                  
                    <label>Montant de règlement des vacations /h:</label>
                    <input type='text'  name="payment_rate" ng-model="grade.paymentRate" width='80%'  md-no-asterisk required />
                        <div ng-messages="myForm.payment_rate.$error">
                            <div ng-message="required">le champ montant  est obligatoire</div>
                            <div ng-message="minlength">le code doit avoir au moins 3 caractères</div>
                        </div>
                </md-input-container> 
     
            </div>

      </div>
    </form>
  </md-content>
</div>
        

        
<p>&nbsp;</p>
              <!--tabs widget-->
              
    <uib-tabset>
      <uib-tab >
          <uib-tab-heading>
              <span>Liste des filières</span>
          </uib-tab-heading>
        <div class="tab-container">              
                <div class="row" >
                    <table class="table table-striped table-condensed">
                         <thead>
                             <tr class="bg-primary">
                                 <th>Num</th>
                                 <th>Intitulé du grade </th>
                                 <th>Code</th>
                                 <th>Barème de paiement</th>
                                 <th ></th>

                             </tr>
                         </thead>
                         <tbody>
                             <tr ng-repeat="grd in grades" >
                               <td >{{cpt + $index}}</td>
                               <td ng-bind="grd.name"></td> 
                               <td ng-bind="grd.code"></td>
                               <td ng-bind="grd.paymentRate"> </td>
                               <td>
                                   <div class="btn-group">
                                    <button type="button" ng-click="redirectbareme(grd.id)" class="btn btn-default btn-xs btn-info"><i class="fa fa-edit"></i></button>
                                    <button  type="button" ng-click="deleteGrade(grd)" class="btn btn-default btn-xs btn-danger" ><i class="fa fa-trash-o"></i></button>   
                                   </div>
                               </td>

                             </tr>
                         </tbody>
                     </table>
                 </div>
                <!--End tab-->
                
            </div>  
            </uib-tab>
              <uib-tab>
                <uib-tab-heading>
                    <span>Liste des Responsables</span>
                </uib-tab-heading>
                <div class="tab-container"> 
                </div>
            </uib-tab>
        </div>
   </md-content>
