


<style> 
.md-datepicker-calendar-pane{
z-index: 120000}

.md-select-menu-container {z-index: 120000;}



</style>
    
<div ng-cloak novalidate> 
    <div class="well" style="margin-left: -30px; margin-right: -30px;" ng-init="$ctrl.init();"> 
        <a ng-show= "$ctrl.showbillDetails" href="#!/subjectBilling">[Retrour]</a>
        <a ng-show= "!$ctrl.showbillDetails" href="#!/teacher-follow-up">[Retrour]</a>
            <div class="row text-align-center"> Facturation des frais de vacation</div>
            <div class="row">
                <div class='col-md-4'>

                </div>
                <div class="col-md-2"></div>

                
                <div class="pul-middle" >
                                <div class="btn-group">
                                    <button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown">
                                        Autres options
                                        <span class="caret"></span>
                                    </button>
                                    <ul class="dropdown-menu pull-right" role="menu">
                                        <li><a href="" ng-click="$ctrl.printNotes()"><span>Imprimer la facture</span></a>
                                        </li>
                                        <li><a href="" ng-click="$ctrl.printNotesFailures()"><span></span></a>
                                        </li>
                                        <!--<li><a href="" ng-click="$ctrl.clotureCalculNotes($ctrl.selectedUe.ue_class_id)"><span>Imprimer liste étudiants</span></a>
                                        </li> -->
                                    </ul>
                                </div>
                </div>
                
               
            </div>
        </div>

<div class="form-view-main">
    <div class="form-view">


<md-content layout-padding >

    <form   name="examForm" >
        <div layout-gt-sm='row' >

            <div class = "col-xs-6" >
                <div layout-gt-sm='row' >
                    <md-input-container class="md-block" flex-gt-sm>
                        <label>Enseignant:</label>
                        <md-autocomplete  md-search-text="$ctrl.searchTeacher" 
                                         md-selected-item="$ctrl.selectedTeacher"  
                                         md-items="item in $ctrl.queryTeacher($ctrl.searchTeacher)" 
                                         md-item-text="item.name" 
                                         md-min-length="0"
                                         placeholder="" 
                                         md-selected-item-change="$ctrl.selectedItemChange($ctrl.selectedTeacher)"
                                         md-input-name="Teacher"
                                         md-no-asterisk
                                         ng-disabled="$ctrl.showbillDetails"
                                         required>
                            <md-item-template>
                              <span md-highlight-text="$ctrl.searchTeacher" md-highlight-flags="^i">{{item.name}}</span>

                            </md-item-template>
                            <md-not-found>
                              Aucun élément correspondant à "{{$ctrl.searchTeacher}}" n'a été trouvé.

                            </md-not-found>
                        </md-autocomplete>
                            <div ng-messages="examForm.classe.$error">
                                <div ng-message="required">Ce champ est obligatoire</div>
                            </div> 
                    </md-input-container >
                </div>

          


                <div  ng-hide = "$ctrl.showbillDetails"  layout-gt-sm='column' style="padding-top: 15px">
                    <md-input-container>
                    <label>Unité d'enseignement affectés</label>
                    
                    <md-select name="ue" ng-disabled="!$ctrl.isActivatedUeSelect" ng-model="$ctrl.selectedUe;" 
                               ng-model-options="{trackBy: '$value.id'}"  
                               ng-change="$ctrl.loadBills($ctrl.selectedTeacher,$ctrl.selectedUe)" md-no-asterisk ng-required="true">
                        <md-option ng-hide="$ctrl.showbillDetails" ng-disabled="true" ng-selected="true" ng-value="{id:-1,code:-1}">
                            <em >Choisissez une UE</em>
                         
                        </md-option>
                    
                        
                        <md-option  ng-repeat="ue in $ctrl.assignedSubjects" ng-value="ue" >
                        {{ue.codeUe}}[{{ue.nomUe}}]

                      </md-option>


                    </md-select>
                    <div class="errors" ng-messages="examForm.ue.$error">
                        <div ng-message="required">Champ obligatoire</div>
                      </div>
                    </md-input-container> 

                </div>
                
                <div layout-gt-sm='column' style="padding-top: 15px" ng-show="$ctrl.showbillDetails">
                    <md-input-container>
                    <label>Unité d'enseignement affectés</label>
                    
                    <md-select name="ue" disabled ng-model="$ctrl.selectedUe;" 
                               ng-model-options="{trackBy: '$value.id'}"  
                                md-no-asterisk ng-required="true">

                        <md-option  ng-disabled="true" ng-selected="true" ng-value="$ctrl.selectedUe">
                            <em >{{$ctrl.selectedUe.codeUe}}[{{$ctrl.selectedUe.nomUe}}]</em>
                         
                        </md-option>                        
                        



                    </md-select>
                    <div class="errors" ng-messages="examForm.ue.$error">
                        <div ng-message="required">Champ obligatoire</div>
                      </div>
                    </md-input-container> 

                </div>      
                <div layout-gt-sm='column' style="padding-top: 15px" >
                    <md-input-container>
                    <label>Taux horaire</label>
                    
                    <md-select name="ue" disabled ng-model="$ctrl.paymentRate"  md-no-asterisk ng-required="true">

                        <md-option  ng-disabled="true" ng-selected="true" ng-value="$ctrl.paymentRate">
                            <em >{{$ctrl.paymentRate}}FCFA</em>
                         
                        </md-option>                        
                        



                    </md-select>
                    <div class="errors" ng-messages="examForm.ue.$error">
                        <div ng-message="required">Champ obligatoire</div>
                      </div>
                    </md-input-container> 

                </div>                 
           
            </div>

            <div class = "col-xs-6"  >
                <!-- Display examlis on a table -->
                <div class="row">

                    <table class="table" style="font-size:0.8em; background-color: #dfe4ea; color: #0c2461;" ng-show="tableBillsShow===1">
                    <thead>

                        <tr class="bg-primary">
                            <th class="col-xs-1 align-middle" >N°</th>
                            <th class=" align-middle" >N° Facture</th>
                            <th class=" align-middle">Volume Horaire</th>
                            <th class=" align-middle">Montant</th>
                            <th class=" align-middle">Date</th>
                            <th class=" align-middle">statut</th>
                            
                        </tr>
                   </thead>
                    <tbody>

                        <tr ng-repeat="bill in $ctrl.bills" style="font-size:0.8em;">
                          <td  class="col-xs-1"> {{$index+1}}</td>
                          <td nclass="col-xs-1"><a ng-href="home#!/subjectBilling/{{bill.refNumber}}" ng-bind="bill.refNumber"></a></td>
                          <td ng-bind="bill.totalTime+'H'" class="col-xs-3"></td>
                          <td ng-bind="bill.paymentAmount" class="col-xs-1" ng-class="{'zf-red': (exam.isMarkRegistered!==1)}"></td>
                          <td ng-bind="$ctrl.formatDate(bill.date.date) | date:'dd/MM/yyyy'" class="col-xs-2"></td>
                          <td ng-bind="bill.status===1?'Payé':'En cours...'"></td>
                        </tr>

                    </tbody>

                    </table>
               
                </div>
                
                <div class="row" ng-show = "$ctrl.showbillDetails">

                    <table class="table" style="font-size:0.8em; background-color: #dfe4ea; color: #0c2461;" >
                    <thead>

                        <tr class="bg-primary">
                            <th class=" align-middle" >N° Facture</th>
                            <th class=" align-middle">Date</th>
                            <th class=" align-middle">statut</th>
                            
                        </tr>
                   </thead>
                    <tbody>

                        <tr  style="font-size:0.8em;">
                          
                          <td nclass="col-xs-1" ng-bind="$ctrl.bill.refNumber"></td>
                          <td ng-bind="$ctrl.formatDate($ctrl.bill.date.date) | date:'dd/MM/yyyy'" class="col-xs-2"></td>
                          <td ng-bind="$ctrl.bill.status===1?'Payé':'En cours...'"></td>
                        </tr>

                    </tbody>

                    </table>
               
                </div>                
            </div>           
        </div>

        <div layout-gt-sm='row'>
            <div class="col-md-6 pull-left">
               <!-- <button class="btn btn-inverse" ng-click="$ctrl.clotureCalculNotes($ctrl.selectedUe.ue_class_id)" ng-disabled="examForm.$invalid||$ctrl.selectedUe.mark_calculation_status===1"><i class="fa fa-lock" ></i>&nbsp;Clôture</button>&nbsp;&nbsp; -->

            </div>
            <div class="col-md-6 text-right">
                <button class="btn btn-danger" ng-click="$ctrl.generateBill($ctrl.selectedTeacher,$ctrl.selectedUe)" ng-hide = "$ctrl.showbillDetails" ><i class="fa fa-refresh" ></i>&nbsp;Générer la facture</button>&nbsp;&nbsp;&nbsp;
                <button class="btn btn-danger" ng-click="$ctrl.deliberation()" ><i class="fa fa-save" ></i>&nbsp;Valider le paiement</button>
            </div>
        </div>
      

    </form>
    </md-content>
<!----------------------------------------------------------------------------------------------->


<p></p>
             <!--tabs widget-->
              <div class="row" > 
                    <ul class="nav nav-tabs">
                        <li class="active">
                            <a href="">Liste des cours réalisés</a>
                        </li>
                    </ul>
                    <div id =" tab1">
                            <table class="table table-striped table-condensed">
                                <thead>
                                    <tr class="bg-primary">
                                        <th>Num</th>
                                        <th>Description</th>
                                        <th>Date</th>
                                        <th>Heures</th>
                                        
                                        <th>PT</th>

                                    </tr>
                                </thead>
                                <tbody>
                                    <tr ng-repeat="bill in $ctrl.billDetails" >
                                      <td>{{$index+1}}</td>
                                      <td ng-bind="bill.description"></td>
                                      <td ng-bind="$ctrl.formatDate(bill.date.date) | date:'dd/MM/yyyy'"></td>
                                      <td ng-bind='bill.totalTime+"H"'></td>
                                      
                                      <td ng-bind='bill.paymentAmount' ></td>
                                    </tr>
                                    <tr><td colspan="3" style="text-align: right">Total</td><td>{{$ctrl.totalHrsBilled}}H</td><td>{{$ctrl.totalHrsBilled*$ctrl.paymentRate}}</td></tr> 
                                    <tr><td colspan="3" style="text-align: right">Volume horaire prévu</td><td>{{$ctrl.totalHrsAffected}}H</td><td>{{$ctrl.totalHrsAffected*$ctrl.paymentRate}}</td></tr> 
                                    <tr><td colspan="3" style="text-align: right">Cumul volume horaire entérieur réalisé</td><td>{{$ctrl.totalHrsPreviouslyBilled}}H</td><td>{{$ctrl.totalHrsPreviouslyBilled*$ctrl.paymentRate}}</td></tr>
                                        
                                       
                                    <tr><td colspan="3" style="text-align: right">Volume horaire facturé</td><td>{{$ctrl.totalHrsCurrentlyBilled}}H </td><td>{{$ctrl.totalHrsCurrentlyBilled*$ctrl.paymentRate}}</td></tr>    
                                    <tr><td colspan="3" style="text-align: right">heures bonus</td><td>{{$ctrl.overtime}}H</td><td>0</td></tr> 
                                    <tr><td colspan="4" style="text-align: right">Retenue sur vacation 25%</td><td>{{$ctrl.vacationDeduction}}</td></tr> 
                                    <tr><td colspan="4" style="text-align: right">IR 5.5%</td><td>{{$ctrl.totalHrsCurrentlyBilled*$ctrl.paymentRate*0.055}}</td></tr>  
                                    <tr><td colspan="4" style="text-align: right">NAP</td><td>{{($ctrl.totalHrsCurrentlyBilled*$ctrl.paymentRate)-($ctrl.totalHrsCurrentlyBilled*$ctrl.paymentRate*0.055)-$ctrl.vacationDeduction}}</td></tr> 

                                </tbody>
                            </table>
                    </div>
                    <div id="tab2"></div>
                 </div>
                <!--End tab-->
                
              
                
            </div>  
        </div>

</div>