
<link rel="stylesheet" type="text/css" href="css/datatables.bootstrap.css">
<link rel="stylesheel" type="text/css" href="css/buttons.datables.min.css">
<style>
/*md-dialog{
max-width: 900px;

}*/
.md-dialog-container {

    z-index: 1000;

}

</style>

  

</style>
<div class="row">
                <div class="col-lg-12">
                    <h4 class="page-header">Liste des Enseignants</h4>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row" ng-init="init()">
                <div class="col-lg-12">
                    <!-- Panneau des boutton -->
                    <div class="panel panel-default small">
                        <div class="panel-heading" style="margin-bottom: 15px;">

                            <button type="button" ng-click="redirect(-1)" class="btn btn-danger" id='newacadyr'>Créer</button>
                        </div>
                        
                  <!--class="table table-striped table-bordered table-hover table-condensed datatable"-->
                  <table id="tblfilieres" datatable="ng" dt-options="dtOptions" dt-column-defs="dtColumnDefs1"  class="table table-striped  table-hover table-condensed datatable">
                                
                                <thead>
                                    <tr>
                                        <th  > #</th>
                                        <th  > Nom  et  Prénoms</th>
                                        <th >Téléphone</th>
                                        <th >email</th>
                                        <th >type</th>
                                        <th ></th>
                                        <th ></th>
                                    </tr>
                                </thead>
                                <tbody>
    
                                    <tr ng-repeat="teach in teachers" style="cursor: pointer" ng-dblclick="redirect(teach.id)">
                                            <td >{{$index+1}}</td>
                                          <td ng-bind="teach.name"></td>
                                          <td ng-bind="teach.phoneNumber"></td>
                                          <td ng-bind="teach.email"></td>
                                          <td ng-bind="teach.type"></td>
                                          <td ng-bind='teach.status?"":"x"' ng-class="{'zf-green fa fa-check': fil.status,'zf-red': !fil.status }"></td>
                                          
                                          
                                          <td>
                                              <div class="btn-group">

                                              <button  type="button" ng-click="deleteTeacher(teach)" class="btn btn-danger  btn-xs" ><i class="fa fa-trash-o"></i></button></td>
                                              </div>
                                              
                                         </tr>

                                </tbody>
                            </table>

                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>

