<div layout="column" class="wrapper" ng-cloak>
    <md-toolbar md-scroll-shrink ng-if="true"  class="md-shadow-bottom-z-2" layout-padding>
        <div style="padding: 0">
            <h3 class="md-title">
                Liste des enseignants
            </h3>
        </div>
    </md-toolbar>

    <md-content layout="column">
        <div>
            <a href="#!new-teacher" class="md-button md-raised md-primary">Creer un enseignant</a>
        </div>
        <div class="loading-container" ng-if="!hasSucceededLoadingTeachers()">
            <div class="error-block" ng-if="hasFailedLoadingTeachers()">
                <img class="error-icon" src="assets/images/warning_752755.png" alt=""/>
                <span class="error-message md-warn">Une erreur s'est produite lors du chargement des donnees</span>
                <md-button class="md-raised md-warn" ng-click="loadTeachers()">Reessayer</md-button>
            </div>
            <div class="loader-block" ng-if="isLoadingTeachers()">
                <md-progress-circular md-mode="indeterminate"></md-progress-circular>
            </div>
        </div>
        <div layout="row" id="container" ng-if="hasSucceededLoadingTeachers()">
            <div class="panel " flex="30"  flex-gt-sm>
                <div class="panel-body">
                    <table class="table table-bordered bordered table-striped table-condensed datatable" style="font-size:0.8em; background-color: #dfe4ea; color: #0c2461;" ui-jq="dataTable" ui-options="dataTableOpt">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>Noms & Prenoms</th>
                            <th>Grade</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr ng-repeat="teacher in teachers" class="clickable teacher-item xx-small"
                            ng-style="{'background-color': teacher.id === selectedTeacherId ? 'lightblue' : 'initial'}"
                            ng-click="onSelectTeacher(teacher.id)">
                            <td>{{$index+1}}</td>
                            <td>{{teacher.name}}</td>
                            <td>{{teacher.grade.name}}</td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="" flex="70" id="teacher_details_container">
                <div id="teacher_details_placeholder" ng-if="!selectedTeacherId">
                    <img src="assets/images/pointer_178432.png" alt=""/>
                    <span>Selectionnez un enseignant pour avoir ses informations</span>
                </div>
                <div class="loading-container" ng-if="selectedTeacherId && !hasSucceededLoadingCurrentTeacher()">
                    <div class="error-block" ng-if="hasFailedLoadingCurrentTeacher()">
                        <img class="error-icon" src="assets/images/warning_752755.png" alt=""/>
                        <span class="error-message md-warn">Une erreur s'est produite lors du chargement des donnees</span>
                        <md-button class="md-raised md-warn" ng-click="loadCurrentTeacher()">Reessayer</md-button>
                    </div>
                    <div class="loader-block" ng-if="isLoadingCurrentTeacher()">
                        <md-progress-circular md-mode="indeterminate" class="md-accent md-hue-1" md-diameter="30"></md-progress-circular>
                    </div>
                </div>
                <div id="teacher_details" ng-if="hasSucceededLoadingCurrentTeacher()" class="panel">
                    <div class="panel-body gap-1" layout="column">
                        <div layout="row" class="gap-1">
                            <div class="flex-gt-sm gap-0-5" flex="50" layout="column">
                                <table class="table table-bordered bordered table-striped table-condensed" style="font-size:0.8em;  color: #0c2461;">
                                    <tr><td>Noms & Prenoms</td><td>{{currentTeacher.name}}</td></tr>
                                    <tr><td>Date de naissance</td><td>{{currentTeacher.birthDate.date | date}}</td></tr>
                                    <tr><td>Lieu de naissance</td><td>{{currentTeacher.birthplace}}</td></tr>
                                    <tr><td>Nationalite</td><td>{{currentTeacher.country.name.fr}}</td></tr>
                                    <tr><td>Etat civil</td><td>{{currentTeacher.maritalSStatus === 'single' ? 'Celibataire' : 'Marie(e)'}}</td></tr>
                                    <tr><td>Telephone</td><td>{{currentTeacher.phone}}</td></tr>
                                    <tr><td>Email</td><td>{{currentTeacher.email}}</td></tr>
                                    <tr><td>Diplome le plus eleve</td><td>{{currentTeacher.highest_degree.name}}</td></tr>
                                    <tr><td>Specialite</td><td>{{currentTeacher.speciality.name}}</td></tr>
                                    <tr><td>Grade</td><td>{{currentTeacher.grade.name}}</td></tr>
                                    <tr><td>Employeur Actuel</td><td>{{currentTeacher.actual_employer}}</td></tr>
                                    <tr><td>Etablissement sollicité</td><td>{{currentTeacher.requested_establishement.name}}</td></tr>
                                </table>

                                <div>
                                    <a href="{{'#!edit/'+selectedTeacherId}}" class="md-button md-raised md-primary md-hue-4 no-margin-left">
                                        <img src="assets/images/edit_4414703.png" alt="" width="16px" height="16px"/>
                                        Editer
                                    </a>
                                    <md-button class="md-raised md-accent md-hue-2" ng-click="openAffectTeachingUnitDialog()">
                                        <img src="assets/images/plus_3839101.png" alt="" width="16px" height="16px"/>
                                        Affecter une UE
                                    </md-button>
                                    <md-button class="md-raised md-warn md-hue-1 no-margin-left">
                                        <img src="assets/images/report_2912773.png" alt="" width="16px" height="16px"/>
                                        Generer la convention
                                    </md-button>
                                </div>
                            </div>
                            <div class="flex-gt-sm gap-1" id="teacher_documents" layout="column">
                                <div ng-class="!!currentTeacher.identityDocumentFile ? 'document-item' : 'document-item disabled'">
                                    <img class="document-icon" src="assets/images/id_783886.png" alt=""/>
                                    <span class="document-name single-line-ellipsis">{{currentTeacher.identityDocumentFile ? (currentTeacher.identity_document_type === 'passport' ? 'Passeport' : 'CNI') : 'Document d\'identite'}}</span>
                                    <a target="_blank" download
                                       href="{{currentTeacher.identityDocumentFile.url}}"
                                       class="document-download-button clickable">
                                        <img src="assets/images/download_9502265.png" alt=""/>
                                    </a>
                                </div>
                                <div ng-class="!!currentTeacher.coverLetterFile ? 'document-item' : 'document-item disabled'">
                                    <img class="document-icon" src="assets/images/letter_208027.png" alt=""/>
                                    <span class="document-name single-line-ellipsis">Lettre de motivation</span>
                                    <a target="_blank" download
                                       href="{{currentTeacher.coverLetterFile.url}}"
                                       class="document-download-button clickable">
                                        <img src="assets/images/download_9502265.png" alt=""/>
                                    </a>
                                </div>
                                <div ng-class="!!currentTeacher.resumeFile ? 'document-item' : 'document-item disabled'">
                                    <img class="document-icon" src="assets/images/resume_942799.png" alt=""/>
                                    <span class="document-name single-line-ellipsis">Curiculum Vitea</span>
                                    <a target="_blank" download
                                       href="{{currentTeacher.resumeFile.url}}"
                                       class="document-download-button clickable">
                                        <img src="assets/images/download_9502265.png" alt=""/>
                                    </a>
                                </div>
                                <div ng-class="!!currentTeacher.highestDegreeFile ? 'document-item' : 'document-item disabled'">
                                    <img class="document-icon" src="assets/images/certificate_2912761.png" alt=""/>
                                    <span class="document-name single-line-ellipsis">Diplome le plus eleve</span>
                                    <a target="_blank" download
                                       href="{{currentTeacher.highestDegreeFile.url}}"
                                       class="document-download-button clickable">
                                        <img src="assets/images/download_9502265.png" alt=""/>
                                    </a>
                                </div>
                                <div ng-class="!!currentTeacher.teacherRankFile ? 'document-item' : 'document-item disabled'">
                                    <img class="document-icon" src="assets/images/top_7061138.png" alt=""/>
                                    <span class="document-name single-line-ellipsis">Justificatif grade ens.</span>
                                    <a target="_blank" download href="{{currentTeacher.teacherRankFile.url}}"
                                       class="document-download-button clickable">
                                        <img src="assets/images/download_9502265.png" alt=""/>
                                    </a>
                                </div>
                                <div ng-class="!!currentTeacher.experienceReviewFile ? 'document-item' : 'document-item disabled'">
                                    <img class="document-icon" src="assets/images/review_3080641.png" alt=""/>
                                    <span class="document-name single-line-ellipsis">Bilan de l'experience</span>
                                    <a target="_blank" download="nene.pdf"
                                       href="{{currentTeacher.experienceReviewFile.url}}"
                                       type="download" class="document-download-button clickable">
                                        <img src="assets/images/download_9502265.png" alt=""/>
                                    </a>
                                </div>
                                <div ng-class="!!currentTeacher.nominationActFile ? 'document-item' : 'document-item disabled'">
                                    <img class="document-icon" src="assets/images/development_2191261.png" alt=""/>
                                    <span class="document-name single-line-ellipsis">Acte de nomination</span>
                                    <a target="_blank" download
                                       href="{{currentTeacher.nominationActFile.url}}"
                                       class="document-download-button clickable">
                                        <img src="assets/images/download_9502265.png" alt=""/>
                                    </a>
                                </div>
                            </div>
                        </div>
                        <br/>
                        <div layout="row" class="gap-1">
                            <div flex-gt-sm flex="50">
                                <table class="table table-bordered bordered table-striped table-condensed datatable" style="font-size:0.8em; background-color: #dfe4ea; color: #0c2461;" ui-jq="dataTable" ui-options="dataTableOpt">
                                    <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>UE</th>
                                        <th>Sem</th>
                                        <th>Classe</th>
                                        <th>Volume</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <tr ng-repeat="teachingUnit in currentTeacher.teaching_units" class="clickable teacher-item"
                                        ng-style="{'background-color': teachingUnit.id === selectedTeachingUnitId ? 'lightblue' : 'initial'}"
                                        ng-click="onSelectTeachingUnit(teachingUnit.id)">
                                        <td>{{$index+1}}</td>
                                        <td>{{teachingUnit.codeUe}}</td>
                                        <td>{{teachingUnit.semester}}</td>
                                        <td>{{teachingUnit.classe}}</td>
                                        <td>{{teachingUnit.totalHrs}}H</td>
                                    </tr>
                                    <tr style="text-align:center;font-weight : bold; color: #fff; background-color:#708090;"><td  colspan="4">Total Volume Horaire</td><td align="left">{{currentTeacher.teaching_units|sumByKey:'totalHrs'}}H</td></tr>
                                    </tbody>
                                </table>
                            </div>
                            <div flex-gt-sm flex="50" id="teaching_unit_details_container">
                                <div id="teaching_unit_details_placeholder" ng-if="!selectedTeachingUnitId">
                                    <img src="assets/images/pointer_178432.png" alt=""/>
                                    <span>Selectionnez une UE pour avoir ses informations</span>
                                </div>

                                <div class="loading-container" ng-if="selectedTeachingUnitId && !hasSucceededLoadingCurrentProgressionStats()">
                                    <div class="error-block" ng-if="hasFailedLoadingCurrentProgressionStats()">
                                        <img class="error-icon" src="assets/images/warning_752755.png" alt=""/>
                                        <span class="error-message md-warn">Une erreur s'est produite lors du chargement des donnees</span>
                                        <md-button class="md-raised md-warn" ng-click="loadCurrentProgressionStats()">Reessayer</md-button>
                                    </div>
                                    <div class="loader-block" ng-if="isLoadingCurrentProgressionStats()">
                                        <md-progress-circular md-mode="indeterminate" class="md-accent md-hue-1" md-diameter="30"></md-progress-circular>
                                    </div>
                                </div>
                                <div id="teaching_unit_details" ng-if="selectedTeachingUnitId && hasSucceededLoadingCurrentProgressionStats()">
                                    <table class="table table-bordered" style="font-size:0.8em; background-color: #dfe4ea; color: #0c2461;">
                                        <tr>
                                            <th colspan="6" scope="row" class="text-align-center uppercase">Cours magistraux</th>
                                        </tr>
                                        <tr>
                                            <th colspan="2">CM</th>
                                            <th colspan="2">TD</th>
                                            <th colspan="2">TP</th>
                                            <th rowspan="2" colspan="4" scope="col">Progression</th>

                                        </tr>                                        
                                        <tr>
                                            <th scope="col">Prév</th>
                                            <th scope="col">Réal</th>
                                            <th scope="col">Prév</th>
                                            <th scope="col">Réal</th>
                                            <th scope="col">Prév</th>
                                            <th scope="col">Réal</th>                                            
                                            
                                        </tr>
                                        <tr>
                                            <td>{{currentProgressionStats.cm.total}}H</td>
                                            <td>{{currentProgressionStats.cm.progress}}H</td>
                                            <td>{{currentProgressionStats.td.total}}H</td>
                                            <td>{{currentProgressionStats.td.progress}}H</td> 
                                            <td>{{currentProgressionStats.tp.total}}H</td>
                                            <td>{{currentProgressionStats.tp.progress}}H</td>                                            
                                            <td colspan="4">
                                                <div class="teaching-unit-progression">
                                                    <div class="teaching-unit-progression-bar" ng-style="{'width': getRoundedPercentage(currentProgressionStats.percentage)+'%'}"></div>
                                                </div>
                                                <span class="teaching-unit-progression-value">{{getRoundedPercentage(currentProgressionStats.percentage)}}%</span>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="progression-divider" colspan="8"></td>
                                        </tr>

                                    </table>
                                    <div class="text-align-center">
                                        <md-button style="width: -webkit-fill-available"
                                                   ng-click="openProgressionsTimelineDialog($event)"
                                                   class="md-raised md-accent md-hue-3 no-margin-left no-margin-right">
                                            Afficher les details
                                        </md-button>
                                        <md-button style="width: -webkit-fill-available"
                                                   ng-click="openNewProgressionDialog($event)"
                                                   class="md-raised md-primary md-hue-3 no-margin-left no-margin-right">
                                            Ajouter une progession
                                        </md-button>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </md-content>
</div>