
            <div class="col-lg-12 row" style="margin-top:50px;">
                    <h1 class="page-header">Bienvenue</h1>
            </div>

            <!-- /.row -->
            <div class="row">
                <div >
                    <form method="POST" action="">
     <br />
                    <div class="panel panel-primary">
                      <div class="panel-heading">Vérification des informations de paiement</div>
                      <div class="panel-body">
                          <p>
                              Les inscriptions administrative et académique à l'Institut Supérieure Agenla Academy sont conditionnées par le paiement des frais d'inscrption qui s'élèvent à la sommes de : <span class="text-danger">115000FCFA</span>.
                              Par ailleurs, vous devez vous rassurer que vous avez soldé la totalité des frais de scolarité de l'année passée.<br/>
                          Pour poursuivre avec le processus, rassurez vous que vous êtes en règle et cliquez sur suivant.
                          </p>
                          
                          <?php if($this->debtError):?>
                          
                          <div class='bg-danger'>
                              <div class="alert alert-danger">
                                  <i class='fa fa-warning'></i> Erreur: Vous n'êtes pas à jour du paiement de vos droits universitaires. Vous devez obligatoirement solder la  dette de l'année académique précédente qui s'élève à: <span class="bg-primary"> <?=$this->debt?>FCFA</span>.
                              </div>
                          </div>
                          <div class="alert alert-warning"><i class='fa fa-stop'></i> Après chaque paiement, vous devez patienter au moins  48H pour qu'il soit pris en compte dans notre base de donnée.</div>
                          <br /> <br />
                          <?php endif;?>
                          
                          <?php if($this->paymentError):?>
                          
                          <div class='bg-danger'>
                              <div class="alert alert-danger">
                              <i class='fa fa-warning'></i> Erreur: Frais d'inscription non encore réglés.
                              </div>
                          </div>
                          <div class="alert alert-warning"><i class='fa fa-stop'></i> Après chaque paiement, vous devez patienter au moins  48H pour qu'il soit pris en compte dans notre base de donnée.</div>
                          <br /> <br />
                          <?php endif;?>   
                          
                          <input type="hidden" name='' value='<?php$this->amountPaid;?>'>
                          <button type="submit" class="btn btn-danger btn-xl pull-right"> Suivant ></button>
                      </div>
                    </div>
                    </form>
                </div>
                
            </div>



        
