

 <p>
 <div class="jumbotron" style="margin-top: 55px;">
    
   

        
<div class='row'>
    <div class="col-md-8" >
        <!--<h1 style='color: green;'> Agenla Academy</h1>-->
        <h1 style='color: green;'> Agenla Academy</h1>
        <h2 style='color: grey;'> Plateforme web de gestion académique</h2>
        <div class="row">
            <div class="col-md-6">
            <ol class="faq">
                <li>Gestion académique <a href="nvdossier">Cliquer ici</a></li>
                    <li>Gestion des notes</li>
                    <li>Suivi des paiements de frais de scolarité</li>
                    <li>Planification</li>
            </li>
            </ol>
            <a class="btn btn-success btn-lg" href='help'>Plus de details ici</a>
            </div>
            <div class="col-md-6" style="color: #707aaa;">
               <br /> 
              En cas de problème bien vouloir nous contacter à l'adresse suivante:<br />
              Tel:  <br />
              Email: 
            </div>
        </div>
    </div>
    <div class="col-md-4">
    </p>
    <form class="" method="POST" action="">
            <h4 class="form-signin-heading">Connectez vous ici</h2>
            <?php if ( $isLoginError): ?>
            <div class="alert alert-warning" role="alert">
                Login ou mot de passe incorrect
                <!--<a href="">Forgot password?</a> -->
            </div>
            <?php endif; ?>
            
       
          <div class="form-group">
            <?= $this->formElement($form->get('email')->setAttributes([
                'class'=>'form-control', 
                'placeholder'=>'Votre adresse email',
                'required' => true,
                'autofocus' => true
                ])
                ->setLabelAttributes([
                    'class' => 'sr-only'
                ])); ?>
           
          </div>
          <div class="form-group">
            <?= $this->formElement($form->get('password')->setAttributes([
                'class'=>'form-control', 
                'placeholder'=>'Mot de passe',
                'required' => true,
                ])
                ->setLabelAttributes([
                    'class' => 'sr-only'
                ])); ?>
         
            <?= $this->formLabel($form->get('remember_me')); ?>
            <?= $this->formElement($form->get('remember_me')); ?>
      
            <?= $this->formElement($form->get('redirect_url')); ?>
           
            <?php //$this->formElement($form->get('csrf')) ?>
           <!-- <label>Numéro du Dossier :</label>
            <input type="text" name='num-dossier' class="form-control"/>
            <input type="hidden" name='redirectUrl' class="form-control"/> -->
           <?= $this->formElement($form->get('csrf')) ?>
            <button type="submit" name="login-btn" id='login-btn' class="btn btn-primary btn-lg btn-block">Suivant</button>
          </di>
           
        </div>
    </form>
    
    </div>
</div>
    </div>
