
<link rel="stylesheet" type="text/css" href="css/datatables.bootstrap.css">
<link rel="stylesheel" type="text/css" href="css/buttons.datables.min.css">
<style>
  /*.table th{
  background-color:#337ab7;
 // color:white;
  text-align:left;
  vertical-align:center;
}*/
  

</style>
<div class="row" ng-init="$ctrl.init() ">
                <div class="col-lg-12">
                    <h4 class="page-header">Détail des paiements</h4>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-12">
                    <!-- Panneau des boutton -->
                    <div class="panel panel-default small">
                        <div class="panel-heading" style="margin-bottom: 15px;">

                            <a href="#!/newmoratorium" class="btn btn-danger" id='newacadyr'>Créer</a>
                           
                            
                        </div>
                        
                  <!--class="table table-striped table-bordered table-hover table-condensed datatable"-->
                            <table  datatable="ng" dt-options="$ctrl.dtOptions"  dt-column-defs="$ctrl.dtColumnDefs"  class="row-border hover table table-striped table-hover table-condensed datatable" style="table-layout: fixed">
                                <thead>
                                    <tr class="highlight">
                                        <th style="width: 15%">Matricule</th>
                                        <th>Nom</th>
                                        <th>Prénom</th>
                                        <th style="width: 10%">Classe</th>
                                        <th>Dotation</th>
                                        <th>Montant Payé</th>
                                        <th>Solde</th>
                                        <th>Sstatus</th>
                                   </tr>
                                </thead>
                                <tbody>
                                    <tr ng-repeat="pmt in $ctrl.moratoriums " ng-dblclick="$ctrl.redirect(pmt.id)"  style="cursor: pointer;" >
                                      <td ng-bind="pmt.matricule"></td>
                                      <td ng-bind="pmt.nom"></td>
                                      <td ng-bind="pmt.prenom"></td>
                                      <td ng-bind="pmt.class"></td>
                                      <td ng-bind="pmt.feesDotation | currency :'':0"></td>
                                      <td ng-bind="pmt.feesPaid | currency :'':0"></td>
                                      <td ng-bind="pmt.feesBalance | currency :'':0"></td>
                                      <td ng-bind="pmt.moratoriumAutorization"></td>
                                    </tr>
                                </tbody>
                            </table>

                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>

            