
<script src="js/app/student/admission.component.js"></script>
<link rel="stylesheet" type="text/css" href="css/datatables.bootstrap.css">
<link rel="stylesheel" type="text/css" href="css/buttons.datables.min.css">
<style>
  /*.table th{
  background-color:#337ab7;
 // color:white;
  text-align:left;
  vertical-align:center;
}*/
  

</style>
<div ng  ng-controller="studentCtrl as $ctrl" ng-cloak >
    <div  class="row" >
                <div class="col-lg-12">
                    <h4 class="page-header">Liste des étudiants admis par concous ou sur titre</h4>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-12">
                    <!-- Panneau des boutton -->
                    <div class="panel panel-default small">
                        <div class="panel-heading" style="margin-bottom: 15px;">

                            <a href="" class="btn btn-danger" ng-disabled="true"  id='newacadyr'>Créer</a>
                            
                            
                        </div>
                        
                  <!--class="table table-striped table-bordered table-hover table-condensed datatable"-->
                            <table   datatable="ng" dt-options="$ctrl.dtOptions"  dt-column-defs="$ctrl.dtColumnDefs"  class="row-border hover table table-striped table-hover table-condensed datatable" style="table-layout: fixed">
                                <thead>
                                    <tr >
                                        <th>Num</th>
                                        <th >Nom</th>
                                        <th>Num Tel</th>
                                        <th >Classe</th>
                                        <th>Montant</th>
                                        <th>Date</th>
                                        <th >ID admission</th>
                                        <th >Type</th>
                                        <th>Statut</th>
                                   </tr>
                                </thead>
                                <tbody>
                                    <tr ng-repeat="std in $ctrl.students " ng-dblclick="$ctrl.loadStd(std)"  style="cursor: pointer;">
                                     <td ng-bind="std.num"></td>
                                      <td ng-bind='std.nom+" "+std.prenom'></td>
                                      
                                      <td ng-bind="std.phoneNumber"></td>
                                      <td ng-bind="std.classe"></td>
                                      <td ng-bind="std.feesPaid"></td>
                                      <td ng-bind="$ctrl.formatDate(std.dateAdmission) | date:'dd/MM/yyyy'"></td>
                                      <td ng-bind="std.numDossier"></td>
                                      <td ng-bind="std.entranceType"></td>
                                      <td ng-bind="(std.status===0)?'Attente confirmation':(std.status===1)?'Attente inscription':'Terminer'" ng-class="{'zf-bg-warn': std.status===1,'zf-bg-green': std.status===2, 'zf-bg-red': std.status===0 }"></td>
                                      
                                    </tr>
                                </tbody>
                            </table>

                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>
</div>            

            