
<link rel="stylesheet" type="text/css" href="css/datatables.bootstrap.css">
<link rel="stylesheel" type="text/css" href="css/buttons.datables.min.css">
<style>
  /*.table th{
  background-color:#337ab7;
 // color:white;
  text-align:left;
  vertical-align:center;
}*/
  

</style>
<div class="row" ng-init="$ctrl.init() ">
                <div class="col-lg-12">
                    <h4 class="page-header">Gestion des créances</h4>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-12">
                    <!-- Panneau des boutton -->
                    <div class="panel panel-default small">
                        <div class="panel-heading" style="margin-bottom: 15px;">

                            
                            <div ng-show="<?=($this->access('global.system.admin', ['user'=>$this->currentuser($this->identity())])==1)||($this->access('manage.payment', null)==1)?true:false?>">
                            <button  ng-click="$ctrl.importBalance()" class="btn btn-primary" id='newacadyr'><i class="fa fa-file"></i>&nbsp;Importer la balance</button>
                            <button  ng-click="$ctrl.loadStdDotation()" class="btn btn-primary" id='newacadyr'><i class="fa fa-file"></i>&nbsp;Dotation</button>
                            
                            <button  ng-click="$ctrl.addStdToSubject()" class="btn btn-default " id='newacadyr'><i class="fa fa-money"></i>&nbsp;Mise à Jour des règlements</button>
                            <button  ng-click="$ctrl.loadStdPayments()" class="btn btn-default " id='newacadyr'><i class="fa fa-money"></i>&nbsp;Importer les règlements</button>
                            </div>
                            
                        </div>
                        
                  <!--class="table table-striped table-bordered table-hover table-condensed datatable"-->
                            <table  datatable="ng" dt-options="$ctrl.dtOptions"  dt-column-defs="$ctrl.dtColumnDefs"  class="row-border hover table table-striped table-hover table-condensed datatable" style="table-layout: fixed">
                                <thead>
                                    <tr class="highlight">
                                        <th style="width: 8%" >Mat</th>
                                        <th>Nom & Prénom</th>
                                        
                                        <th style="width: 8%">Classe</th>
                                        <th style="width: 10%">Dette</th>
                                        <th style="width: 10%">Dotation</th>
                                        <th style="width: 10%">Montant Payé</th>
                                        <th style="width: 10%">Solde</th>
                                   </tr>
                                </thead>
                                <tbody>
                                    <tr ng-repeat="pmt in $ctrl.payments " ng-dblclick="$ctrl.redirect(pmt.id)"  style="cursor: pointer;" >
                                      <td ng-bind="pmt.matricule"></td>
                                      <td ng-bind="pmt.nom"></td>
                                      
                                      <td ng-bind="pmt.class"></td>
                                      <td ng-bind="pmt.feesDebt"></td>
                                      <td ng-bind="pmt.feesDotation | currency :'':0"></td>
                                      <td ng-bind="pmt.feesPaid | currency :'':0"></td>
                                      <td ng-bind="pmt.feesBalance | currency :'':0"></td>
                                    </tr>
                                </tbody>
                            </table>

                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>

            