
<style> 
.md-datepicker-calendar-pane{
z-index: 120000}

.md-select-menu-container {z-index: 120000;}



</style>
    
    <form  ng-submit=""  name="classForm" novalidate>
        <div class="well" style="margin-left: -30px; margin-right: -30px;" ng-init="$ctrl.init()">

            <div class="row">
                <div class='col-lg-2'>
                    <button  type="button" class="btn btn-danger" ng-click="$ctrl.updateClasse()" ng-show="$ctrl.isUpdate" ng-disabled="classForm.$invalid">Modifier</button>
                    <button  type="button" ng-click="$ctrl.addClasse()" class="btn btn-danger" ng-show="!$ctrl.isUpdate" ng-disabled="classForm.$invalid">Enrégistrer</button>
                    <span> <a href="#!/payments">[Retour]</a></span>
                </div>
                <div class="col-lg-4"></div>
                <div class="col-lg-2">
                    
                    <button  type="button" ng-show="$ctrl.isUpdate" ng-click="$ctrl.deleteDegree()" ng-disabled="classForm.$invalid" class="btn btn-default">Supprimer</button>
                    
                    
                </div>
            </div>
        </div>
        <div class="form-view-main">
            <div class="form-view">



  
<div  layout="column" ng-cloak class="md-inline-form" >


    <md-content layout-padding >

    <div layout='row'>
        <div class="col-md-6"><strong>Matricule:</strong>&nbsp;&nbsp;&nbsp; &nbsp;    {{$ctrl.student.matricule}}</div> <div class="col-md-6"></div>
    </div>
    <div layout='row'>
        <div class="col-md-6"><strong>Nom:</strong>&nbsp;&nbsp;&nbsp;&nbsp;     {{$ctrl.student.nom+" "+$ctrl.student.prenom}}</div><div class="col-md-6" ></div>
    </div>
    <div layout='row'>
        <div class="col-md-6"><strong>Faculté:</strong>&nbsp;&nbsp;&nbsp;&nbsp;{{$ctrl.student.facultyName}}</div><div class="col-md-6" ><strong>Filière:</strong>&nbsp;&nbsp;&nbsp;&nbsp;{{$ctrl.student.filiereName}}</div>
    </div>
    <div layout='row'>
        <div class="col-md-6"><strong>Parcourt académique:</strong>&nbsp;&nbsp;&nbsp;&nbsp; {{$ctrl.student.degreeName}}</div><div class="col-md-6" ><strong>Classe:</strong> {{$ctrl.student.class}}</div>
    </div>
        <div layout='row' class="bg-info">
            <div class="col-md-6"></div><div class="col-md-6"  ><strong>Dette année antérieure: <span class="text-danger">{{$ctrl.student.feesDebt}}</span></strong></div>
    </div>
   
    
        
        
    <div layout='row'>

        

    </div>      
          
    <div layout-gt-sm="row">

        
        </div>



        </form>
  </md-content>

</div>
<p>&nbsp;</p>
              <!--tabs widget-->
                <div class="row" style='padding: 25px;' >
                    <ul class="nav nav-tabs">
                      <li class="active"><a href="#">Historique des paiements</a></li>

                    </ul>

                                        <table class="table table-striped table-condensed">
                                            <thead>
                                                <tr class="bg-primary">
                                                    <th >Num</th>
                                                    <th >ID de paiement</th>
                                                    <th>Date de la transaction</th>
                                                    <th>Montant</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr ng-repeat="pmt in $ctrl.payments" >
                                                  <td ng-bind="pmt.num"></td>
                                                  <td ng-bind="pmt.mobilePaymentId"></td>
                                                  <td ng-bind="$ctrl.formatDate(pmt.dateTransaction) | date:'dd/MM/yyyy H:m:s'"></td>
                                                  <td ng-bind="pmt.amount | currency:'':0" style="text-align: right"></td>
                                                </tr>
                                                <tr class="bg-info"><td colspan=3 style="vertical-align: middle; text-align: center;"><strong>Total</strong></td><td style="text-align: right"><strong>{{$ctrl.totalPayments | currency:'':0}}</strong></td></tr>
                                            </tbody>
                                        </table>
                    
                 </div>
                <!--End tab-->
                
            </div>  
        </div>

