<div class="jumbotron">
    <h1 style='font-size: 3.5em'>Inscription au concours d'entrée à l'<a href="http://udm.aed-cm.org" style="text-decoration: none;"> <span class="zf-green">UdM</span></a></h1>
    <div class="zf-green"><h4>Prochaine session: le 27 Septembre 2017</h4></div>
    <p>

        
<div class='row'>
    <div class="col-md-8" >
        <h2 style='color: grey;'>Soumettez votre dossier en trois étapes</h2>
        <div class="row">
            <div class="col-md-6">
            <ol class="faq">
                <li>Création d'un numéro de dossier <a href="nvdossier">Cliquer ici</a></li>
                    <li>Paiement et validation des frais de concours</li>
                    <li>Soumission du dossier de candidature</li>
            </li>
            </ol>
            <a class="btn btn-success btn-lg" href='help'>Plus de details ici</a>
            </div>
            <div class="col-md-6" style="color: #707aaa;">
               <br /> 
              En cas de problème bien vouloir nous contacter à l'adresse suivante:<br />
              Tel: 691144891 <br />
              Email: si@udm.aed-cm.org
            </div>
        </div>
    </div>
    <div class="col-md-4">
    </p>
    <form class="" method="POST" action="">
            <h4 class="form-signin-heading">Connectez vous ici</h2>
            <?php if ( $isLoginError): ?>
            <div class="alert alert-warning" role="alert">
                Numéro de dossier incorrect 
                <!--<a href="">Forgot password?</a> -->
            </div>
            <?php endif; ?>
            
       
          <div class="form-group">
            <?= $this->formElement($form->get('email')->setAttributes([
                'class'=>'form-control', 
                'placeholder'=>'Votre adresse email',
                'required' => true,
                'autofocus' => true
                ])
                ->setLabelAttributes([
                    'class' => 'sr-only'
                ])); ?>
          </div>
          <div class="form-group">
            <?= $this->formElement($form->get('password')->setAttributes([
                'class'=>'form-control', 
                'placeholder'=>'Password',
                'required' => true,
                ])
                ->setLabelAttributes([
                    'class' => 'sr-only'
                ])); ?>
            <?= $this->formLabel($form->get('remember_me')); ?>
            <?= $this->formElement($form->get('remember_me')); ?>
      
            <?= $this->formElement($form->get('redirect_url')); ?>
           
            <?php //$this->formElement($form->get('csrf')) ?>
           <!-- <label>Numéro du Dossier :</label>
            <input type="text" name='num-dossier' class="form-control"/>
            <input type="hidden" name='redirectUrl' class="form-control"/> -->
            <button type="submit" name="login-btn" id='login-btn' class="btn btn-primary btn-lg btn-block">Suivant</button>
          </di>
           
        </div>
    </form>
    <p><span ><a class="" href="<?php //$this->url("admission")."/nvdossier"?>" > Cliquer ici</a> pour  créer un dossier de candidature</span></p>      
    </div>
</div>
    </div>
