<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class AcademicYear extends \Application\Entity\AcademicYear implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Application\\Entity\\AcademicYear' . "\0" . 'id', '' . "\0" . 'Application\\Entity\\AcademicYear' . "\0" . 'code', '' . "\0" . 'Application\\Entity\\AcademicYear' . "\0" . 'name', '' . "\0" . 'Application\\Entity\\AcademicYear' . "\0" . 'startingDate', '' . "\0" . 'Application\\Entity\\AcademicYear' . "\0" . 'endingDate', '' . "\0" . 'Application\\Entity\\AcademicYear' . "\0" . 'isDefault', '' . "\0" . 'Application\\Entity\\AcademicYear' . "\0" . 'status', '' . "\0" . 'Application\\Entity\\AcademicYear' . "\0" . 'totalSmsSent', '' . "\0" . 'Application\\Entity\\AcademicYear' . "\0" . 'admissionStartingDate', '' . "\0" . 'Application\\Entity\\AcademicYear' . "\0" . 'admissionEndingDate', '' . "\0" . 'Application\\Entity\\AcademicYear' . "\0" . 'adminRegistrationStartingDate', '' . "\0" . 'Application\\Entity\\AcademicYear' . "\0" . 'adminRegistrationEndingDate', '' . "\0" . 'Application\\Entity\\AcademicYear' . "\0" . 'prefix', '' . "\0" . 'Application\\Entity\\AcademicYear' . "\0" . 'entranceFees', '' . "\0" . 'Application\\Entity\\AcademicYear' . "\0" . 'registrationFees', '' . "\0" . 'Application\\Entity\\AcademicYear' . "\0" . 'previousYear'];
        }

        return ['__isInitialized__', '' . "\0" . 'Application\\Entity\\AcademicYear' . "\0" . 'id', '' . "\0" . 'Application\\Entity\\AcademicYear' . "\0" . 'code', '' . "\0" . 'Application\\Entity\\AcademicYear' . "\0" . 'name', '' . "\0" . 'Application\\Entity\\AcademicYear' . "\0" . 'startingDate', '' . "\0" . 'Application\\Entity\\AcademicYear' . "\0" . 'endingDate', '' . "\0" . 'Application\\Entity\\AcademicYear' . "\0" . 'isDefault', '' . "\0" . 'Application\\Entity\\AcademicYear' . "\0" . 'status', '' . "\0" . 'Application\\Entity\\AcademicYear' . "\0" . 'totalSmsSent', '' . "\0" . 'Application\\Entity\\AcademicYear' . "\0" . 'admissionStartingDate', '' . "\0" . 'Application\\Entity\\AcademicYear' . "\0" . 'admissionEndingDate', '' . "\0" . 'Application\\Entity\\AcademicYear' . "\0" . 'adminRegistrationStartingDate', '' . "\0" . 'Application\\Entity\\AcademicYear' . "\0" . 'adminRegistrationEndingDate', '' . "\0" . 'Application\\Entity\\AcademicYear' . "\0" . 'prefix', '' . "\0" . 'Application\\Entity\\AcademicYear' . "\0" . 'entranceFees', '' . "\0" . 'Application\\Entity\\AcademicYear' . "\0" . 'registrationFees', '' . "\0" . 'Application\\Entity\\AcademicYear' . "\0" . 'previousYear'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (AcademicYear $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCode($code)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCode', [$code]);

        return parent::setCode($code);
    }

    /**
     * {@inheritDoc}
     */
    public function getCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCode', []);

        return parent::getCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setStartingDate($startingDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStartingDate', [$startingDate]);

        return parent::setStartingDate($startingDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getStartingDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStartingDate', []);

        return parent::getStartingDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setEndingDate($endingDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEndingDate', [$endingDate]);

        return parent::setEndingDate($endingDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getEndingDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEndingDate', []);

        return parent::getEndingDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsDefault($isDefault)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsDefault', [$isDefault]);

        return parent::setIsDefault($isDefault);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsDefault()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsDefault', []);

        return parent::getIsDefault();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotalSmsSent($totalSmsSent)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotalSmsSent', [$totalSmsSent]);

        return parent::setTotalSmsSent($totalSmsSent);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalSmsSent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalSmsSent', []);

        return parent::getTotalSmsSent();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdmissionStartingDate($admissionStartingDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdmissionStartingDate', [$admissionStartingDate]);

        return parent::setAdmissionStartingDate($admissionStartingDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdmissionStartingDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdmissionStartingDate', []);

        return parent::getAdmissionStartingDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdmissionEndingDate($admissionEndingDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdmissionEndingDate', [$admissionEndingDate]);

        return parent::setAdmissionEndingDate($admissionEndingDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdmissionEndingDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdmissionEndingDate', []);

        return parent::getAdmissionEndingDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdminRegistrationStartingDate($adminRegistrationStartingDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdminRegistrationStartingDate', [$adminRegistrationStartingDate]);

        return parent::setAdminRegistrationStartingDate($adminRegistrationStartingDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdminRegistrationStartingDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdminRegistrationStartingDate', []);

        return parent::getAdminRegistrationStartingDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdminRegistrationEndingDate($adminRegistrationEndingDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdminRegistrationEndingDate', [$adminRegistrationEndingDate]);

        return parent::setAdminRegistrationEndingDate($adminRegistrationEndingDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdminRegistrationEndingDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdminRegistrationEndingDate', []);

        return parent::getAdminRegistrationEndingDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrefix($prefix)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrefix', [$prefix]);

        return parent::setPrefix($prefix);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrefix()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrefix', []);

        return parent::getPrefix();
    }

    /**
     * {@inheritDoc}
     */
    public function setFeesPaid($entranceFees)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFeesPaid', [$entranceFees]);

        return parent::setFeesPaid($entranceFees);
    }

    /**
     * {@inheritDoc}
     */
    public function getEntranceFees()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEntranceFees', []);

        return parent::getEntranceFees();
    }

    /**
     * {@inheritDoc}
     */
    public function setRegistrationFees($registrationFees)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRegistrationFees', [$registrationFees]);

        return parent::setRegistrationFees($registrationFees);
    }

    /**
     * {@inheritDoc}
     */
    public function getRegistrationFees()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRegistrationFees', []);

        return parent::getRegistrationFees();
    }

    /**
     * {@inheritDoc}
     */
    public function setPreviousYear(\Application\Entity\AcademicYear $previousYear = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPreviousYear', [$previousYear]);

        return parent::setPreviousYear($previousYear);
    }

    /**
     * {@inheritDoc}
     */
    public function getPreviousYear()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPreviousYear', []);

        return parent::getPreviousYear();
    }

}
