<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ClassOfStudyHasSemester extends \Application\Entity\ClassOfStudyHasSemester implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Application\\Entity\\ClassOfStudyHasSemester' . "\0" . 'id', '' . "\0" . 'Application\\Entity\\ClassOfStudyHasSemester' . "\0" . 'credits', '' . "\0" . 'Application\\Entity\\ClassOfStudyHasSemester' . "\0" . 'hoursVolume', '' . "\0" . 'Application\\Entity\\ClassOfStudyHasSemester' . "\0" . 'subjectCredits', '' . "\0" . 'Application\\Entity\\ClassOfStudyHasSemester' . "\0" . 'subjectHours', '' . "\0" . 'Application\\Entity\\ClassOfStudyHasSemester' . "\0" . 'cmHours', '' . "\0" . 'Application\\Entity\\ClassOfStudyHasSemester' . "\0" . 'tpHours', '' . "\0" . 'Application\\Entity\\ClassOfStudyHasSemester' . "\0" . 'tdHours', '' . "\0" . 'Application\\Entity\\ClassOfStudyHasSemester' . "\0" . 'subjectCmHours', '' . "\0" . 'Application\\Entity\\ClassOfStudyHasSemester' . "\0" . 'subjectTdHours', '' . "\0" . 'Application\\Entity\\ClassOfStudyHasSemester' . "\0" . 'subjectTpHours', '' . "\0" . 'Application\\Entity\\ClassOfStudyHasSemester' . "\0" . 'status', '' . "\0" . 'Application\\Entity\\ClassOfStudyHasSemester' . "\0" . 'isPreviousYearSubject', '' . "\0" . 'Application\\Entity\\ClassOfStudyHasSemester' . "\0" . 'markCalculationStatus', '' . "\0" . 'Application\\Entity\\ClassOfStudyHasSemester' . "\0" . 'classOfStudy', '' . "\0" . 'Application\\Entity\\ClassOfStudyHasSemester' . "\0" . 'semester', '' . "\0" . 'Application\\Entity\\ClassOfStudyHasSemester' . "\0" . 'subject', '' . "\0" . 'Application\\Entity\\ClassOfStudyHasSemester' . "\0" . 'teachingUnit'];
        }

        return ['__isInitialized__', '' . "\0" . 'Application\\Entity\\ClassOfStudyHasSemester' . "\0" . 'id', '' . "\0" . 'Application\\Entity\\ClassOfStudyHasSemester' . "\0" . 'credits', '' . "\0" . 'Application\\Entity\\ClassOfStudyHasSemester' . "\0" . 'hoursVolume', '' . "\0" . 'Application\\Entity\\ClassOfStudyHasSemester' . "\0" . 'subjectCredits', '' . "\0" . 'Application\\Entity\\ClassOfStudyHasSemester' . "\0" . 'subjectHours', '' . "\0" . 'Application\\Entity\\ClassOfStudyHasSemester' . "\0" . 'cmHours', '' . "\0" . 'Application\\Entity\\ClassOfStudyHasSemester' . "\0" . 'tpHours', '' . "\0" . 'Application\\Entity\\ClassOfStudyHasSemester' . "\0" . 'tdHours', '' . "\0" . 'Application\\Entity\\ClassOfStudyHasSemester' . "\0" . 'subjectCmHours', '' . "\0" . 'Application\\Entity\\ClassOfStudyHasSemester' . "\0" . 'subjectTdHours', '' . "\0" . 'Application\\Entity\\ClassOfStudyHasSemester' . "\0" . 'subjectTpHours', '' . "\0" . 'Application\\Entity\\ClassOfStudyHasSemester' . "\0" . 'status', '' . "\0" . 'Application\\Entity\\ClassOfStudyHasSemester' . "\0" . 'isPreviousYearSubject', '' . "\0" . 'Application\\Entity\\ClassOfStudyHasSemester' . "\0" . 'markCalculationStatus', '' . "\0" . 'Application\\Entity\\ClassOfStudyHasSemester' . "\0" . 'classOfStudy', '' . "\0" . 'Application\\Entity\\ClassOfStudyHasSemester' . "\0" . 'semester', '' . "\0" . 'Application\\Entity\\ClassOfStudyHasSemester' . "\0" . 'subject', '' . "\0" . 'Application\\Entity\\ClassOfStudyHasSemester' . "\0" . 'teachingUnit'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ClassOfStudyHasSemester $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCredits($credits)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCredits', [$credits]);

        return parent::setCredits($credits);
    }

    /**
     * {@inheritDoc}
     */
    public function getCredits()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCredits', []);

        return parent::getCredits();
    }

    /**
     * {@inheritDoc}
     */
    public function setHoursVolume($hoursVolume)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHoursVolume', [$hoursVolume]);

        return parent::setHoursVolume($hoursVolume);
    }

    /**
     * {@inheritDoc}
     */
    public function getHoursVolume()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHoursVolume', []);

        return parent::getHoursVolume();
    }

    /**
     * {@inheritDoc}
     */
    public function setSubjectCredits($subjectCredits)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSubjectCredits', [$subjectCredits]);

        return parent::setSubjectCredits($subjectCredits);
    }

    /**
     * {@inheritDoc}
     */
    public function getSubjectCredits()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubjectCredits', []);

        return parent::getSubjectCredits();
    }

    /**
     * {@inheritDoc}
     */
    public function setSubjectHours($subjectHours)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSubjectHours', [$subjectHours]);

        return parent::setSubjectHours($subjectHours);
    }

    /**
     * {@inheritDoc}
     */
    public function getSubjectHours()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubjectHours', []);

        return parent::getSubjectHours();
    }

    /**
     * {@inheritDoc}
     */
    public function setCmHours($cmHours)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCmHours', [$cmHours]);

        return parent::setCmHours($cmHours);
    }

    /**
     * {@inheritDoc}
     */
    public function getCmHours()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCmHours', []);

        return parent::getCmHours();
    }

    /**
     * {@inheritDoc}
     */
    public function setTpHours($tpHours)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTpHours', [$tpHours]);

        return parent::setTpHours($tpHours);
    }

    /**
     * {@inheritDoc}
     */
    public function getTpHours()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTpHours', []);

        return parent::getTpHours();
    }

    /**
     * {@inheritDoc}
     */
    public function setTdHours($tdHours)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTdHours', [$tdHours]);

        return parent::setTdHours($tdHours);
    }

    /**
     * {@inheritDoc}
     */
    public function getTdHours()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTdHours', []);

        return parent::getTdHours();
    }

    /**
     * {@inheritDoc}
     */
    public function setSubjectCmHours($subjectCmHours)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSubjectCmHours', [$subjectCmHours]);

        return parent::setSubjectCmHours($subjectCmHours);
    }

    /**
     * {@inheritDoc}
     */
    public function getSubjectCmHours()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubjectCmHours', []);

        return parent::getSubjectCmHours();
    }

    /**
     * {@inheritDoc}
     */
    public function setSubjectTdHours($subjectTdHours)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSubjectTdHours', [$subjectTdHours]);

        return parent::setSubjectTdHours($subjectTdHours);
    }

    /**
     * {@inheritDoc}
     */
    public function getSubjectTdHours()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubjectTdHours', []);

        return parent::getSubjectTdHours();
    }

    /**
     * {@inheritDoc}
     */
    public function setSubjectTpHours($subjectTpHours)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSubjectTpHours', [$subjectTpHours]);

        return parent::setSubjectTpHours($subjectTpHours);
    }

    /**
     * {@inheritDoc}
     */
    public function getSubjectTpHours()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubjectTpHours', []);

        return parent::getSubjectTpHours();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsPreviousYearSubject($isPreviousYearSubject)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsPreviousYearSubject', [$isPreviousYearSubject]);

        return parent::setIsPreviousYearSubject($isPreviousYearSubject);
    }

    /**
     * {@inheritDoc}
     */
    public function getisPreviousYearSubject()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getisPreviousYearSubject', []);

        return parent::getisPreviousYearSubject();
    }

    /**
     * {@inheritDoc}
     */
    public function setMarkCalculationStatus($markCalculationStatus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMarkCalculationStatus', [$markCalculationStatus]);

        return parent::setMarkCalculationStatus($markCalculationStatus);
    }

    /**
     * {@inheritDoc}
     */
    public function getMarkCalculationStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMarkCalculationStatus', []);

        return parent::getMarkCalculationStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setClassOfStudy(\Application\Entity\ClassOfStudy $classOfStudy = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClassOfStudy', [$classOfStudy]);

        return parent::setClassOfStudy($classOfStudy);
    }

    /**
     * {@inheritDoc}
     */
    public function getClassOfStudy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClassOfStudy', []);

        return parent::getClassOfStudy();
    }

    /**
     * {@inheritDoc}
     */
    public function setSemester(\Application\Entity\Semester $semester = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSemester', [$semester]);

        return parent::setSemester($semester);
    }

    /**
     * {@inheritDoc}
     */
    public function getSemester()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSemester', []);

        return parent::getSemester();
    }

    /**
     * {@inheritDoc}
     */
    public function setSubject(\Application\Entity\Subject $subject = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSubject', [$subject]);

        return parent::setSubject($subject);
    }

    /**
     * {@inheritDoc}
     */
    public function getSubject()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubject', []);

        return parent::getSubject();
    }

    /**
     * {@inheritDoc}
     */
    public function setTeachingUnit(\Application\Entity\TeachingUnit $teachingUnit = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTeachingUnit', [$teachingUnit]);

        return parent::setTeachingUnit($teachingUnit);
    }

    /**
     * {@inheritDoc}
     */
    public function getTeachingUnit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTeachingUnit', []);

        return parent::getTeachingUnit();
    }

}
