<link rel="stylesheet" href='js/datatables-plugins/dataTables.bootstrap.css'>


<style> 
.md-datepicker-calendar-pane{
z-index: 120000}

.md-select-menu-container {z-index: 120000;}



</style>
    
<form  ng-submit=""  name="examForm" ng-cloak novalidate>
        <div class="well" style="margin-left: -30px; margin-right: -30px;" ng-init="$ctrl.init()">

            <div class="row">
                <div class='col-md-4'>
  
                    <span> <a href="#!/examlist">Retour</a></span>
                </div>
                <div class="col-md-2"></div>

                
                <div class="pul-middle">
                                <div class="btn-group">
                                    <button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown">
                                        Autres options
                                        <span class="caret"></span>
                                    </button>
                                    <ul class="dropdown-menu pull-right" role="menu">
                                        <!--<li><a href="" ng-click="$ctrl.printMps()"><span>Imprimer recap</span></a>
                                        </li>-->
                                        <li><a href="" ng-click="$ctrl.printDetailedMps()"><span>Imprimer pv recap </span></a>
                                        </li>
                                        <li ng-show='$ctrl.selectedClasse.studyLevel===7' ng-click="$ctrl.print7thYrMps()"><a href=""><span>Imprimer pv recap 7ième année</span></a>
                                        
                                        </li> 
                                    </ul>
                                </div>
                </div>
                
                
                
            </div>
        </div>

<div class="form-view-main">
    <div class="form-view">


    <md-content layout-padding >

   
    <div layout-gt-sm='row' >
        <div layout-gt-sm='column' class="col-md-6" >
            <md-input-container class="md-block" flex-gt-sm>
                <label>Classe:</label>
                <md-autocomplete  md-search-text="$ctrl.searchClasse" 
                                 md-selected-item="$ctrl.selectedClasse"  
                                 md-items="item in $ctrl.query($ctrl.searchClasse)" 
                                 md-item-text="item.code" 
                                 md-min-length="0"
                                 placeholder="Faites de la classe" 
                                 md-selected-item-change="$ctrl.selectedItemChange(item)"
                                 md-input-name="classe"
                                 md-no-asterisk
                                 required>
                    <md-item-template>
                      <span md-highlight-text="$ctrl.searchClasse" md-highlight-flags="^i">{{item.code}}</span>

                    </md-item-template>
                    <md-not-found>
                      Aucun élément correspondant à "{{$ctrl.searchClasse}}" n'a été trouvé.

                    </md-not-found>
                </md-autocomplete>
                    <div ng-messages="examForm.classe.$error">
                        <div ng-message="required">Ce champ est obligatoire</div>
                    </div> 
           </md-input-container >
        </div>
            <div layout-gt-sm='column' class="col-md-6" style="padding-top: 10px" >
                <!-- Display examlis on a table -->
                <div ng-show="$ctrl.selectedSem.markCalculationStatus===1" class="" style="font-size:0.8em; color: #0c2461;">

                   <button class="btn btn-lg-12 btn-inverse pull-right"  ng-click="$ctrl.printTranscripts($ctrl.selectedClasse.code,$ctrl.selectedSem.id)"><i class="fa fa-download" ></i>&nbsp;Télécharger les relevés de notes</button>                        

                </div>
  
            </div>
        </div>
        <div layout-gt-sm='row' >
            <div layout-gt-sm='column'  class="col-md-6" >
                <md-input-container>
                    <label>Semestre</label>
                    <md-select name="semester" ng-model="$ctrl.selectedSem" ng-model-options="{trackBy: '$value.id'}" md-on-open="$ctrl.asignedSemToClasse($ctrl.selectedClasse.code); "  ng-change="$ctrl.activateUeSelect()"
                                md-no-asterisk required >

                        <md-option ng-disabled="true"><em>---Choix du Semestre---</em></md-option>
                      <md-option ng-repeat="sem in $ctrl.semesters" ng-value="sem"  >
                        {{sem.name}}
                      </md-option>

                    </md-select>
                    <div class="errors" ng-messages="examForm.semester.$error">
                      <div ng-message="required">Champ obligatoire</div>
                    </div>
                </md-input-container>
            </div>
            <div layout-gt-sm='column'  class="col-md-6">
                <!--<md-input-container>
                    <label>Options d'impression</label>
                    <md-select name="printingOption" ng-model="$ctrl.printingOption" md-no-asterisk >

                        <md-option ng-disabled="true"><em>---Option d'impression---</em></md-option>
                        <md-option ng-value="0"> Ordre alphabétique</md-option>
                        <md-option ng-value="1"> Ordre de mérite</md-option>

                    </md-select>
                    <div class="errors" ng-messages="examForm.printingOption.$error">
                      <div ng-message="required">Champ obligatoire</div>
                    </div>
                </md-input-container> -->               
            </div>
           
        </div>
        <div layout-gt-sm="row">
            <div layout-gt-sm='column'  class="col-md-6" >
                <md-input-container>
                <md-checkbox ng-model="$ctrl.isSpecialDelibAllow"                
                    aria-label="Actif?"
                    ng-true-value="1"
                    ng-false-value="0" class="md-primary"> 
                    Autoriser une délibération spéciale.
                </md-checkbox>
                </md-input-container>

                <md-input-container ng-if="$ctrl.isSpecialDelibAllow===1" class="animate-if">
                    <label>Nombre de matières</label>
                    <md-select name="nbreUeDelibSpecial" ng-model="$ctrl.nbreUeDelibSpecial" md-no-asterisk >

                        <md-option ng-disabled="true"><em>---Matière à délibérer---</em></md-option>
                        <md-option ng-value="1">1 Unité d'enseignement</md-option>
                        <md-option ng-value="2">2 Unités d'enseignement</md-option>
                        <md-option ng-value="3">3 Unités d'enseignement</md-option>
                        <md-option ng-value="4">4 Unités d'enseignement</md-option>
                        <md-option ng-value="6">6 Unités d'enseignement</md-option>
                        <md-option ng-value="8">8 Unités d'enseignement</md-option>
                        <md-option ng-value="16">16 Unités d'enseignement</md-option>

                    </md-select>
                    <div class="errors" ng-messages="examForm.nbreUeDelibSpecial.$error">
                      <div ng-message="required">Champ obligatoire</div>
                    </div>
                </md-input-container> 
            </div>            
           
        </div>    
   
    <div layout-gt-sm='row' >
        <div class="col-md-6 pull-left"><button class="btn btn-inverse" ng-disabled="$ctrl.selectedSem.markCalculationStatus===1" ng-click="$ctrl.clotureCalculNotes($ctrl.selectedClasse.code,$ctrl.selectedSem.id)"><i class="fa fa-lock" ></i>&nbsp;Clôture</button></div>
        <div class="col-md-4 pullt-right"><button class="btn btn-inverse" ng-disabled="!$ctrl.selectedSem.sendSmsStatus===1" ng-show="$ctrl.selectedSem.markCalculationStatus===0 && $ctrl.selectedSem.ranking%2===0" ng-click="$ctrl.sendResultBySMS($ctrl.selectedClasse.code,$ctrl.selectedSem.id)"><i class="fa fa-send-o" ></i>&nbsp;Envoyer les notes par SMS</button></div>
        <div class="col-md-2 text-right"><button class="btn btn-danger" ng-disabled="$ctrl.selectedSem.markCalculationStatus===1" ng-click="$ctrl.loadStd($ctrl.selectedClasse.code,$ctrl.selectedSem.id)"><i class="fa fa-refresh" ></i>&nbsp;Calcul MPS</button></div>

        
    </div>
         
</md-content>


<p>&nbsp;</p>
              <!--tabs widget-->
                <div class="row" >
                    <ul class="nav nav-tabs">
                      <li class="active"><a href="#"> Recapitulatif des notes du {{$ctrl.selectedSem.code}}</a></li>

                    </ul>

                                        <table class="table table-striped table-condensed">
                                            <thead>
                                                <tr class="bg-primary">
                                                  <th style="vertical-align: middle; align: center" ng-repeat="(key, val) in $ctrl.registeredStd[0]">{{ key }}</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr ng-repeat="row in $ctrl.registeredStd" >
                                                    <td style="vertical-align: middle; align: center;" ng-repeat="column in row">
                                                      {{ column }}
                                                    </td>
                                                </tr>
                                            </tbody>
                                        </table>
                 </div>
                <!--End tab-->
                
            </div>  
        </div>

  </form>