
<link rel="stylesheet" type="text/css" href="css/datatables.bootstrap.css">
<link rel="stylesheel" type="text/css" href="css/buttons.datables.min.css">


<style>
  /*.table th{
  background-color:#337ab7;
 // color:white;
  text-align:left;
  vertical-align:center;
}*/
  

</style>

<div class="row" ng-init="$ctrl.init() ">
                <div class="col-lg-12">
                    <h4 class="page-header">Liste des conditions de délibération</h4>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-12">
                    <!-- Panneau des boutton -->
                    <div class="panel panel-default">
                        <div class="panel-heading" style="margin-bottom: 15px;">

                            <a href="#!/newDelibCondition" class="btn btn-danger" id='newacadyr'>Créer</a>
            
                            
                        </div>
                        
                  <!--class="table table-striped table-bordered table-hover table-condensed datatable"-->
                            <table  datatable="ng"   class="row-bordtable table-striped table-hover table-condensed er hover table table-striped table-hover table-condensed datatable" style="table-layout: fixed">
                                <thead>
                                    <tr class="highlight">
                                        <th style="width: 15%;"></th>
                                        <th>Intitulé</th>

                                   </tr>
                                </thead>
                                <tbody>
                                    <tr ng-repeat="condition in $ctrl.conditions " ng-dblclick="$ctrl.redirect(condition.id)" style="cursor: pointer;" >
                                        <td ng-bind="condition.num" ></td>
                                        <td ng-bind="condition.label"></td>

                                     
                                    </tr>
                                </tbody>
                            </table>

                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
     
</div>
            