
<link rel="stylesheet" type="text/css" href="css/datatables.bootstrap.css">
<link rel="stylesheel" type="text/css" href="css/buttons.datables.min.css">
<style>
  /*.table th{
  background-color:#337ab7;
 // color:white;
  text-align:left;
  vertical-align:center;
}*/

  

</style>
<div class="row" ng-init="$ctrl.init() ">
                <div class="col-lg-12">
                    <h4 class="page-header">Liste des examens</h4>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-12">
                    <!-- Panneau des boutton -->
                    <div class="panel panel-default small">
                        <div class="panel-heading" style="margin-bottom: 15px;">

                            <a href="#!/newexam" class="btn btn-danger" id='newacadyr'>Créer</a>
                            <button  ng-click="$ctrl.loadData()" class="btn btn-inverse" id='newacadyr'><span class="fa fa-upload"></span>&nbsp;Importer</button>
                            
                        </div>
                        
                  <!--class="table table-striped table-bordered table-hover table-condensed datatable"-->
                            <table  datatable="ng" dt-options="$ctrl.dtOptions"  dt-column-defs="$ctrl.dtColumnDefs"  class="row-border hover table table-striped table-hover table-condensed datatable" style="table-layout: fixed">
                                <thead>
                                    <tr class="highlight">
                                        <th ></th>
                                        <th >Code</th>
                                        <th >Matière</th>
                                        <th>Type</th>
                                        <th>Classe</th>
                                        <th>Sem</th>
                                        <th style="width:15%">Date</th>
                                        <th>Statut</th>
                                   </tr>
                                </thead>
                                <tbody>
                                    <tr ng-repeat="exam in $ctrl.exams " ng-dblclick="$ctrl.redirect(exam.id)" style="cursor: pointer;" >
                                      <td ng-bind="exam.num"></td>
                                      <td ng-bind="exam.code"></td>
                                      <td ng-bind="exam.subject"></td>
                                      <td ng-bind="exam.type"></td>
                                      <td ng-bind="exam.classe"></td>
                                      <td ng-bind="exam.semester"></td>
                                      <td ng-bind="$ctrl.formatDate(exam.date) | date:'dd/MM/yyyy H:mm:ss'"></td>
                                      <td ng-bind="(exam.status===0)?'Evaluation annulée':(exam.status===1&&exam.isMarkRegistered!=1)?'Note en attente':(exam.isMarkRegistered===1&&exam.isMarkVlidated!=1)?'Note enrégistrée':(exam.isMarkValidated===1&&exam.isMarkConfirmed!=1)?'Note Validée':'Note confirmée' " ng-class="{ 'zf-bg-red': (exam.status===0),'zf-bg-warn': (exam.status===1&&exam.isMarkRegistered!=1),'zf-bg-green': (exam.isMarkRegistered===1&&exam.status!=0) }"></td>
                                    </tr>
                                </tbody>
                            </table>

                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>

            