<style> 
.md-datepicker-calendar-pane{
z-index: 120000}

.md-select-menu-container {z-index: 120000;}
</style>


<md-dialog  style="max-width: 60%;
            max-height: auto;
    width: 60%;
    height: auto;
    border-radius: 0;" aria-label="Délibération">

    <md-toolbar>
      <div class="md-toolbar-tools" ng-cloak>
        <h2>Délibération</h2>
        <span flex></span>
        <md-button class="md-icon-button" ng-click="cancel()">
          <md-icon md-svg-src="img/ic_close_24px.svg" aria-label="Close dialog"></md-icon>
        </md-button>
      </div>
    </md-toolbar>

      <div class="md-dialog-content" >
      <md-content layout-padding >
  
          <div layout-gt-sm='row' ng-init="ueID=<?=$this->ueID?>;semID=<?=$this->semID?>;classeID=<?=$this->classeID?>;subjectID=<?=$this->subjectID?>;">
                Vous êtes sur le point de démarrer la délibération de l'UE: <span style=" font-weight: bold;"><?=$this->ue?></span>
            </div>
                <br />
Les conditions de délibération suivantes seront appliquées:
<div class='row' style="background-color: #dfe4ea; color:#0c2461;">
    <?=$this->delibCondition?>
</div>

                
           
    

            
    <md-dialog-actions layout="row">
      <span flex></span>
      <md-button ng-click="cancel()"> Annuler</md-button>
      <md-button class="md-warn" ng-click="saveDelib(ueID,subjectID,semID,classeID)" >
          <span class="fa fa-check">  Appliquer </span>
      </md-button>

    </md-dialog-actions>
         
    </md-content>
      
      

  
</md-dialog>