<link rel="stylesheet" href='js/datatables-plugins/dataTables.bootstrap.css'>


<style> 
.md-datepicker-calendar-pane{
z-index: 120000}

.md-select-menu-container {z-index: 120000;}



</style>
    
<form  ng-submit=""  name="examForm" ng-cloak novalidate>
        <div class="well" style="margin-left: -30px; margin-right: -30px;" ng-init="$ctrl.init()">

            <div class="row">
                <div class='col-md-4'>
                    <button  type="button" ng-click="$ctrl.cancelExam()" class="btn btn-danger"  ng-show="$ctrl.isUpdate" ng-disabled="examForm.$invalid">Annuler l'examen</button>
                    <button  type="button" ng-click="$ctrl.newExam()" class="btn btn-danger" ng-show="!$ctrl.isUpdate" ng-disabled="examForm.$invalid">Enrégistrer</button>
                    <span> <a href="#!/examlist">Retour</a></span>
                </div>
                <div class="col-md-2"></div>

                
                <div class="pul-middle">
                                <div class="btn-group">
                                    <button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown">
                                        Autres options
                                        <span class="caret"></span>
                                    </button>
                                    <ul class="dropdown-menu pull-right" role="menu">
                                        <li><a href="" ng-click="$ctrl.printMps()"><span>Imprimer</span></a>
                                        </li>
                                      <!--  <li><a href=""><span>Imprimer étiquette</span></a>
                                        </li>
                                        <li><a href=""><span>Imprimer liste étudiants</span></a>
                                        </li> -->
                                    </ul>
                                </div>
                </div>
                
                
                
            </div>
        </div>

<div class="form-view-main">
    <div class="form-view">


    <md-content layout-padding >

   
    <div layout-gt-sm='row' >

        <div class = "col-xs-12">
            <div layout-gt-sm='row' >
                <md-input-container class="md-block" flex-gt-sm>
                    <label>Classe:</label>
                    <md-autocomplete  md-search-text="$ctrl.searchClasse" 
                                     md-selected-item="$ctrl.selectedClasse"  
                                     md-items="item in $ctrl.query($ctrl.searchClasse)" 
                                     md-item-text="item.code" 
                                     md-min-length="0"
                                     placeholder="Faites de la classe" 
                                     md-selected-item-change="$ctrl.selectedItemChange(item)"
                                     md-input-name="classe"
                                     md-no-asterisk
                                     required>
                        <md-item-template>
                          <span md-highlight-text="$ctrl.searchClasse" md-highlight-flags="^i">{{item.code}}</span>

                        </md-item-template>
                        <md-not-found>
                          Aucun élément correspondant à "{{$ctrl.searchClasse}}" n'a été trouvé.

                        </md-not-found>
                    </md-autocomplete>
                        <div ng-messages="examForm.classe.$error">
                            <div ng-message="required">Ce champ est obligatoire</div>
                        </div> 
                </md-input-container >
            </div>
            <div layout-gt-sm='column' style="padding-top: 10px" >
            <!--        <md-input-container>
                    <label>Semestre</label>
                    <md-select name="semester" ng-model="$ctrl.selectedSem" ng-model-options="{trackBy: '$value.id'}" md-on-open="$ctrl.asignedSemToClasse($ctrl.selectedClasse.code); " ng-change=""
                                md-no-asterisk required >
                        <md-option ng-disabled="true"><em>---Choix du Semestre---</em></md-option>
                      <md-option ng-repeat="sem in $ctrl.semesters" ng-value="sem"  >
                        {{sem.name}}
                      </md-option>
                    </md-select>
                    <div class="errors" ng-messages="examForm.semester.$error">
                      <div ng-message="required">Champ obligatoire</div>
                    </div>
                  </md-input-container>  -->
            </div> 
            <div layout-gt-sm='column' style="padding-top: 15px" >
                <md-input-container>

                </md-input-container> 
            </div>
        </div>
     
        <div class = "col-xs-12"  >
            <!-- Display examlis on a table -->
            <div>

            <table class="table table-fixed" style="font-size:0.8em; background-color: #dfe4ea; color: #0c2461;">
                <thead>

                    <tr class="bg-primary">
                        <th class="col-xs-1 align-middle" >#</th>
                        <th class="col-xs-3 align-middle" >Code </th>
                        <th class="col-xs-8 align-middle">Nom</th>

                    </tr>
               </thead>
                <tbody>

                    <tr ng-repeat="sub in $ctrl.backlogs" style="font-size:0.8em;"><a href=''>  
                      <td ng-bind="sub.num" class="col-xs-1"> </td>
                      <td  class="col-xs-3" ><a ng-href="home#!/newexam/{{sub.id}}" ng-bind="sub.code"></a></td>
                      <td ng-bind="sub.nom" class="col-xs-8"></td>
                   
                    </tr>

                </tbody>

                </table>
            </div>
        </div>           
    </div>
   
    <div layout-gt-sm='row' >
        <div class="col-md-12 text-right"><button class="btn btn-danger" ng-click="$ctrl.loadStdPath($ctrl.selectedClasse.id)"><i class="fa fa-refresh" ></i>&nbsp;Afficher parcourt</button></div>
        
    </div>
</md-content>


<p>&nbsp;</p>
              <!--tabs widget-->
                <div class="row" >
                    <ul class="nav nav-tabs">
                      <li class="active"><a href="#"> Détails sur le parcourt de l'étudiant</a></li>

                    </ul>

                                        <table datatable="ng" dt-options="$ctrl.dtOptions"  dt-column-defs="$ctrl.dtColumnDefs" class="table table-striped table-condensed">
                                            <thead>
                                                <tr class="bg-primary">
                                                  <th style="vertical-align: middle; align: center" ng-repeat="(key, val) in $ctrl.registeredStd[0]">{{ key }}</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr ng-repeat="row in $ctrl.registeredStd" >
                                                    <td style="vertical-align: middle; align: center;" ng-click="$ctrl.loadBackLogSubjet(row.Matricule.value)" ng-repeat="column in row">
                                                      {{ column.value }}
                                                    </td>

                                                </tr>
                                            </tbody>
                                        </table>
                 </div>
                <!--End tab-->
                
            </div>  
        </div>

  </form>