
<link rel="stylesheet" type="text/css" href="css/datatables.bootstrap.css">
<link rel="stylesheel" type="text/css" href="css/buttons.datables.min.css">
<style>
  /*.table th{
  background-color:#337ab7;
 // color:white;
  text-align:left;
  vertical-align:center;
}*/
  

</style>
<div class="row" ng-init="init()">
                <div class="col-lg-12">
                    <h4 class="page-header">Années académiques</h4>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-12">
                    <!-- Panneau des boutton -->
                    <div class="panel panel-default small">
                        <div class="panel-heading" style="margin-bottom: 15px;">

                            <a href="#!/acadyr" class="btn btn-danger" id='newacadyr'>Créer</a>
                            
                        </div>
                        <md-content layout-padding >
                         <md-radio-group ng-change="changeOnlineRegistrationDefault(onlineRegistrationStatus)"  ng-model="onlineRegistrationStatus" aria-labelledby="favoriteFruit">
                  <!--class="table table-striped table-bordered table-hover table-condensed datatable"-->
                            <table  datatable="ng" dt-options="dtOptions" dt-column-defs="dtColumnDefs" class="table table-striped table-bordered table-hover table-condensed datatable">
                                
                                <thead>
                                    <tr>
                                        <th>Code</th>
                                        <th>Identification</th>
                                        <th>Date de début</th>
                                        <th>Date de fin</th>
                                        <th>inscription en ligne</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                               
                                    <tr ng-repeat="acadyr in acadyrs" ng-dblclick="(acadyr.status==1)||redirect(acadyr.id)" style='cursor: pointer;' ng-style="{'background-color': acadyr.isDefault==1?'#5CB85C':'','color': acadyr.isDefault==1?'#f9f9f9':''}" >
                                          <td style="width:15%" ng-bind="acadyr.code"></td>
                                          <td style="width:54%" ng-bind="acadyr.name"></td>
                                          <td style="width:13%" ng-bind="formatDate(acadyr.startingDate.date) | date:'dd/MM/yyyy'"></td>
                                          <td style="width:11%" ng-bind="formatDate(acadyr.endingDate.date) | date:'dd/MM/yyyy'"></td>
                                          <td style="width:5%; align: center;" >
                                          
                                <md-radio-button    style="height:5px; margin-top: 5px; margin-left: 40px; padding: 0px; margin-bottom: 0px;"  ng-value="acadyr.id" class="md-primary" checked="acadyr.onlineRegistrationDefaultYear==1?true:false" >  </md-radio-button>
                                          </td>
                                          <td style="width:2%" ng-class="{'fa fa-unlock': acadyr.status=='0','fa fa-lock': acadyr.status=='1'}"></td>

                                              
                                    </tr>
                               

                                </tbody>
                            </table>
                   </md-radio-group>
</md-content>
                    </div>
                    <!-- /.panel -->
                </div>
                