
<style> 
.md-datepicker-calendar-pane{
z-index: 120000}

.md-select-menu-container {z-index: 120000;}



</style>
    
    <form  ng-submit=""  name="teachingUnitForm" novalidate>
        <div class="well" style="margin-left: -30px; margin-right: -30px;" ng-init="$ctrl.init()">

            <div class="row">
                <div class='col-lg-2'>
                    <button  type="button" class="btn btn-danger" ng-click="$ctrl.updateUe()" ng-show="$ctrl.isUpdate" ng-disabled="teachingUnitForm.$invalid">Modifier</button>
                    <button  type="button" ng-click="$ctrl.addUe()" class="btn btn-danger" ng-show="!$ctrl.isUpdate" ng-disabled="teachingUnitForm.$invalid">Enrégistrer</button>
                    <span> <a href="#!/assignedteachingunit">Retour</a></span>
                </div>
                <div class="col-lg-4"></div>
                <div class="col-lg-2">
                <div class="pul-middle" ng-show="$ctrl.isUpdate">
                                <div class="btn-group">
                                    <button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown">
                                        Autres options
                                        <span class="caret"></span>
                                    </button>
                                    <ul class="dropdown-menu pull-right" role="menu">
                                        <li><a href="" ng-click="$ctrl.deleteUe()" ng-disabled="teachingUnitForm.$invalid">Supprimer</a></li>
                                        <li><a href="" ng-click="$ctrl.duplicateUe()"><span>Dupliquer</span></a></li>
                                        <li><a href="" ng-click="$ctrl.activateUe()"><span>Activer</span></a></li>
                                        <li><a href="" ng-click="$ctrl.unactivateUe()"><span>Désactiver</span></a></li>
                                        
                                      <!--  <li><a href=""><span>Imprimer étiquette</span></a>
                                        </li>
                                        <li><a href=""><span>Imprimer liste étudiants</span></a>
                                        </li> -->
                                    </ul>
                                </div>
                </div>                      
                   
                    
                    
                </div>
            </div>
        </div>
        <div class="form-view-main">
            <div class="form-view">



  
<div   ng-cloak class="md-inline-form">


    <md-content layout-padding >

    <div layout-gt-sm='row' >
    <md-input-container class="md-block" flex-gt-sm flex='40'>
          <label>Classe:</label>
          <md-autocomplete  md-search-text="$ctrl.searchText" 
                           md-selected-item="$ctrl.selectedItem"  
                           md-items="item in $ctrl.query($ctrl.searchText)" 
                           md-item-text="item.code" 
                           md-min-length="0"
                           placeholder="Faites de la classe" 
                           md-selected-item-change="$ctrl.selectedItemChange(item)"
                           md-input-name="classe"
                           md-no-asterisk
                           required>
              <md-item-template>
                <span md-highlight-text="$ctrl.searchText" md-highlight-flags="^i">{{item.code}}</span>

              </md-item-template>
              <md-not-found>
                No states matching "{{$ctrl.searchText}}" were found.
                <a ng-click="">Create a new one!</a>
              </md-not-found>
        </md-autocomplete>
              <div ng-messages="teachingUnitForm.classe.$error">
                  <div ng-message="required">Ce champ est obligatoire</div>
              </div> 
    </md-input-container>
    <md-input-container class="md-block" flex-gt-sm flex='60'>
          <label>Enseignant:</label>
          <md-autocomplete md-search-text="$ctrl.searchText1" 
                           md-selected-item="$ctrl.selectedItem1"  
                           md-items="item1 in $ctrl.querySearch3()" 
                           md-item-text="item1.name" 
                           md-min-length="0"
                           placeholder="Enseignant de la classe" 
                           
                           md-input-name="lecturer"
                           md-no-asterisk
                           >
              <md-item-template>
                <span md-highlight-text="$ctrl.searchText" md-highlight-flags="^i">{{item1.name}}</span>

              </md-item-template>
              <md-not-found>
                No states matching "{{$ctrl.searchText}}" were found.
                <a ng-click="">Create a new one!</a>
              </md-not-found>
        </md-autocomplete>
              <div ng-messages="teachingUnitForm.classe.$error">
                  <div ng-message="required">Ce champ est obligatoire</div>
              </div> 
    </md-input-container>
    </div>
     
          
    <div layout-gt-sm="row">
        <md-input-container class="md-block" flex-gt-sm flex='60'>
          <label>Nom de l'UE:</label>
          <input name="name" ng-model="$ctrl.ue.name" md-no-asterisk required />
              <div ng-messages="teachingUnitForm.name.$error">
                  <div ng-message="required">le champ nom UE est obligatoire</div>

              </div>   
        </md-input-container>
        <md-input-container class="md-block" flex-gt-sm flex='20'>
                <label>Choix du smestre</label>
                <md-select name="semester" ng-model="$ctrl.ue.sem_id"  md-on-open="$ctrl.asignedSemToClasse($ctrl.selectedItem.code);" ng-required="true" md-no-asterisk>
                   <!--<md-option><em>None</em></md-option> -->
                   <md-option ng-repeat="sem in $ctrl.semesters" ng-value="sem.id" >
                     {{sem.name}}
                   </md-option>
                 </md-select>
              <div ng-messages="teachingUnitForm.semester.$error">
                  <div ng-message="required">le champ semestre  est obligatoire</div>
                  
              </div> 
        </md-input-container>
        <md-input-container class="md-block" flex-gt-sm flex='10'>
          <label>Code UE:</label>
          <input name="code" ng-model="$ctrl.ue.code" required md-no-asterisk  minlength='3'/>
              <div ng-messages="teachingUnitForm.code.$error">
                  <div ng-message="required">le champ code UE  est obligatoire</div>
                  <div ng-message="minlength">le code doit avoir au moins 3 caractères</div>
              </div> 
        </md-input-container>
        
        <md-input-container class="md-block" flex-gt-sm flex='10'>
          <label>Cédits:</label>
          <input name="credits" type="number"  ng-model="$ctrl.ue.credits" required md-no-asterisk />
              <div ng-messages="teachingUnitForm.credits.$error">
                  <div ng-message="required">le champ nombre de crédits  est obligatoire</div>
                  
              </div> 
        </md-input-container>
        <md-input-container class="md-block" flex-gt-sm flex='10'>
          <label>Horaire:</label>
          <input name="vol_horaire" type="number" ng-model="$ctrl.ue.hours_vol" required md-no-asterisk />
              <div ng-messages="teachingUnitForm.vol_horaire.$error">
                  <div ng-message="required">le champ volume horaire est obligatoire</div>
                  
              </div> 
        </md-input-container>
        
        </div>
        
        <fieldset><legend>Répartition du volume horaire</legend>
      <div layout-gt-sm='row'>      
     <md-input-container class="md-block" flex-gt-sm flex='10'>
        
          <label>CM</label>
          <input name="cm" type='number' ng-model="$ctrl.ue.cm_hrs" required md-no-asterisk  />
              <div ng-messages="teachingUnitForm.cm.$error">
                  <div ng-message="required">le champ code UE  est obligatoire</div>

              </div> 
        </md-input-container>
        
        <md-input-container class="md-block" flex-gt-sm flex='10'>
          <label>TD</label>
          <input name="td" type="number"  ng-model="$ctrl.ue.td_hrs" required md-no-asterisk />
              <div ng-messages="teachingUnitForm.td.$error">
                  <div ng-message="required">le champ nombre de crédits  est obligatoire</div>
                  
              </div> 
        </md-input-container>
        <md-input-container class="md-block" flex-gt-sm flex='10' >
          <label>TP</label>
          <input name="tp" type="number" ng-model="$ctrl.ue.tp_hrs" required md-no-asterisk />
              <div ng-messages="teachingUnitForm.vol_horaire.$error">
                  <div ng-message="required">le champ volume horaire est obligatoire</div>
                  
              </div> 
        </md-input-container>
         
        </div>
            <div class="error">
                <small ng-show="$ctrl.ue.cm_hrs+$ctrl.ue.tp_hrs+$ctrl.ue.td_hrs>$ctrl.ue.hours_vol" >bla bla bla</small>
            </div>
    </fieldset>
        <div layout-gt-sm="column">
                <md-checkbox ng-model="$ctrl.ue.isCompulsory"               
                    aria-label="Actif?"
                    ng-true-value="1"
                    ng-false-value="0"> 
                    Est une UE obligatoire?
                </md-checkbox>

                <md-checkbox ng-model="$ctrl.ue.isEndDegreeTraining"               
                    aria-label="Actif?"
                    ng-true-value="1"
                    ng-false-value="0"> 
                   Est une UE optionnelle?
                </md-checkbox>
          
                <md-checkbox ng-model="$ctrl.ue.isPreviousYearSubject"               
                    aria-label="Actif?"
                    ng-true-value="1"
                    ng-false-value="0"> 
                   Est une UE antérieur de rattrappage?
                </md-checkbox>            
        </div>

        </form>
  </md-content>

</div>
<p>&nbsp;</p>
              <!--tabs widget-->
                <div class="row" >
                    <ul class="nav nav-tabs">
                      <li class="active"><a href="#">Matières</a></li>

                    </ul>

                                        <table class="table table-striped">
                                            <thead>
                                                <tr>
                                                    <th rowspan="2">Matière</th>
                                                    <th rowspan="2" style="width:15%">Code</th>
                                                    <th rowspan="2" style="width:5%">classe</th>
                                                    
                                                    <th rowspan="2" style="width:5%"> poids</th>
                                                    <th style="width:10%" colspan="4">Vol horaire</th>

                                                    <th rowspan="2" style="width:20%">Enseignant</th>
                                                 
                                                    <!--<th style="width:10%"></th>-->
                                                </tr>
                                                <tr><td>Total</td><td>CM</td><td>TD</td><td>TP</td></tr>
                                            </thead>
                                            <tbody>
                                                <tr ng-repeat="sub in subjects" >
                                                  <td ng-bind="sub.subjectName"></td>
                                                  <td ng-bind="sub.subjectCode"></td>
                                                  <td ng-bind="sub.classCode"></td>
                                                  
                                                  <td ng-bind="sub.subjectWeight"></td>
                                                  <td ng-bind="sub.subjectHours"></td>
                                                  <td ng-bind="sub.subjectCmHours"></td>
                                                  <td ng-bind="sub.subjectTdHours"></td>
                                                  <td ng-bind="sub.subjectTpHours"></td>
                                                  <td>rr</td>
                                                  <td></td>
                                                  <td></td>
                                                  <td></td>
                                                  <td></td>
                                                  <td>
                                                      
                                                      <button type="button" ng-click="$ctrl.showSubject(sub)" class="btn btn-default btn"><i class="fa fa-edit"></i></button>
                                                      <button  type="button" ng-click="deleteSubject(sub)" class="btn btn-default btn" ><i class="fa fa-trash-o"></i></button></td></span>
                                                    
                                                  </td>
                                                </tr>
                                            </tbody>
                                        </table>
                        <a class="btn btn-primary" ng-click="$ctrl.addSubject()">Ajouter une matière</a>

                 </div>
                <!--End tab-->
                
            </div>  
        </div>

