
<link rel="stylesheet" type="text/css" href="css/datatables.bootstrap.css">
<link rel="stylesheel" type="text/css" href="css/buttons.datables.min.css">
<style>
  /*.table th{
  background-color:#337ab7;
 // color:white;
  text-align:left;
  vertical-align:center;
}*/
  

</style>
<div class="row" ng-init="$ctrl.init()">
                <div class="col-lg-12">
                    <h4 class="page-header">Liste des formations disponibles</h4>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-12">
                    <!-- Panneau des boutton -->
                    <div class="panel panel-default">
                        <div class="panel-heading" style="margin-bottom: 15px;">

                            <a href="#!/newdegree" class="btn btn-danger" id='newacadyr'>Créer</a>
                        </div>
                        
                  <!--class="table table-striped table-bordered table-hover table-condensed datatable"-->
                            <table  datatable="ng" dt-options="dtOptions" dt-column-defs="dtColumnDefs" class="table table-striped table-bordered table-hover table-condensed datatable">
                                
                                <thead>
                                    <tr>
                                        <th>Nom de la formation</th>
                                        <th style="width:20%">Code</th>
                                        <th style="width:10%">statut</th>
                                        
                                        <!--<th style="width:10%"></th>-->
                                    </tr>
                                </thead>
                                <tbody>
    
                                    <tr ng-repeat="degree in $ctrl.degrees" style="cursor: hand;cursor: pointer;" ng-dblclick="$ctrl.redirect(degree.id)">
                                        
                                      <td ng-bind="degree.name"></td>
                                      <td ng-bind="degree.code"></td>
                                       <td ng-bind='degree.status?"Actif":"Verouillé"'></td>
                              
                                   <!--   <td>
                                          <div class="btn-group">
                                          <a href="#!/updatedegree/{{degree.id}}" class="btn btn-default btn"><i class="fa fa-edit"></i></a>
                                          <button  type="button" ng-click="$ctrl.deleteDegree(degree);" class="btn btn-default btn" ><i class="fa fa-trash-o"></i></button></td></span>
                                      </div>
                                      </td>-->
                                    </tr>

                                </tbody>
                            </table>

                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>

            