<style>
/*md-dialog{
max-width: 900px;

}*/
.md-dialog-container {

    z-index: 1000;

}

</style>


<form  ng-submit="$ctrl.createSchool()" name="schoolForm" novalidate >
        <div class="well" style="margin-left: -30px; margin-right: -30px;">

            <div class="row" >
                <div class='col-lg-2' ng-show="$ctrl.isSchoolEmpty" >

                    <button  type="submit" class="btn btn-danger" ng-disabled="schoolForm.$invalid">Enrégistrer</button>
                </div>
               <div class='col-lg-2' ng-show="!$ctrl.isSchoolEmpty">

                    <button  type="button" class="btn btn-danger" ng-disabled="schoolForm.$invalid">Modifier</button>
                </div>
            </div>
        </div>
        <div class="form-view-main">
            <div class="form-view">

                    <div class="row" >

                            <div class="col-lg-8">
                                <div class="form-group" ng-class="{ 'has-error' : schoolForm.name.$invalid && !schoolForm.name.$pristine }">
                                    <label>Nom de l'institution:</label>
                                    <input type="text" class="form-control" name="name" ng-model="$ctrl.school.name" ng-required="true" require="true"  placeholder="Nom de l'institution" /> 
                                    <p ng-show="schoolForm.name.$invalid && !schoolForm.name.$pristine" class="help-block">Lechamp nom est obligatoire</p>
                                </div>
                            </div>
                            <div class="col-lg-4">
                                <div class="form-group" ng-class="{ 'has-error' : schoolForm.code.$invalid && !schoolForm.code.$pristine }">
                                    <label>Sigle:</label>
                                    <input type="text" class="form-control" name="code" ng-model="$ctrl.school.code" ng-required="true" placeholder="Sigle" /> 
                                    <p ng-show="schoolForm.code.$invalid && !schoolForm.code.$pristine" class="help-block">Le champ Sigle est obligatoire</p>
                                </div>
                            </div>
                    </div>

                
                    <div class="row">
                            <div class="col-lg-6">
                                <label>Responsable:</label>
                                <div class="form-group input-group mb-3" ng-class="{ 'has-error' : schoolForm.logo.$invalid && !schoolForm.logo.$pristine }">
                                    
                                    <input type="text" class="form-control" name="responsable" ng-model="$ctrl.school.logo"  placeholder="Responsable de l'institution..." /> 
                                        <div class="input-group-addon" ng-click="$ctrl.addResponsable()">
                                            <span class="input-group-text"><i class="fa fa-caret-right"></i></span>
                                        </div>
                                    <p ng-show="schoolForm.logo.$invalid && !schoolForm.logo.$pristine" class="help-block">Le champ logo est obligatoire</p>
                                </div>
                            </div>

                            <div class="col-lg-6">
                                <div class="form-group" ng-class="{ 'has-error' : schoolForm.logo.$invalid && !schoolForm.logo.$pristine }">
                                    <label>Logo:</label>
                                    <input type="file" class="form-control" name="logo" ng-model="$ctrl.school.logo"  placeholder="Logo" /> 
                                    <p ng-show="schoolForm.logo.$invalid && !schoolForm.logo.$pristine" class="help-block">Le champ logo est obligatoire</p>
                                </div>
                            </div>
                        </div>


                </form>


                <!--tabs widget-->
                <div class="row" id="my_div">
                    <ul class="nav nav-tabs">
                      <li class="active"><a href="#">Liste des Ecoles</a></li>

                    </ul>

                                        <table class="table table-striped">
                                            <thead>
                                                <tr class="bg-warning">
                                                    <th>Nom</th>
                                                    <th>Code</th>
                                                    <th>Responsable</th>
                                                    <th>Date de création</th>
                                                    <th></th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr ng-repeat="fac in $ctrl.faculties" style="cursor: hand;cursor: pointer;" ng-click="semShow(sem)">
                                                  <td ng-bind="fac.name"></td>
                                                  <td ng-bind="fac.code"></td>
                                                   <td ng-bind="fac.respo"></td>
                                                  <td ng-bind="fac.created_date"></td>
                                                  <td> 
                                                      <div class="btn-group">
                                                        <button type="button" ng-click="showCase.modifyPerson($index)" class="btn btn-default btn-xs"><i class="fa fa-edit"></i></button>
                                                        <button  type="button" ng-click="$ctrl.deleteFaculty(fac)" class="btn btn-default btn-xs" ><i class="fa fa-trash-o"></i></button></td>
                                                      </div>
                                                  </td>
                                                </tr>
                                            </tbody>
                                        </table>
                    <a class="btn btn-primary" ng-disabled="$ctrl.school.length<=0" ng-click="$ctrl.addFaculty($event)">Ajouter une ligne</a>
                    
                    

                 </div>
                <!--End tab-->
            </div>  
        </div>


    
    