
<link rel="stylesheet" type="text/css" href="css/datatables.bootstrap.css">
<link rel="stylesheel" type="text/css" href="css/buttons.datables.min.css">
<style>
/*md-dialog{
max-width: 900px;

}*/
.md-dialog-container {

    z-index: 1000;

}

</style>

  

</style>
<div class="row">
                <div class="col-lg-12">
                    <h4 class="page-header">Liste des filières</h4>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-12">
                    <!-- Panneau des boutton -->
                    <div class="panel panel-default">
                        <div class="panel-heading" style="margin-bottom: 15px;">

                            <button type="button" ng-click="$ctrl.addFiliere()" class="btn btn-danger" id='newacadyr'>Créer</a>
                        </div>
                        
                  <!--class="table table-striped table-bordered table-hover table-condensed datatable"-->
                            <table id="tblfilieres" datatable="ng" dt-options="dtOptions" dt-column-defs="dtColumnDefs" class="table table-striped table-bordered table-hover table-condensed datatable">
                                
                                <thead>
                                    <tr>
                                        <th  > Nom Filière</th>
                                        <th style="width:20%">Code Filière</th>
                                        <th style="width:10%">Statut</th>
                                       
                                        <th style="width:10%"></th>
                                    </tr>
                                </thead>
                                <tbody>
    
                                        <tr ng-repeat="fil in filieres" >
                                          <td ng-bind="fil.name"></td>
                                          <td ng-bind="fil.code"></td>
                                          <td ng-bind="fil.status"></td>
                                          
                                          
                                          <td>
                                              <div class="btn-group">
                                              <button type="button" ng-click="updateFiliere(fil)" class="btn btn-default btn"><i class="fa fa-edit"></i></button>
                                              <button  type="button" ng-click="deleteFiliere(fil)" class="btn btn-default btn" ><i class="fa fa-trash-o"></i></button></td>
                                              </div>
                                              
                                         </tr>

                                </tbody>
                            </table>

                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>

