
    
    <form  ng-submit="saveAcadYear()" name="acadForm" novalidate>
        <div class="well" style="margin-left: -30px; margin-right: -30px;">

            <div class="row">
                <div class='col-lg-2'>

                    <button  type="submit" class="btn btn-danger" ng-disabled="acadForm.$invalid">Enrégistrer</button>
                </div>
            </div>
        </div>
        <div class="form-view-main">
            <div class="form-view">

                    <div class="row" >

                            <div class="col-lg-6">
                                <div class="form-group" ng-class="{ 'has-error' : acadForm.code.$invalid && !acadForm.code.$pristine }">
                                    <label>Code:</label>
                                    <input type="text" class="form-control" name="code" ng-model="acadyr.code" ng-required="true" require="true"  placeholder="code" /> 
                                    <p ng-show="acadForm.code.$invalid && !acadForm.code.$pristine" class="help-block">Lechamp code est obligatoire</p>
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="form-group" ng-class="{ 'has-error' : acadForm.name.$invalid && !acadForm.name.$pristine }">
                                    <label>Nom:</label>
                                    <input type="text" class="form-control" name="name" ng-model="acadyr.name" ng-required="true" placeholder="nom" /> 
                                    <p ng-show="acadForm.name.$invalid && !acadForm.name.$pristine" class="help-block">Le champ nom est obligatoire</p>
                                </div>
                            </div>


                        </div>
                        <div class="row">

                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label>Date de début:</label>
                                    <div class="input-group">
                                      <input type="text" class="form-control" uib-datepicker-popup="{{format}}" ng-model="acadyr.starting_date" is-open="popup1.opened" datepicker-options="dateOptions" ng-required="true" close-text="Close" alt-input-formats="altInputFormats" />
                                      <span class="input-group-btn">
                                        <button type="button" class="btn btn-default" ng-click="open1()"><i class="glyphicon glyphicon-calendar"></i></button>
                                      </span>
                                      <p ng-show="acadForm.starting_date.$invalid && !acadForm.starting_date.$pristine" class="help-block">Le champ date de début est obligatoire</p>
                                    </div>
                                </div>
                            </div>
                             <div class="col-lg-6">
                                <div class="form-group">
                                    <label>Date de fin:</label>
                                    <div class="input-group">
                                      <input type="text" class="form-control" uib-datepicker-popup="{{format}}" ng-model="acadyr.ending_date" is-open="popup2.opened" datepicker-options="dateOptions" ng-required="true" close-text="Close" alt-input-formats="altInputFormats" />
                                      <span class="input-group-btn">
                                        <button type="button" class="btn btn-default" ng-click="open2()"><i class="glyphicon glyphicon-calendar"></i></button>
                                      </span>
                                      <p ng-show="acadForm.ending_date.$invalid && !acadForm.ending_date.$pristine" class="help-block">Le champ date de fin est obligatoire</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-6">
                                <div class="form-group">
                                    
                                    <div class="input-form">
                                        <label>Année par défaut:</label>
                                      <input type="checkbox"  ng-model="usr.annee_default"  />
                                      <p ng-show="acadForm.annee_default.$invalid && !acadForm.annee_default.$pristine" class="help-block">Le champ date de fin est obligatoire</p>
                                    </div>       
                                </div>
                            </div>

                        </div>

                </form>


                <!--tabs widget-->
                <div class="row" >
                    <ul class="nav nav-tabs">
                      <li class="active"><a href="#">Périodes de l'année académique</a></li>

                    </ul>

                                        <table class="table table-striped">
                                            <thead>
                                                <tr class="bg-warning">
                                                    <th>Code</th>
                                                    <th>Nom</th>
                                                    <th>Date de début</th>
                                                    <th>date de fin</th>
                                                    <th></th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr ng-repeat="sem in semesters" style="cursor: hand;cursor: pointer;" ng-click="semShow(sem)">
                                                  <td ng-bind="sem.code"></td>
                                                  <td ng-bind="sem.name"></td>
                                                   <td ng-bind="sem.starting_date"></td>
                                                  <td ng-bind="sem.ending_date"></td>
                                                  <td><span class="fa fa-trash-o" ></span></td>
                                                </tr>
                                            </tbody>
                                        </table>
                        <a class="btn btn-primary" ng-click="addSemester()">Ajouter une ligne</a>

                 </div>
                <!--End tab-->
            </div>  
        </div>

