
<style> 
.md-datepicker-calendar-pane{
z-index: 120000}

.md-select-menu-container {z-index: 120000;}



</style>
    
    <form  ng-submit=""  name="classForm" novalidate>
        <div class="well" style="margin-left: -30px; margin-right: -30px;" ng-init="$ctrl.init()">

            <div class="row">
                <div class='col-lg-2'>
                    <button  type="button" class="btn btn-danger" ng-click="$ctrl.updateClasse()" ng-show="$ctrl.isUpdate" ng-disabled="classForm.$invalid">Modifier</button>
                    <button  type="button" ng-click="$ctrl.addClasse()" class="btn btn-danger" ng-show="!$ctrl.isUpdate" ng-disabled="classForm.$invalid">Enrégistrer</button>
                    <span> <a href="#!/classes">Retour</a></span>
                </div>
                <div class="col-lg-4">
                    
                </div>
                <div class="col-lg-2">
                    
                    <button  type="button" ng-show="$ctrl.isUpdate" ng-click="$ctrl.deleteDegree()" ng-disabled="classForm.$invalid" class="btn btn-default">Supprimer</button>
                    
                    
                </div>
            </div>
        </div>
        <div class="form-view-main">
            <div class="form-view">



  
<div  layout="column" ng-cloak class="md-inline-form">


    <md-content layout-padding >
    <div layout='row' style="padding-top: 25px;" ng-show="$ctrl.classe.isCommonCore">
        <md-input-container class="md-block" flex='100' >
        <label>Choisir une formation de tronc commun:</label>          
            <md-select  name="cycle" placeholder="Choisir le cycle de formation" ng-model="$ctrl.classe.coreDegree"  md-no-asterisk  ng-required='$ctrl.classe.isCommonCore'>
                <md-option ng-value="degree.id" ng-repeat="degree in $ctrl.troncCommuns">{{degree.name}}</md-option>
            </md-select>
                  <div ng-messages="classForm.cycle.$error">
                      <div ng-message="required">Ce champ est obligatoire</div>
                  </div> 
        </md-input-container>
    </div>
     <div layout='row' style="background-color: #dfe4ea; padding-top: 25px;">
        <md-input-container class="md-block" flex="70"  >
              <label>Formations associées:</label>
              <md-autocomplete  md-search-text="$ctrl.searchText" 
                               md-selected-item="$ctrl.selectedItem"  
                               md-items="item in $ctrl.querySearch($ctrl.searchText)" 
                               md-item-text="item.name" 
                               md-min-length="0"
                               placeholder="Faites d'un diplôme de formation" 
                               md-selected-item-change="$ctrl.selectedItemChange(item)"
                               md-input-name="degree"
                               md-no-asterisk
                               >
                  <md-item-template>
                    <span md-highlight-text="$ctrl.searchText" md-highlight-flags="^i">{{item.name}}</span>

                  </md-item-template>
                  <md-not-found>
                    No states matching "{{$ctrl.searchText}}" were found.
                    <a ng-click="">Create a new one!</a>
                  </md-not-found>
            </md-autocomplete>
                  <div ng-messages="classForm.degree.$error">
                      <div ng-message="required">Ce champ est obligatoire</div>
                  </div> 
        </md-input-container>
        <md-input-container class="md-block" flex='10'  ng-show="$ctrl.classe.isCommonCore">

                    <button class="btn btn-danger" ng-click="$ctrl.addCommonCoreDegree($ctrl.selectedItem)"><i class="fa fa-plus"></i></button>

        </md-input-container>           
       
     <md-input-container class="md-block" flex='20' >
        Tronc commun?     
        <md-checkbox class='md-primary' ng-model="$ctrl.classe.isCommonCore" ng-change="$ctrl.resetCommonCoreDegree()"  "aria-label="Actif ?" md-no-ink ></md-checkbox>
        
    </md-input-container>  

    </div>
    <div  style="background-color: #dfe4ea;">

        <table>

           <tbody>
               <tr ng-repeat="deg in $ctrl.selectedDegrees track by deg.id">
                   <td class="text-primary" ng-bind="deg.name"></td>&nbsp;<td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td>
                   <td ><button class="btn btn-default btn-xs" ng-click="$ctrl.removeDegreeFromCommnCore(deg)"><i class="fa fa-trash"></i></button></td>
               </tr>

           </tbody>
       </table> 
    </div>        
        
    <div layout='row' style="padding-top: 25px;">
    <md-input-container class="md-block" flex='100' >
    <label>Cycle de formation:</label>          
        <md-select  name="cycle" placeholder="Choisir le cycle de formation" ng-model="$ctrl.classe.cycleId"  md-no-asterisk  ng-required='$ctrl.isCycleRequired'>
            <md-option ng-value="cycle.id" ng-repeat="cycle in $ctrl.trainingCycles">{{cycle.name}}</md-option>
        </md-select>
              <div ng-messages="classForm.cycle.$error">
                  <div ng-message="required">Ce champ est obligatoire</div>
              </div> 
    </md-input-container>
   
        
    <md-input-container class="md-block" flex='100' >
    <label>Niveau d'etude correspondant</label>          
        <md-select  name="level" placeholder="Choisir le niveau d'etude correspondant" ng-model="$ctrl.classe.studyLevel" md-on-open="loadLevels()" md-no-asterisk  required>
            <md-option ng-value="level.id" ng-repeat="level in $ctrl.levelsStudy">{{level.name}}</md-option>
        </md-select>
              <div ng-messages="classForm.level.$error">
                  <div ng-message="required">ce champ est obligatoire</div>

              </div>
    </md-input-container>
    </div>      
          
    <div layout-gt-sm="row">
        <md-input-container class="md-block" flex-gt-sm>
          <label>Nom de la classe:</label>
          <input name="name" ng-model="$ctrl.classe.name" md-no-asterisk required />
              <div ng-messages="classForm.name.$error">
                  <div ng-message="required">le champ nom est obligatoire</div>

              </div>   
        </md-input-container>

        <md-input-container class="md-block" flex-gt-sm>
          <label>Code de la classe:</label>
          <input name="code" ng-model="$ctrl.classe.code" required md-no-asterisk  minlength='3'/>
              <div ng-messages="classForm.code.$error">
                  <div ng-message="required">le champ code de spécialité est obligatoire</div>
                  <div ng-message="minlength">le code doit avoir au moins 3 caractères</div>
              </div> 
        </md-input-container>
        
        </div>
        
        <div layout-gt-sm='row' >
        <div class = "col-lg-12">
   

                    <md-checkbox ng-model="$ctrl.classe.isEndCycle"               
                        aria-label="Actif?"
                        ng-true-value="1"
                        ng-false-value="0"> 
                        Correspond à la fin de cycle
                    </md-checkbox>
           
           
                    <md-checkbox ng-model="$ctrl.classe.isEndDegreeTraining"               
                        aria-label="Actif?"
                        ng-true-value="1"
                        ng-false-value="0"> 
                        Correspond à la fin de formation
                    </md-checkbox>

                    <md-checkbox ng-model="$ctrl.classe.isEndCommonCore"  ng-show="$ctrl.commonCore"              
                        aria-label="Actif?"
                        ng-true-value="1"
                        ng-false-value="0"> 
                        Correspond à la fin du tronc commun
                    </md-checkbox>           
           
        </div>

         
        <div class = "col-lg-12"  style="background-color: #dfe4ea;" >
            <div class="row">  
            <div class="col-md-10"  style="margin-top:25px;">

                <md-input-container class="column md-block" flex-gt-sm>
                    <label>Associer des semestres à la classe:</label>
                    <md-autocomplete  md-search-text="$ctrl.searchSemester" 
                                     md-selected-item="$ctrl.selectedSem"  
                                     md-items="item in $ctrl.query($ctrl.searchSemester)" 
                                     md-item-text="item.code" 
                                     md-min-length="0"
                                     placeholder="Faites le choix de la classe" 
                                     md-selected-item-change="$ctrl.selectedItemChange(item)"
                                     md-input-name="classe"
                                     md-menu-container-class="custom-container"
                                     md-no-asterisk
                                     ng-required='$ctrl.showClasseElement'>
                        <md-item-template>
                          <span md-highlight-text="$ctrl.searchSemester" md-highlight-flags="^i">{{item.code}}</span>

                        </md-item-template>
                        <md-not-found>
                          Aucun élément correspondant à "{{$ctrl.searchSemester}}" n'a été trouvé.

                        </md-not-found>
                    </md-autocomplete>
                        <div ng-messages="gradeForm.classe.$error">
                            <div ng-message="required">Ce champ est obligatoire</div>
                        </div> 
                </md-input-container >

            </div>
            <div class="col-md-2" style="margin-top:40px;" >
                <button class="btn btn-danger" ng-click="$ctrl.associateSemToclasse()"><i class="fa fa-plus"></i></button>
            </div>
        </div>
           
            <div class="col-md-9">
            <table>
               
                <tbody>
                    <tr ng-repeat="sem in $ctrl.semesters">
                        <td class="text-primary" ng-bind="sem.code"></td>&nbsp;<td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td>
                        <td ><button class="btn btn-default" ng-click="$ctrl.removeSemToClasse(sem.code)"><i class="fa fa-trash"></i></button></td>
                    </tr>
                    
                </tbody>
            </table>
            </div>

           
        </div>             
        
        </div>

        </form>
  </md-content>

</div>
<p>&nbsp;</p>
              <!--tabs widget-->
              <!--  <div class="row" >
                    <ul class="nav nav-tabs">
                      <li class="active"><a href="#">Cyles de formation</a></li>

                    </ul>

                                        <table class="table table-striped">
                                            <thead>
                                                <tr class="bg-warning">
                                                    <th style='width:30%;'>Code</th>
                                                    <th>Nom</th>
                                                    <th>Durée</th>

                                                    <th style='width:12%;'></th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr ng-repeat="cycle in cycles" >
                                                  <td ng-bind="cycle.code"></td>
                                                  <td ng-bind="cycle.name"></td>
                                                  <td ng-bind="cycle.duration"></td>
                                                  <td>
                                                      
                                                      <button type="button" ng-click="showCurriculum(cycle)" class="btn btn-default btn"><i class="fa fa-edit"></i></button>
                                                      <button  type="button" ng-click="deleteCycle(cycle)" class="btn btn-default btn" ><i class="fa fa-trash-o"></i></button></td></span>
                                                    
                                                  </td>
                                                </tr>
                                            </tbody>
                                        </table>
                        <a class="btn btn-primary" ng-click="$ctrl.addCurriculum()">Ajouter un cycle</a>

                 </div>
              -->
                <!--End tab-->
                
            </div>  
        </div>

