
    
    <form  ng-submit=""  name="acadForm" novalidate>
        <div class="well" style="margin-left: -30px; margin-right: -30px;" ng-init="$ctrl.init()">

            <div class="row">
                <div class='col-lg-2'>
                    <button  type="button" class="btn btn-danger" ng-click="$ctrl.updateDegree()" ng-show="$ctrl.isUpdate" ng-disabled="acadForm.$invalid">Modifier</button>
                    <button  type="button" ng-click="$ctrl.addDegree()" class="btn btn-danger" ng-show="!$ctrl.isUpdate" ng-disabled="acadForm.$invalid">Enrégistrer</button>
                    <span> <a href="#!/degree">Annuler</a></span>
                </div>
                <div class="col-lg-4"></div>
                <div class="col-lg-2">
                    
                    <button  type="button" ng-show="$ctrl.isUpdate" ng-click="$ctrl.deleteDegree()" ng-disabled="acadForm.$invalid" class="btn btn-default">Supprimer</button>
                    
                    
                </div>
            </div>
        </div>
        <div class="form-view-main">
            <div class="form-view">


<style> 
.md-datepicker-calendar-pane{
z-index: 120000}

.md-select-menu-container {z-index: 120000;}
</style>

  
<div  layout="column" ng-cloak class="md-inline-form">


    <md-content layout-padding >
    <div>
      <form name="degreeForm">
            <div layout layout-sm="column">
                <md-input-container flex="flex" style="width: 60%; margin-top: 15px;" >
                    <label>Cycle de formation:</label>
                    <md-select name="dpt" placeholder="Choisir le cycle de formation" ng-model="$ctrl.degree.cycle_id"   style="width: 60%;" required>
                         <md-option ng-disabled="true"><em>---Choix de la spécialité---</em></md-option>
                         
                        <md-option ng-value="cycle.id" ng-repeat="cycle in cyclesFormation">{{cycle.name}}</md-option>
                    </md-select>
               </md-input-container>
            </div>            
          <div layout='column'>
          <md-input-container class="md-block" style="width: 85%; margin-top: 20px;" >
          <label>Filière:</label>
          <md-autocomplete flex="70" md-search-text="$ctrl.searchText" md-min-length="0" md-selected-item="$ctrl.selectedItem"  
                           md-items="item in $ctrl.querySearch($ctrl.searchText)" md-selected-item-change="$ctrl.searchSpeByFil($ctrl.selectedItem.id)"
                           md-item-text="item.name" placeholder="Faites le choix d'une filière" required>
              <md-item-template>
                <span md-highlight-text="$ctrl.searchText" md-highlight-flags="^i">{{item.name}}</span>

              </md-item-template>
              <md-not-found>
                No states matching "{{$ctrl.searchText}}" were found.
                <a ng-click="">Create a new one!</a>
              </md-not-found>

            </md-autocomplete>
          </md-input-container>
          </div>
        
            <div layout layout-sm="column">
                <md-input-container flex="flex" style="width: 60%; margin-top: 15px;" >
                    <label>Spécialité:</label>
                    <md-select name="dpt" placeholder="Choisir la spécialité" ng-model="$ctrl.degree.spe_id"  ng-change="$ctrl.searchOptionBySpe(degree.spe_id)" style="width: 60%;" >
                         <md-option ng-disabled="true"><em>---Choix de la spécialité---</em></md-option>
                         
                        <md-option ng-value="spe.id" ng-repeat="spe in specialites">{{spe.name}}</md-option>
                    </md-select>
               </md-input-container>
            </div> 
          <div layout layout-sm="row">
     
                <md-input-container class="md-block" flex-gt-sm  style=" margin-top: 15px;" >
                    <label>Option:</label>
                    <md-select name="dpt" placeholder="Choisir l'option" ng-model="$trl.degree.opt_id"   style="width: 60%;"  >
                         <md-option ng-disabled="true"><em>---Choix de l'option---</em></md-option>
                        <md-option ng-value="opt.id" ng-repeat="opt in options">{{fil.name}}</md-option>
                    </md-select>
               </md-input-container>

            
                        
         </div>
          <div layout-gt-sm="row" style="margin-top:10px;">
          <md-input-container class="md-block" flex-gt-sm>
            <label>Nom du diplôme:</label>
            <input name="name" ng-model="$ctrl.degree.name" required />
                <div ng-messages="degreeForm.name.$error">
                    <div ng-message="required">le champ nom est obligatoire</div>
                    
                </div>   
          </md-input-container>

          <md-input-container class="md-block" flex-gt-sm>
            <label>Code du diplôme:</label>
            <input name="code" ng-model="$ctrl.degree.code" required />
                <div ng-messages="degreeForm.code.$error">
                    <div ng-message="required">le champ code de spécialité est obligatoire</div>
                    <div ng-message="minlength">le code doit avoir au moins 2 caractères</div>
                </div> 
          </md-input-container>
        </div>
        <md-input-container class="md-block" flex-gt-sm">
                
                    <md-checkbox ng-model="$ctrl.degree.isCoreCurriculum"   class="md-primary"            
                    aria-label="Tronc commun?"
                    ng-true-value="true"
                    ng-false-value="false"> 
                </md-checkbox>
            <span>Tronc commun?</span>
          </md-input-container>
            <md-input-container class="md-block" flex-gt-sm">
                
                <md-checkbox ng-model="$ctrl.degree.status"   class="md-primary"            
                    aria-label="Actif?"
                    ng-true-value="1"
                    ng-false-value="0"> 
                </md-checkbox>
                <span>Actif?</span>
          </md-input-container>


        

      </form>
    </div>
  </md-content>

</div>


<p>&nbsp;</p>

                <!--tabs widget-->
                <div class="row" >
                    <ul class="nav nav-tabs">
                      <li class="active"><a href="#">Cyles de formation</a></li>

                    </ul>

                                        <table class="table table-striped">
                                            <thead>
                                                <tr class="bg-warning">
                                                    <th style='width:30%;'>Code</th>
                                                    <th>Nom</th>
                                                    <th>Niveau</th>
                                                    <th>Durée</th>

                                                    <th style='width:12%;'></th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr ng-repeat="cycle in cycles" >
                                                  <td ng-bind="cycle.code"></td>
                                                  <td ng-bind="cycle.name"></td>
                                                  <td ng-bind="cycle.cycleLevel"></td>
                                                  <td ng-bind="cycle.duration"></td>
                                                  <td>
                                                      
                                                      <button type="button" ng-click="showCurriculum(cycle)" class="btn btn-default btn"><i class="fa fa-edit"></i></button>
                                                      <button  type="button" ng-click="deleteCycle(cycle)" class="btn btn-default btn" ><i class="fa fa-trash-o"></i></button></td></span>
                                                    
                                                  </td>
                                                </tr>
                                            </tbody>
                                        </table>
                        <a class="btn btn-primary" ng-click="$ctrl.addCurriculum()">Ajouter un cycle</a>

                 </div>
                <!--End tab-->
            </div>  
        </div>

