
<link rel="stylesheet" type="text/css" href="css/datatables.bootstrap.css">
<link rel="stylesheel" type="text/css" href="css/buttons.datables.min.css">
<style>
  /*.table th{
  background-color:#337ab7;
 // color:white;
  text-align:left;
  vertical-align:center;
}*/
  

</style>
<div class="row">
                <div class="col-lg-12">
                    <h4 class="page-header">Liste des filières</h4>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-12">
                    <!-- Panneau des boutton -->
                    <div class="panel panel-default">
                        <div class="panel-heading" style="margin-bottom: 15px;">

                            <a href="#!/createfiliere" class="btn btn-danger" id='newacadyr'>Créer</a>
                        </div>
                        
                  <!--class="table table-striped table-bordered table-hover table-condensed datatable"-->
                            <table  datatable="ng" dt-options="dtOptions" dt-column-defs="dtColumnDefs" class="table table-striped table-bordered table-hover table-condensed datatable">
                                
                                <thead>
                                    <tr>
                                        <th>Code Filière</th>
                                        <th> Nom Filière</th>
                                        <th>Faculté</th>
                                       
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
    
                                        <tr ng-repeat="acayr in acadyrs" >
                                          <td ng-bind="acayr.code"></td>
                                          <td ng-bind="acayr.name"></td>
                                          <td ng-bind="acayr.starting_date"></td>
                                          
                                          
                                          <td>
                                              <div class="btn-group">
                                              <button type="button" ng-click="showCase.modifyPerson($index)" class="btn btn-default btn"><i class="fa fa-edit"></i></button>
                                              <button  type="button" class="btn btn-default btn" ><i class="fa fa-trash-o"></i></button></td>
                                              </div>
                                              
                                         </tr>

                                </tbody>
                            </table>

                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>

            


    
                                        <select class="form-control"  ng-model="data.model" >
                                        <option ng-repeat="fac in $ctrl.faculties" value="{{fac.id}}"> {{fac.name}} </option>
                                    </select>