
<link rel="stylesheet" type="text/css" href="css/datatables.bootstrap.css">
<link rel="stylesheel" type="text/css" href="css/buttons.datables.min.css">
<style>
/*md-dialog{
max-width: 900px;

}*/
.md-dialog-container {
    //position: fixed !important;
   // left: 20%;
    //top: 0%;
    //background-color: white;
    z-index: 1000;

}

</style>

  

</style>
<div class="row">
                <div class="col-lg-12">
                    <h4 class="page-header">Liste des Spécialités</h4>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row" ng-init="$ctrl.init()">
                <div class="col-lg-12">
                    <!-- Panneau des boutton -->
                    <div class="panel panel-default">
                        <div class="panel-heading" style="margin-bottom: 15px;">

                            <button type="button" ng-click="$ctrl.redirect(-1)" class="btn btn-danger" id='newacadyr'>Créer</a>
                        </div>
                        
                  <!--class="table table-striped table-bordered table-hover table-condensed datatable"-->
                  <table id="tblfilieres" datatable="ng" dt-options="dtOptions" dt-column-defs="dtColumnDefs"  class="table table-striped  table-hover table-condensed datatable">
                                
                                <thead>
                                    <tr>
                                        <th  > N°</th>
                                        <th  > Nom Spécialité</th>
                                        <th >Code Spécialité</th>
                                        <th >Statut</th>
                                       
                                        <th ></th>
                                    </tr>
                                </thead>
                                <tbody>
    
                                    <tr ng-repeat="spe in specialites" style="cursor: pointer" ng-dblclick="$ctrl.redirectUpdate(spe.id)">
                                            <td >{{$ctrl.cpt + $index}}</td>
                                          <td ng-bind="spe.name"></td>
                                          <td ng-bind="spe.code"></td>
                                          <td ng-bind='spe.status?"":"x"' ng-class="{'zf-green fa fa-check': spe.status,'zf-red': !spe.status }"></td>
                                          
                                          
                                          <td>
                                              <div class="btn-group">

                                              <button  type="button" ng-click="$ctrl.deleteSpe(spe)" class="btn btn-danger  btn-xs" ><i class="fa fa-trash-o"></i></button></td>
                                              </div>
                                              
                                         </tr>

                                </tbody>
                            </table>

                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>

