<script src="js/app/department/department.component.js"></script>
<link rel="stylesheet" href='js/datatables-plugins/dataTables.bootstrap.css'>


<style> 
.md-datepicker-calendar-pane{
z-index: 120000}

.md-select-menu-container {z-index: 120000;}

li.active a.ng-binding {
  color: #000 !important;
	background-color: #eeeeee !important;
	text-decoration: none;
}

</style>


<div class="well"  style="margin-left: -30px; margin-right: -30px;" ng-init="$ctrl.init()">
        
            <div class="row">
                <div class='col-md-6'>

                    <button  ng-show=" <?=($this->access('global.system.admin', null))?true:false?> && !$ctrl.isUpdate" type="button" ng-click="$ctrl.updateDept(dpt)" class="btn btn-danger" ng-disabled="myForm.$invalid" ><span class="fa fa-edit"></span>&nbsp;Modifier Département</button>
                    <span> <a href="#!/department">Retour</a></span>
                </div>
                <div class="col-md-6" > <h4>Gérer les Départements</h4></div>

                

                
            </div>
</div>

<div class="form-view-main">
    <div class="form-view">
        <div   ng-cloak class="md-inline-form">


    <md-content layout-padding >
        <form   name="myForm">

   
      <div class="md-dialog-content"  ng-init="init()">
        
            <div layout="row">

                <md-select name="faculty" placeholder="Choisir la établissement" ng-model="dpt.fac_id"  ng-change="$ctrl.searchDptByFaculty(dpt.fac_id)" style="min-width: 400px;" required>
                         <md-option ng-disabled="true"><em>---Choix de l'établissement---</em></md-option>
                        <md-option ng-value="faculty.id" ng-repeat="faculty in faculties">{{faculty.name}}</md-option>
                    </md-select>
            </div>
            <div layout layout-sm="column">
                <md-input-container flex="flex" style="width: 60%" >
                    <label>Nom du département:</label>
                    <input type='text'  name='name' ng-model="dpt.name" width='80%' md-no-asterisk required />
                        <div ng-messages="myForm.name.$error">
                            <div ng-message="required">le champ code département est obligatoire</div>
                            <div ng-message="minlength">le code doit avoir au moins 3 caractères</div>
                        </div>                    
        
                </md-input-container>
                <md-input-container flex="flex" style="width: 20%" >
                  
                    <label>Code département:</label>
                    <input type='text'  name="code" ng-model="dpt.code" width='80%' minlength="2" md-no-asterisk required />
                        <div ng-messages="myForm.code.$error">
                            <div ng-message="required">le champ code département est obligatoire</div>
                            <div ng-message="minlength">le code doit avoir au moins 3 caractères</div>
                        </div>
                </md-input-container> 
            </div>

          <md-checkbox class='md-primary' ng-model="dpt.status"  ng-checked="(dpt.status)"aria-label="Actif ?" md-no-ink ></md-checkbox>


      </div>
     
         




        </form>
  </md-content>
</div>
        

        
<p>&nbsp;</p>
              <!--tabs widget-->
              
    <uib-tabset>
      <uib-tab >
          <uib-tab-heading>
              <span>Liste des filières</span>
          </uib-tab-heading>
        <div class="tab-container">              
                <div class="row" >
                    <table class="table table-striped table-condensed">
                         <thead>
                             <tr class="bg-primary">
                                 <th>Num</th>
                                 <th>Code Filière</th>
                                 <th>Nom Filière</th>
                                 <th >status</th>
                                 <th ></th>

                             </tr>
                         </thead>
                         <tbody>
                             <tr ng-repeat="fil in filieres" >
                               <td >{{$ctrl.cpt + $index}}</td>
                               <td ng-bind="fil.code"></td>
                               <td ng-bind="fil.name"></td> 
                               <td ng-bind='fil.status?"":"x"' ng-class="{'zf-green fa fa-check': dep.status,'zf-red': !dep.status }"> </td>
                               <td>
                                   <div class="btn-group">
                                    
                                    <button  type="button" ng-click="$ctrl.deleteFil(fil)" class="btn btn-default btn-xs btn-danger" ><i class="fa fa-trash-o"></i></button>   
                                   </div>
                               </td>

                             </tr>
                         </tbody>
                     </table>
                 </div>
                <!--End tab-->
                
            </div>  
            </uib-tab>
              <uib-tab>
                <uib-tab-heading>
                    <span>Liste des Responsables</span>
                </uib-tab-heading>
                <div class="tab-container"> 
                </div>
            </uib-tab>
        </div>

