<script src="js/app/department/department.component.js"></script>
<link rel="stylesheet" href='js/datatables-plugins/dataTables.bootstrap.css'>


<style> 
.md-datepicker-calendar-pane{
z-index: 120000}

.md-select-menu-container {z-index: 120000;}

li.active a.ng-binding {
  color: #000 !important;
	background-color: #eeeeee !important;
	text-decoration: none;
}

</style>


<div class="well"  style="margin-left: -30px; margin-right: -30px;" ng-init="$ctrl.init()">
        
            <div class="row">
                <div class='col-md-6'>

                    <button  ng-show=" <?=($this->access('global.system.admin', null))?true:false?> && !$ctrl.isUpdate" type="button" ng-click="$ctrl.updateCycle(cycle)" class="btn btn-danger" ng-disabled="myForm.$invalid" ><span class="fa fa-edit"></span>&nbsp;Modifier Cycle </button>
                    <span> <a href="#!/cycleFormation">Retour</a></span>
                </div>
                <div class="col-md-6" > <h4>Gérer les Cycles de formation</h4></div>

                

                
            </div>
</div>

<div class="form-view-main">
    <div class="form-view">
        <div   ng-cloak class="md-inline-form">


    <md-content layout-padding >
        <form   name="myForm">

   
      <div class="md-dialog-content"  ng-init="init()">
        
          
            <div layout layout-sm="column">
                <md-input-container flex="flex" style="width: 60%" >
                    <label>Nom du cycle:</label>
                    <input type='text'  name='name' ng-model="cycle.name" width='80%' md-no-asterisk required />
                        <div ng-messages="myForm.name.$error">
                            <div ng-message="required">le champ nom de la filièreest obligatoire</div>
                            <div ng-message="minlength">le code doit avoir au moins 3 caractères</div>
                        </div>                    
        
                </md-input-container>
                <md-input-container flex="flex" style="width: 20%" >
                  
                    <label>Code Cycle:</label>
                    <input type='text'  name="code" ng-model="cycle.code" width='80%' minlength="2" md-no-asterisk required />
                        <div ng-messages="myForm.code.$error">
                            <div ng-message="required">le champ code  est obligatoire</div>
                            <div ng-message="minlength">le code doit avoir au moins 3 caractères</div>
                        </div>
                </md-input-container> 
            </div>

          <md-checkbox class='md-primary' ng-model="cycle.status"  ng-checked="(cycle.status)"aria-label="Actif ?" md-no-ink ></md-checkbox>
      </div>
    </form>
  </md-content>
</div>
        

        
<p>&nbsp;</p>
              <!--tabs widget-->
              
    <uib-tabset>
      <uib-tab >
          <uib-tab-heading>
              <span>Liste des cycles e foramtion</span>
          </uib-tab-heading>
        <div class="tab-container">              
                <div class="row" >
                    <table class="table table-striped table-condensed">
                         <thead>
                             <tr class="bg-primary">
                                 <th>Num</th>
                                 <th>Code cycle</th>
                                 <th>Nom Cycle de formation</th>
                                 <th >status</th>
                                 <th ></th>

                             </tr>
                         </thead>
                         <tbody>
                             <tr ng-repeat="cy in cycles" >
                               <td >{{$ctrl.cpt + $index}}</td>
                               <td ng-bind="cy.code"></td>
                               <td ng-bind="cy.name"></td> 
                               <td ng-bind='cy.status?"":"x"' ng-class="{'zf-green fa fa-check': cy.status,'zf-red': !cy.status }"> </td>
                               <td>
                                   <div class="btn-group">
                                    <button type="button" ng-click="$ctrl.updateCycle(cy)" class="btn btn-default btn-xs btn-info"><i class="fa fa-edit"></i></button>
                                    <button  type="button" ng-click="$ctrl.deleteCycle(cy)" class="btn btn-default btn-xs btn-danger" ><i class="fa fa-trash-o"></i></button>   
                                   </div>
                               </td>

                             </tr>
                         </tbody>
                     </table>
                 </div>
                <!--End tab-->
                
            </div>  
            </uib-tab>
              <uib-tab>
                <uib-tab-heading>
                    <span>Liste des Responsables</span>
                </uib-tab-heading>
                <div class="tab-container"> 
                </div>
            </uib-tab>
        </div>

