

<div ng-app="myApp" ng-controller="onlineregCtrl as $ctrl"  ng style="margin-top: 50px; ">
    <md-content id="std-main-content" ng-init="$ctrl.init()">
      <!-- Display workflow bar -->
        <div style="text-align:right; height:10px; margin-bottom: 30px;">
            Draft<img src="img/icons8-forward-50.png" style="height:30px;">
            Attente payment<img src="img/icons8-forward-50.png" style="height:30px;">
            Attente validation<img src="img/icons8-forward-50.png" style="height:30px;">
            Terminer<img src="img/icons8-forward-50.png" style="height:30px;">
        </div>
      <!-- End -->
      <p class="text-warning"><span class='fa fa-warning'>Prière de bien vouloir remplir les différents champs du formulaire. tous les champs suivis de l'astérisk<span class="text-danger">(*) </span> sont obligatoires.
              LE formulaire ne pourra être soumis que si les champs sont bien remplis</span></p>
      <!--Showing tabs -->
        <md-tabs md-dynamic-height md-border-bottom class="md-no-animation padding"  >
            <!--First tab -->
            <md-tab label="Inscription Administrative">
                <md-content >
                <div  layout="column" ng-cloak class="md-inline-form">
                     <form name="stdRegistrationForm">
                    <div class="row">
                        <div class="col-md-3">
                          <img style="width:200px; height:200px;" ng-src="{{imageSrc}}" />      
                          <md-input-container class="md-block" flex-gt-sm>
                            
                            <input type ="file" name="image" ng-file-select="onFileSelect($files)" ng-model="imageSrc"   />
                                <div ng-messages="stdRegistrationForm.image.$error">
                                    <div ng-message="required">le champ photo est obligatoire</div>
                                    
                                </div> 
                          </md-input-container>                            
   
                        </div>
                        <div class="col-md-9">
                            <p class=" ">
                            <span class="text-primary pull-right"><?=$this->studentFaculty ?></span><br />
                            <span class="text-primary pull-right"><?=$this->studentTraining?></span> <br />
                            
                            <span class="text-primary"><?=$this->studentName?></span><span class="pull-right"><?=$this->studentClasse?></span>
                            </p>
                        </div>
                    </div>
                     
                            <md-toolbar>
                            <div class="md-toolbar-tools">
                              <h2>Identifcation de l'étudiant</h2>
                            </div>
                          </md-toolbar>
                          <div layout-gt-sm="row"  style='margin-top: 15px;'>
                          <md-input-container class="md-block" flex-gt-sm>
                            <label>Nom:</label>
                            <input name="name" ng-model="$ctrl.student.name" required />
                                <div ng-messages="stdRegistrationForm.name.$error">
                                    <div ng-message="required">le champ nom est obligatoire</div>

                                </div>   
                          </md-input-container>

                          <md-input-container class="md-block" flex-gt-sm>
                            <label>Prénom:</label>
                            <input name="prenom" ng-model="$ctrl.student.prenom" required />
                                <div ng-messages="stdRegistrationForm.prenom.$error">
                                    <div ng-message="required">le champ Prénom est obligatoire</div>
                                    
                                </div> 
                          </md-input-container>
                        </div>
                        <div layout-gt-sm="row" >
                            <md-input-container class="md-block" flex-gt-sm>
                              <label>Date de naissance</label>
                              <md-datepicker  ng-model="$ctrl.student.birthdate" name="birthdate" required></md-datepicker>

                              <div ng-messages="stdRegistrationForm.birthdate.$error">
                                <div ng-message="valid">Format de date invalide</div>
                                <div ng-message="required">le champ date de naissance est obligatoire</div>

                              </div>
                            </md-input-container>

                          <md-input-container class="md-block" flex-gt-sm>
                            <label>Ville de naissance:</label>
                            <input name="birthplace" ng-model="$ctrl.student.birthplace" required />
                                <div ng-messages="stdRegistrationForm.birthplace.$error">
                                    <div ng-message="required">le champ Prénom est obligatoire</div>
                                    
                                </div> 
                          </md-input-container>
                        </div>
                          <div layout-gt-sm="row"  >
                                <md-input-container class="md-block" flex-gt-sm>
                                    <label>Sexe</label>
                                    <md-select name='gender' ng-model="$ctrl.student.gender" required >
                                        <md-option value="M">Masculin</md-option>
                                        <md-option value="sword">Féminin</md-option>
                                    </md-select>
                                    <div ng-messages="stdRegistrationForm.gender.$error">
                                        <div ng-message="required">le champ Sexe est obligatoire</div>

                                    </div>                                    
                                </md-input-container>
                          
     
                                <md-input-container class="md-block" flex-gt-sm>
                                    <label>Numéro de téléphone</label>
                                    <input name="phoneNumber" ng-model="$ctrl.student.phoneNumber" ng-pattern="/^[0-9]{9}$/" required />
                                    <div ng-messages="stdRegistrationForm.phoneNumber.$error">
                                        <div ng-message="required">le champ numéro de téléphone est obligatoire</div>
                                        <div ng-message="pattern">Numéro de téléphone invalid</div>
                         
                                    </div>
                                </md-input-container>
                                <md-input-container class="md-block" flex-gt-sm>
                                    <label>Email</label>
                                    <input name="email" ng-model="$ctrl.student.email"  type="email" required  minlength="10" maxlength="100" ng-pattern="/^.+@.+\..+$/"  />
                                    <div ng-messages="stdRegistrationForm.email.$error" role="alert">
                                       <div ng-message-exp="['required', 'minlength', 'maxlength', 'pattern']">
                                          votre email doit contenir au moins 10 et être semblable à un email.
                                        </div>
                                    </div>
                                </md-input-container>
   
                        </div>


                          <div layout-gt-sm="row" style='margin-top: 5px;' >
                                <md-input-container class="md-block" flex-gt-sm>
                                    <label>Langue</label>
                                    <md-select name ='language' ng-model="$ctrl.student.language" required >
                                        <md-option value="FR">Français</md-option>
                                        <md-option value="ANG">Anglais</md-option>
                                      </md-select>
                                    <div ng-messages="stdRegistrationForm.language.$error">
                                        <div ng-message="required">le champ Langue est obligatoire</div>
                                    </div> 
                                </md-input-container>
                                <md-input-container class="md-block" flex-gt-sm>
                                    <label>Nationalité</label>
                                    <md-select name='nationality' ng-model="$ctrl.student.nationality" required  >
                                        <md-option ng-repeat="country in $ctrl.countries" ng-value="country.name" >
                                          {{country.name}}
                                        </md-option>
                                      </md-select>
                                    <div ng-messages="stdRegistrationForm.nationality.$error">
                                        <div ng-message="required">le champ Nationalité est obligatoire</div>
                                    </div>                                     
                                </md-input-container>
                                <md-input-container class="md-block" flex-gt-sm>
                                    <label>Réligion</label>
                                    <md-select name='religion' ng-model="$ctrl.student.religion" required >
                                        <md-option value="CATHOLIQUE">Catholique</md-option>
                                        <md-option value="PROTESTANT">Protestant</md-option>
                                        <md-option value="MUSULMAN">Musulman</md-option>
                                        <md-option value="AUTRE">Autres</md-option>
                                      </md-select>
                                    <div ng-messages="stdRegistrationForm.religion.$error">
                                        <div ng-message="required">le champ Religion est obligatoire</div>
                                    </div> 
                                </md-input-container>

                          </div>
                          <div layout-gt-sm="row" style='margin-top: 15px;' >
                          
                                <md-input-container class="md-block" flex-gt-sm>
                                    <label>Situation matrimoniale</label>
                                    <md-select name='matrimonialStatus' ng-model="$ctrl.student.matrimonialStatus" required >
                                        <md-option value="Célibataire">Célibataire</md-option>
                                        <md-option value="Marié(e)">Marié(e)</md-option>
                                        <md-option value="Divorcé(e)">Divorcé(e)</md-option>
                                      </md-select>
                                    <div ng-messages="stdRegistrationForm.matrimonialStatus.$error">
                                        <div ng-message="required">le champ Situation matrimoniale est obligatoire</div>
                                    </div> 
                                </md-input-container>
                                <md-input-container class="md-block" flex-gt-sm>
                                    <label>Situation d'emploi</label>
                                    <md-select name='employmentStatus' ng-model="$ctrl.student.employmentStatus" required >
                                        <md-option value="Employé">Employé</md-option>
                                        <md-option value="Sans emploi">Sans emploi</md-option>

                                      </md-select>
                                    <div ng-messages="stdRegistrationForm.employmentStatus.$error">
                                        <div ng-message="required">le champ Situation d'emploi est obligatoire</div>
                                    </div> 
                                </md-input-container>
                                <md-input-container class="md-block" flex-gt-sm>
                                    <label>Handicap</label>
                                    <md-select name='handicap' ng-model="$ctrl.student.handicap" required >
                                        <md-option value="OUI">Oui</md-option>
                                        <md-option value="NON">Non</md-option>

                                      </md-select>
                                    <div ng-messages="stdRegistrationForm.handicap.$error">
                                        <div ng-message="required">le champ Handicap est obligatoire</div>
                                    </div> 
                                </md-input-container>
                            
                          </div>
                        
                          
 <!-- identification du père -->
                          <md-toolbar>
                            <div class="md-toolbar-tools">
                              <h2>Identifcation de du père</h2>
                            </div>
                          </md-toolbar>
                           <div layout-gt-sm="row" style='margin-top: 15px;'>
                          <md-input-container class="md-block" flex-gt-sm>
                            <label>Nom et Prénoms:</label>
                            <input name="fatherName" ng-model="$ctrl.student.fatherName" required />
                                <div ng-messages="stdRegistrationForm.fatherName.$error">
                                    <div ng-message="required">le champ nom est obligatoire</div>

                                </div>   
                          </md-input-container>

                          <md-input-container class="md-block" flex-gt-sm>
                            <label>Profession</label>
                            <input name="fatherProfession" ng-model="$ctrl.student.fatherProfession" required />
                                <div ng-messages="stdRegistrationForm.fatherProfession.$error">
                                    <div ng-message="required">le champ Profession est obligatoire</div>
                                    <div ng-message="minlength">le code doit avoir au moins 2 caractères</div>
                                </div> 
                          </md-input-container>
                        </div> 
                           <div layout-gt-sm="row" style='margin-top: 5px;' >
                                <md-input-container class="md-block" flex-gt-sm>
                                    <label>Pays de Résidence</label>
                                    <md-select name='fatherCountry' ng-model="$ctrl.student.fatherCountry" required >
                                        <md-option ng-repeat="country in $ctrl.countries" ng-value="country" >
                                          {{country.name}}
                                        </md-option>
                                    </md-select>
                                    <div ng-messages="stdRegistrationForm.fatherCountry.$error">
                                        <div ng-message="required">le champ Pays de résidence est obligatoire</div>
                                    </div> 
                                </md-input-container>

                                <md-input-container class="md-block" flex-gt-sm>
                                <label>Ville de résidence</label>
                                    <md-select name="fatherCity" ng-model="$ctrl.student.fatherCity" md-on-open="$ctrl.getCities($ctrl.student.fatherCountry.sortname)"  required>
                                    
                                        <md-option ng-repeat="city in $ctrl.cities" ng-value="city" >
                                          {{city.name}}
                                        </md-option>
                                    </md-select>
                                    
                                    <div ng-messages="stdRegistrationForm.fatherCity.$error">
                                        <div ng-message="required">le champ Région de résidence est obligatoire</div>
                                    </div> 
                                </md-input-container>
                                <md-input-container class="md-block" flex-gt-sm>

                                </md-input-container>
                          </div>
                           <div layout-gt-sm="row" style='margin-top: 10px;'>
                          <md-input-container class="md-block" flex-gt-sm>
                            <label>Numéro de téléphone:</label>
                            <input name="fatherPhoneNum" ng-model="$ctrl.student.fatherPhoneNum" ng-pattern="/^[0-9]{9}$/" required />
                                <div ng-messages="stdRegistrationForm.fatherPhoneNum.$error">
                                    <div ng-message="pattern">Numéro de téléphone invalid</div>

                                </div>   
                          </md-input-container>

                          <md-input-container class="md-block" flex-gt-sm>
                            <label>Email:</label>
                            <input name="fatherEmail" type="email" ng-model="$ctrl.student.fatherEmail" minlength="10" maxlength="100" ng-pattern="/^.+@.+\..+$/" />
                                <div ng-messages="stdRegistrationForm.fatherEmail.$error">
                                       <div ng-message-exp="['required', 'minlength', 'maxlength', 'pattern']">
                                          votre email doit contenir au moins 10 et être semblable à un email.
                                        </div>
                                </div> 
                          </md-input-container>
                        </div> 
 <!-- FIn identification du père -->
 
  <!-- identification de la mère -->
                            <md-toolbar>
                            <div class="md-toolbar-tools">
                              <h2>Identifcation de la mère</h2>
                            </div>
                          </md-toolbar>
                             <div layout-gt-sm="row" style='margin-top: 15px;'>
                          <md-input-container class="md-block" flex-gt-sm>
                            <label>Nom et Prénoms de la mère:</label>
                            <input name="motherName" ng-model="$ctrl.student.motherName" required />  
                                <div ng-messages="stdRegistrationForm.motherName.$error">
                                    <div ng-message="required">le champ nom est obligatoire</div>

                                </div>   
                          </md-input-container>

                          <md-input-container class="md-block" flex-gt-sm>
                            <label>Profession</label>
                            <input name="motherProfession" ng-model="$ctrl.student.motherProfession" required />
                                <div ng-messages="stdRegistrationForm.motherProfession.$error">
                                    <div ng-message="required">le champ Prénom est obligatoire</div>
                                    <div ng-message="minlength">le code doit avoir au moins 2 caractères</div>
                                </div> 
                          </md-input-container>
                        </div> 
                           <div layout-gt-sm="row" style='margin-top: 5px;' >
                                <md-input-container class="md-block" flex-gt-sm>
                                    <label>Pays de Résidence</label>
                                    <md-select name="motherCountry" ng-model="$ctrl.student.motherCountry" required >
                                        <md-option ng-repeat="country in $ctrl.countries_1" ng-value="country" >
                                          {{country.name}}
                                        </md-option>
                                      </md-select>
                                    <div ng-messages="stdRegistrationForm.motherCountry.$error">
                                        <div ng-message="required">le champ Ville  de résidence est obligatoire</div>
                                    </div>
                                </md-input-container>
                                <md-input-container class="md-block" flex-gt-sm>
                                    <label>Ville de résidence</label>
                                    <md-select name="motherCity" ng-model="$ctrl.student.motherCity" md-on-open="$ctrl.getCities_1($ctrl.student.motherCountry.sortname)"  required>
                                    
                                        <md-option ng-repeat="city in $ctrl.cities_1" ng-value="city.id" >
                                          {{city.name}}
                                        </md-option>
                                    </md-select>
                                    <div ng-messages="stdRegistrationForm.motherCity.$error">
                                        <div ng-message="required">le champ Région de résidence est obligatoire</div>
                                    </div>                                    
                                </md-input-container>
                                <md-input-container class="md-block" flex-gt-sm>
                            
                               
                                </md-input-container>

                          </div>
                           <div layout-gt-sm="row" style='margin-top: 15px;' >
                          <md-input-container class="md-block" flex-gt-sm>
                            <label>Numéro de téléphone:</label>
                            <input name="motherPhoneNum" ng-model="$ctrl.student.motherPhoneNum" ng-pattern="/^[0-9]{9}$/" required />
                                <div ng-messages="stdRegistrationForm.motherPhoneNum.$error">
                                    <div ng-message="required">le champ nom est obligatoire</div>
                                    <div ng-message="pattern">Numéro de téléphone invalid</div>

                                </div>   
                          </md-input-container>

                          <md-input-container class="md-block" flex-gt-sm>
                            <label>Email:</label>
                            <input name="motherEmail" type="email" ng-model="$ctrl.student.motherEmail" minlength="10" maxlength="100" ng-pattern="/^.+@.+\..+$/" />
                                <div ng-messages="stdRegistrationForm.motherEmail.$error">
                                       <div ng-message-exp="['required', 'minlength', 'maxlength', 'pattern']">
                                          votre email doit contenir au moins 10 et être semblable à un email.
                                        </div>
                                </div> 
                          </md-input-container>
                        </div> 
 <!-- FIn identification de la mère -->
 
   <!-- identification du tuteur -->
                          <md-toolbar>
                            <div class="md-toolbar-tools">
                              <h2>Identifcation du tuteur</h2>
                            </div>
                          </md-toolbar>
                             <div layout-gt-sm="row" style='margin-top: 15px;' >
                          <md-input-container class="md-block" flex-gt-sm>
                            <label>Nom et Prénoms:</label>
                            <input name="tutorName" ng-model="$ctrl.student.tutorName"  />
                                <div ng-messages="stdRegistrationForm.tutorName.$error">
                                    <div ng-message="required">le champ nom est obligatoire</div>

                                </div>   
                          </md-input-container>

                          <md-input-container class="md-block" flex-gt-sm>
                            <label>Profession</label>
                            <input name="tutorProfession" ng-model="$ctrl.student.tutorProfession" />
                                <div ng-messages="stdRegistrationForm.tutorProfession.$error">
                                    <div ng-message="required">le champ Prénom est obligatoire</div>
                                    <div ng-message="minlength">le code doit avoir au moins 2 caractères</div>
                                </div> 
                          </md-input-container>
                        </div> 
                           <div layout-gt-sm="row" style='margin-top: 5px;' >
                                <md-input-container class="md-block" flex-gt-sm>
                                    <label>Pays de Résidence</label>
                                    <md-select name="tutorCountry" ng-model="$ctrl.student.tutorCountry">
                                        <md-option ng-repeat="country in $ctrl.countries_2" ng-value="country" >
                                          {{country.name}}
                                        </md-option>
                                      </md-select>
                                    <div ng-messages="stdRegistrationForm.tutorCountry.$error">
                                        <div ng-message="required">le champ Région de résidence est obligatoire</div>
                                    </div>                                     
                                </md-input-container>
                                <md-input-container class="md-block" flex-gt-sm>
                                    <label>Ville de résidence</label>
                                    <md-select name="tutorCity" ng-model="$ctrl.student.tutorCity" md-on-open="$ctrl.getCities_2($ctrl.student.tutorCountry.sortname)" >
                                    
                                        <md-option ng-repeat="city in $ctrl.cities_2" ng-value="city.id" >
                                          {{city.name}}
                                        </md-option>
                                    </md-select>
                                    <div ng-messages="stdRegistrationForm.tutorCity.$error">
                                        <div ng-message="required">le champ Région de résidence est obligatoire</div>
                                    </div>                                     
                                </md-input-container>
                                <md-input-container class="md-block" flex-gt-sm>
                               
                                </md-input-container>

                          </div>
                           <div layout-gt-sm="row" style='margin-top: 15px;' >
                          <md-input-container class="md-block" flex-gt-sm>
                            <label>Numéro de téléphone:</label>
                            <input name="tutorPhoneNum" ng-model="$ctrl.student.tutorPhoneNum" ng-pattern="/^[0-9]{9}$/" />
                                <div ng-messages="stdRegistrationForm.tutorPhoneNum.$error">
                                    <div ng-message="required">le champ nom est obligatoire</div>
                                    <div ng-message="pattern">Numéro de téléphone invalid</div>

                                </div>   
                          </md-input-container>

                          <md-input-container class="md-block" flex-gt-sm>
                            <label>Email:</label>
                            <input name="tutorEmail" ng-model="$ctrl.student.tutorEmail" minlength="10" maxlength="100" ng-pattern="/^.+@.+\..+$/" />
                                <div ng-messages="stdRegistrationForm.tutorEmail.$error">
                                       <div ng-message-exp="['required', 'minlength', 'maxlength', 'pattern']">
                                          votre email doit contenir au moins 10 et être semblable à un email.
                                        </div>
                                </div> 
                          </md-input-container>
                        </div> 
 <!-- FIn identification du tuteur -->
 
   <!-- information du baccalauréat -->
                               <md-toolbar>
                            <div class="md-toolbar-tools">
                              <h2>Etudes antérieures</h2>
                            </div>
                          </md-toolbar>
                        <div layout-gt-sm="row" style='margin-top: 15px;'>
                          <md-input-container class="md-block" flex-gt-sm>
                            <label>Dernier établissement:</label>
                            <input name="lastSchool" ng-model="$ctrl.student.lastSchool" required />
                                <div ng-messages="stdRegistrationForm.lastSchool.$error">
                                    <div ng-message="required">le champ établissement est obligatoire</div>

                                </div>   
                          </md-input-container>

                          <md-input-container class="md-block" flex-gt-sm>
                            <label>Type du diplôme d'entrée</label>
                                    <md-select name="entranceCertificate" ng-model="$ctrl.student.entranceCertificate" ngchange='$ctrl.isBaccalaureat($ctrl.student.entranceCertificate)' required >
                                        <md-option value="BACC">Baccalauréat</md-option>
                                        <md-option value="BTS">BTS</md-option>
                                        <md-option value="DUT">DUT</md-option>
                                        <md-option value="GCE/A">GCE/A</md-option>
                                        <md-option value="HND">HND</md-option>
                                        <md-option value="LICENCE">Licence</md-option>
                                        <md-option value="MASTER">Master</md-option>
                                      </md-select>
                                    <div ng-messages="stdRegistrationForm.entranceCertificate.$error">
                                        <div ng-message="required">le champ diplôme de résidence est obligatoire</div>
                                    </div>  
                          </md-input-container>
                          <md-input-container class="md-block" flex-gt-sm>
                            <label>Matricule du diplôme:</label>
                            <input name="certificateId" ng-model="$ctrl.student.certificateId" required />
                                <div ng-messages="stdRegistrationForm.certificateId.$error">
                                    <div ng-message="required">le champ matricule est obligatoire</div>

                                </div>   
                          </md-input-container>
                        </div> 
                        <div layout-gt-sm="row" style='margin-top: 5px;' ng-show='$ctrl.isBaccalaureat($ctrl.student.entranceCertificate)'>
                          <md-input-container class="md-block" flex-gt-sm>
                            <label>Série:</label>
                            <md-select name="certificateOption" ng-model="$ctrl.student.certificateOption" ng-required='$ctrl.isBaccalaureat($ctrl.student.entranceCertificate)' >
                                        <md-option value="A">A</md-option>
                                        <md-option value="C">C</md-option>
                                        <md-option value="D">D</md-option>
                                        <md-option value="E">E</md-option>
                                        <md-option value="F1">F1</md-option>
                                        <md-option value="F3">F3</md-option>
                                        <md-option value="F4">F4</md-option>
                                        <md-option value="F5">F5</md-option>
                                        <md-option value="SCIENCE">Science</md-option>
                                        <md-option value="ART">Art</md-option>
                                      </md-select>
                                    <div ng-messages="stdRegistrationForm.entranceCertificate.$error">
                                        <div ng-message="required">le champ Série est obligatoire</div>
                                    </div>   
                          </md-input-container>

                          <md-input-container class="md-block" flex-gt-sm>
                            <label>Centre d'examen:</label>
                            <input name="examCenter" ng-model="$ctrl.student.examCenter" ng-required='$ctrl.isBaccalaureat($ctrl.student.entranceCertificate)' />
                                <div ng-messages="stdRegistrationForm.examCenter.$error">
                                    <div ng-message="required">Ce champ  est obligatoire</div>
                                    <div ng-message="minlength">le code doit avoir au moins 2 caractères</div>
                                </div> 
                          </md-input-container>
                         
                          <md-input-container class="md-block" flex-gt-sm>
                            <label>Session:</label>
                            <input name="examSession" ng-model="$ctrl.student.examSession" ng-required='$ctrl.isBaccalaureat($ctrl.student.entranceCertificate)' />
                                <div ng-messages="stdRegistrationForm.examSession.$error">
                                    <div ng-message="required">Ce champ  est obligatoire</div>

                               </div>   
                          </md-input-container>

                          <md-input-container class="md-block" flex-gt-sm>
                            <label>Reférence:</label>
                            <input name="examReference" ng-model="$ctrl.student.examReference" ng-required='$ctrl.isBaccalaureat($ctrl.student.entranceCertificate)' />
                                <div ng-messages="stdRegistrationForm.examReference.$error">
                                    <div ng-message="required">le champ Prénom est obligatoire</div>
                                    <div ng-message="minlength">le code doit avoir au moins 2 caractères</div>
                                </div> 
                          </md-input-container>
                          <md-input-container class="md-block" flex-gt-sm>
                            <label>Jury:</label>
                            <input name="examJury" ng-model="$ctrl.student.examJury" ng-required='$ctrl.isBaccalaureat($ctrl.student.entranceCertificate)' />
                                <div ng-messages="stdRegistrationForm.examJury.$error">
                                    <div ng-message="required">Ce champ  est obligatoire</div>

                               </div>   
                          </md-input-container>                            
                        </div> 
 <!-- FIn identification du baccalauréat -->
 
 
<!-- informations complémentaire -->
                            <md-toolbar>
                            <div class="md-toolbar-tools">
                              <h2>Informationis complémentaires</h2>
                            </div>
                          </md-toolbar>
                         <div layout-gt-sm="row" style='margin-top: 15px;' >
                          <md-input-container class="md-block" flex-gt-sm>
                            <label>Activités sportives:</label>
                            <input name="sport" ng-model="$ctrl.student.sport" required />
                                <div ng-messages="stdRegistrationForm.sport.$error">
                                    <div ng-message="required">Ce champ est obligatoire</div>

                                </div>   
                          </md-input-container>
                          </div> 
                          <div layout-gt-sm="row" >
                          <md-input-container class="md-block" flex-gt-sm>
                            <label>Activités associatives:</label>
                            <input name="association" ng-model="$ctrl.student.association" required />
                                <div ng-messages="stdRegistrationForm.association.$error">
                                    <div ng-message="required">Ce champ  est obligatoire</div>
                                    <div ng-message="minlength">le code doit avoir au moins 2 caractères</div>
                                </div> 
                          </md-input-container>
                        </div> 
                           <div layout-gt-sm="row" style='margin-top: -15px;' >
                           <md-input-container class="md-block" flex-gt-sm>
                            <label>Activités culturelles:</label>
                            <input name="cultural" ng-model="$ctrl.student.cultural" required />
                                <div ng-messages="stdRegistrationForm.cultural.$error">
                                    <div ng-message="required">Ce champ  est obligatoire</div>
                                    <div ng-message="minlength">le code doit avoir au moins 2 caractères</div>
                                </div> 
                          </md-input-container>
                           </div>
                           <div layout-gt-sm="row" >

                          <md-input-container class="md-block" flex-gt-sm>
                            <label>Connaissances informatique:</label>
                            <input name="computer" ng-model="$ctrl.student.computer" required />
                                <div ng-messages="stdRegistrationForm.computer.$error">
                                    <div ng-message="required">Ce champ  est obligatoire</div>
                                    <div ng-message="minlength">le code doit avoir au moins 2 caractères</div>
                                </div> 
                          </md-input-container>
                          </div>
            <div layout-gt-sm="row" style="background-color: white">
                <md-checkbox name='certified'
                  ng-model="data.cb2"
                  aria-label="Checkbox 2"
                  ng-true-value="'yup'"
                  ng-false-value="'nope'"
                  class="md-primary md-align-top-left" required flex>
                    
                Je certifie que les informations que je fournies à travers le présent formulaire sont exactes et vérifiables  <br/>
                <div ng-messages="stdRegistrationForm.certified.$error">
                   
                    
                </div> 
              </md-checkbox>                
            </div>
            <div layout-gt-sm="row" style="background-color: white">
                <md-input-container class="md-block" flex-gt-sm></md-input-container>
                <md-input-container class="md-block" flex-gt-sm></md-input-container>
                <md-input-container class="md-block " flex-gt-sm>
                    <div class="pull-right " >
                    <md-button  ng-click='$ctrl.submitRegistrationForm()' class="md-raised md-primary" ng-disabled="stdRegistrationForm.$invalid" >Enrégistrer</md-button>
                    </div>
                    
                </md-input-container>
                
            </div>

 <!-- FIn informations complémentaires -->
                      </form>
                   
                </div>
            </md-content>
                     
      </md-tab>
      <!-- EN TAB --> 

        
    </md-tabs>
    </md-content>
    
</div>

