<link rel="stylesheet" type="text/css" href="css/sb-admin-2.css">
<link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">
<link rel="stylesheel" type="text/css" href='bower_components/angular-material/angular-material.min.css'>
<br/><br/><br/>

            <!-- /.row -->
            <div class="row" ng-app="myApp" ng-cloak ng-controller="onlineregCtrl as $ctrl">
     
                    <form method="POST" action="">
    <div class="panel panel-primary" ng-init="$ctrl.student.classe='<?=$this->classe?>';$ctrl.student.matricule='<?=$this->matricule?>';init()">
    <div class="panel-heading">Inscription pédagogique</div>
    <div class="panel-body">
        <div class='alert alert-warning small'>
        Cette étpe vous permet de sélectionner les unités d'enseignement aux qulles vous allez participer pendant l'année académique.
        A titre de rappel chaque étudiant à droit à un maximum de 36 crédits par semestre. les unités d'enseignement en dette sont prioritaires.
        </div>


              <!--tabs widget-->
    <div class="row" ng-if='currentYrSubjects.length>0' >
        <ul class="nav nav-tabs">
          <li class="active"><a href="#">Matières</a></li>
        </ul>
                    
            <div class="row">
                <div class="col-md-6">
                    <div ng-class='(nbreCreditInscrit(subjectList1)>36?"panel panel-red":"panel panel-success")'>
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-support fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge">{{sem1}}</div>
                                    <div>Vous avez choisi : <strong>{{nbreCreditInscrit(subjectList1)}}/{{(totalCredits1+totalCredits3)}} </strong> Crédits</div>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>  
                <div class=" col-md-6">
                    <div ng-class='(nbreCreditInscrit(subjectList2)>36?"panel panel-red":"panel panel-success")'>
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-support fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge">{{sem2}}</div>
                                    <div>Vous avez choisi : <strong>{{nbreCreditInscrit(subjectList2)}}/{{(totalCredits2+totalCredits4)}}</strong> Crédits</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>                        
        </div>                  
                <div class='row'>
                    <div ng-repeat="sem in semesters"> 
                    
                            
                        <div class='col-md-6'>
                        <!-- <h5 ng-bind="sem.code"></h5>-->    
                                        <table class="table table-striped table-condensed small">
                                            <thead>
                                                <tr class="bg-warning">
                                                    <th>#</th>
                                                    <th style='width:30%;'>Code</th>
                                                    <th>UE</th>
                                                    <th>Crédits</th>
                                                    <th></th>
                                                </tr>
                                            </thead>
                                            <tbody >
     
                                                <tr ng-repeat="subject in currentYrSubjects" ng-if="(sem.code===subject.semester)&&sem.ranking%2===1"> 
                                                    <td ng-init="calculateSum1(subject)"></td>
                                                    <td ng-bind="subject.codeUe"></td>
                                                    <td ng-bind="subject.nomUe" ></td>
                                                    <td ng-bind="subject.credits"></td>

                                                     <td>
                                                         <input type="checkbox" ng-click="toggleSelection1(subject);"  ng-checked="exist1(subject)" /></td>

                                                </tr>
                                                <tr ng-if="sem.ranking%2===1" class='bg-danger'><th colspan='3'>Total</th><th ng-model="totalCredits1">{{totalCredits1}}</th><th></th></tr>
                                                
                                                 <tr ng-repeat="subject in currentYrSubjects" ng-if="(sem.code===subject.semester)&&sem.ranking%2===0"> 
                                                    <td ng-init="calculateSum2(subject)"></td>
                                                    <td ng-bind="subject.codeUe"></td>
                                                    <td ng-bind="subject.nomUe" ></td>
                                                    <td ng-bind="subject.credits"></td>

                                                     <td>
                                                         <input type="checkbox" ng-checked="exist2(subject)" ng-app="    "ng-click="toggleSelection2(subject);"/></td>

                                                </tr>                                               
                                                <tr ng-if="sem.ranking%2===0" class='bg-danger'><th colspan='3'>Total</th><th ng-bind="totalCredits2"></th><th></th></tr>
       
                                            </tbody>
                                        </table>
                        </div>
                        
                    </div>
                </div>
                      
                    <div ng-if="backlogs.length>0">
                    <div class="row" ><div class="col-md-12 text-center"><h5>UE A REPRENDRE</h5> </strong> </div></div>
                    <div  ng-repeat="sem in semesters">     
                    <div class='col-md-6' >
                        
                                        <table class="table table-striped table-condensed small" >
                                            <thead>
                                                <tr class="bg-warning">
                                                    <th>#</th>
                                                    <th style='width:30%;'>Code</th>
                                                    <th>UE</th>
                                                    <th>Crédits</th>
                                                    <th></th>
                                                </tr>
                                            </thead>
                                            <tbody >
    
                                                <tr  ng-repeat="back in backlogs" ng-if="(back.semRanking%2===sem.ranking%2)&&back.semRanking%2===1"> 
                                                        <td ng-init="calculateSum3(back)"></td>
                                                     <td ng-bind="back.codeUe"></td>
                                                     <td ng-bind="back.nomUe" ></td>
                                                     <td ng-bind="back.credits"></td>
                                                     <td>
                                                         <input type="checkbox" ng-checked="true" ng-disabled="true" />
                                                    </td>
                                                </tr>
                                                <tr ng-if="sem.ranking%2===1" class='bg-danger'><th colspan='3'>Total</th><th ng-bind="totalCredits3"></th><th></th></tr>
                                                
                                                <tr  ng-repeat="back in backlogs" ng-if="(back.semRanking%2===sem.ranking%2)&&back.semRanking%2===0"> 
                                                        <td ng-init="calculateSum4(back)"></td>
                                                     <td ng-bind="back.codeUe"></td>
                                                     <td ng-bind="back.nomUe" ></td>
                                                     <td ng-bind="back.credits"></td>
                                                     <td>
                                                         <input type="checkbox" ng-checked="true" ng-disabled="true" />
                                                    </td>
                                                </tr>                                                
                                                <tr ng-if="sem.ranking%2===0" class='bg-danger'><th colspan='3'>Total</th><th ng-bind="totalCredits4"></th><th></th></tr>      
                           
                                            </tbody>
                                        </table>                        
                        
                    </div> 
                    </div>
              </div>          

              <div class="row">
                  <md-input-container class="md-block pull-right" flex-gt-sm>
                      <md-button  ng-click='$ctrl.submitInscriptionPedagogique()' class="md-raised md-warn" ng-disabled="(disableSendButton1||disableSendButton2||$ctrl.submitInscriptionButtonDisabled)"  <!--ng-disabled="stdRegistrationForm.$invalid"-->Enrégistrer</md-button>
                  </md-input-container>
              </div>                        

        </div>
           
              <div ng-if="currentYrSubjects.length<=0">
              <div class="row">
                  <p class="text-center">Grille d'enseignments non encore disponible</p>
                  <md-input-container class="md-block pull-right" flex-gt-sm>
                      <a   class="btn btn-danger "  href="endRegistration"  <!--ng-disabled="stdRegistrationForm.$invalid"-->Suivant</a>
                  </md-input-container>
              </div>                  
              </div>
        
   </div>
</div>              

                <!--End tab-->                        
                    </form>
      
                
            </div>
    


                
            </div>  
        </div>

