
<style> 
.md-datepicker-calendar-pane{
z-index: 120000}

.md-select-menu-container {z-index: 120000;}



</style>
    
<form  ng-submit=""  name="teachingUnitForm" ng-cloak novalidate>
        <div class="well" style="margin-left: -30px; margin-right: -30px;" ng-init="$ctrl.init()">

            <div class="row">
                <div class='col-lg-2'>
                    <button  type="button" class="btn btn-danger" ng-click="$ctrl.updateUe()" ng-show="$ctrl.isUpdate" ng-disabled="teachingUnitForm.$invalid">Modifier</button>
                    <button  type="button" ng-click="$ctrl.addUe()" class="btn btn-danger" ng-show="!$ctrl.isUpdate" ng-disabled="teachingUnitForm.$invalid">Enrégistrer</button>
                    <span> <a href="#!/teachingunit">Annuler</a></span>
                </div>
                <div class="col-lg-4"></div>
                <div class="col-lg-2">
                    
                    <button  type="button" ng-show="$ctrl.isUpdate" ng-click="$ctrl.deleteUe()" ng-disabled="teachingUnitForm.$invalid" class="fa fa-trash-o btn btn-default">&nbsp;Supprimer</button>
                    
                    
                </div>
            </div>
        </div>
        <div class="form-view-main">
            <div class="form-view">



  
<div   ng-cloak class="md-inline-form">


    <md-content layout-padding >

    <div layout-gt-sm='row' >
    <md-input-container class="md-block" flex-gt-sm flex='40'>
          <label>Classe:</label>
          <md-autocomplete  md-search-text="$ctrl.searchText" 
                           md-selected-item="$ctrl.selectedItem"  
                           md-items="item in $ctrl.querySearch($ctrl.searchText)" 
                           md-item-text="item.name" 
                           md-min-length="0"
                           placeholder="Faites de la classe" 
                           md-selected-item-change="$ctrl.selectedItemChange(item)"
                           md-input-name="classe"
                           md-no-asterisk
                           required>
              <md-item-template>
                <span md-highlight-text="$ctrl.searchText" md-highlight-flags="^i">{{item.name}}</span>

              </md-item-template>
              <md-not-found>
                No states matching "{{$ctrl.searchText}}" were found.
                <a ng-click="">Create a new one!</a>
              </md-not-found>
        </md-autocomplete>
              <div ng-messages="teachingUnitForm.classe.$error">
                  <div ng-message="required">Ce champ est obligatoire</div>
              </div> 
    </md-input-container>
    <md-input-container class="md-block" flex-gt-sm flex='60'>
          <label>Enseignant:</label>
          <md-autocomplete md-search-text="$ctrl.searchText1" 
                           md-selected-item="$ctrl.selectedItem1"  
                           md-items="item1 in $ctrl.querySearch3()" 
                           md-item-text="item1.name" 
                           md-min-length="0"
                           placeholder="Enseignant de la classe" 
                           
                           md-input-name="lecturer"
                           md-no-asterisk
                           >
              <md-item-template>
                <span md-highlight-text="$ctrl.searchText" md-highlight-flags="^i">{{item1.name}}</span>

              </md-item-template>
              <md-not-found>
                No states matching "{{$ctrl.searchText}}" were found.
                <a ng-click="">Create a new one!</a>
              </md-not-found>
        </md-autocomplete>
              <div ng-messages="teachingUnitForm.classe.$error">
                  <div ng-message="required">Ce champ est obligatoire</div>
              </div> 
    </md-input-container>
    </div>
     
          
    <div layout-gt-sm="row">
        <md-input-container class="md-block" flex-gt-sm flex='60'>
          <label>Nom de l'UE:</label>
          <input name="name" ng-model="$ctrl.ue.name" md-no-asterisk required />
              <div ng-messages="teachingUnitForm.name.$error">
                    <div ng-message="required">le champ nom UE est obligatoire</div>

              </div>   
        </md-input-container>

        <md-input-container class="md-block" flex-gt-sm flex='10'>
          <label>Code UE:</label>
          <input name="code" ng-model="$ctrl.ue.code" required md-no-asterisk  minlength='3'/>
              <div ng-messages="teachingUnitForm.code.$error">
                  <div ng-message="required">le champ code UE  est obligatoire</div>
                  <div ng-message="minlength">le code doit avoir au moins 3 caractères</div>
              </div> 
        </md-input-container>
        
        <md-input-container class="md-block" flex-gt-sm flex='10'>
          <label>Cédits:</label>
          <input name="credits" type="number"  ng-model="$ctrl.ue.credits" required md-no-asterisk />
              <div ng-messages="teachingUnitForm.credits.$error">
                  <div ng-message="required">le champ nombre de crédits  est obligatoire</div>
                  
              </div> 
        </md-input-container>
        <md-input-container class="md-block" flex-gt-sm flex='10'>
          <label>Horaire:</label>
          <input name="vol_horaire" type="number" ng-model="$ctrl.ue.hours_vol" required md-no-asterisk />
              <div ng-messages="teachingUnitForm.vol_horaire.$error">
                  <div ng-message="required">le champ volume horaire est obligatoire</div>
                  
              </div> 
        </md-input-container>
        
        </div>
        
        <fieldset><legend>Répartition du volume horaire</legend>
      <div layout-gt-sm='row'>      
     <md-input-container class="md-block" flex-gt-sm flex='10'>
        
          <label>CM</label>
          <input name="cm" type='number' ng-model="$ctrl.ue.cm_hrs" required md-no-asterisk  />
              <div ng-messages="teachingUnitForm.cm.$error">
                  <div ng-message="required">le champ code UE  est obligatoire</div>

              </div> 
        </md-input-container>
        
        <md-input-container class="md-block" flex-gt-sm flex='10'>
          <label>TD</label>
          <input name="td" type="number"  ng-model="$ctrl.ue.td_hrs" required md-no-asterisk />
              <div ng-messages="teachingUnitForm.td.$error">
                  <div ng-message="required">le champ nombre de crédits  est obligatoire</div>
                  
              </div> 
        </md-input-container>
        <md-input-container class="md-block" flex-gt-sm flex='10' >
          <label>TP</label>
          <input name="tp" type="number" ng-model="$ctrl.ue.tp_hrs" required md-no-asterisk />
              <div ng-messages="teachingUnitForm.vol_horaire.$error">
                  <div ng-message="required">le champ volume horaire est obligatoire</div>
                  
              </div> 
        </md-input-container>
         
        </div>
            <div class="error">
                <small ng-show="$ctrl.ue.cm_hrs+$ctrl.ue.tp_hrs+$ctrl.ue.td_hrs>$ctrl.ue.hours_vol" >bla bla bla</small>
            </div>
    </fieldset>
        <div layout-gt-sm="column">
                <md-checkbox ng-model="$ctrl.classe.isEndCycle"               
                    aria-label="Actif?"
                    ng-true-value="1"
                    ng-false-value="0"> 
                    Est une UE obligatoire?
                </md-checkbox>

                <md-checkbox ng-model="$ctrl.classe.isEndDegreeTraining"               
                    aria-label="Actif?"
                    ng-true-value="1"
                    ng-false-value="0"> 
                   Esst une UE optionnelle?
                </md-checkbox>
          
        </div>

        </form>
  </md-content>

</div>
<p>&nbsp;</p>
              <!--tabs widget-->
                <div class="row" >
                    <ul class="nav nav-tabs">
                      <li class="active"><a href="#">Matières</a></li>

                    </ul>

                                        <table class="table table-striped">
                                            <thead>
                                                <tr class="bg-warning">
                                                    <th style='width:30%;'>Code</th>
                                                    <th>Nom</th>
                                                    <th colspan="4">Durée</th>
                                                    <th>CM</th>
                                                    <th>TP</th>
                                                    <th>TD</th>

                                                    <th style='width:12%;'></th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr ng-repeat="cycle in cycles" >
                                                  <td ng-bind="cycle.code"></td>
                                                  <td ng-bind="cycle.name"></td>
                                                  <td ng-bind="cycle.duration"></td>
                                                  <td ng-bind="cycle.duration"></td>
                                                  <td ng-bind="cycle.duration"></td>
                                                  <td>
                                                      
                                                      <button type="button" ng-click="showCurriculum(cycle)" class="btn btn-default btn"><i class="fa fa-edit"></i></button>
                                                      <button  type="button" ng-click="deleteCycle(cycle)" class="btn btn-default btn" ><i class="fa fa-trash-o"></i></button></td></span>
                                                    
                                                  </td>
                                                </tr>
                                            </tbody>
                                        </table>
                        <a class="btn btn-primary" ng-click="$ctrl.addSubject()">Ajouter une matière</a>

                 </div>
                <!--End tab-->
                
            </div>  
        </div>

