<link rel="stylesheet" href='js/datatables-plugins/dataTables.bootstrap.css'>


<style> 
.md-datepicker-calendar-pane{
z-index: 120000}

.md-select-menu-container {z-index: 120000;}



</style>


<div class="well" style="margin-left: -30px; margin-right: -30px;" ng-init="$ctrl.init()">
        
            <div class="row">
                <div class='col-md-4'>

                    <button  ng-show=" <?=($this->access('global.system.admin', null))||($this->access('exam.create', null))?true:false?> && !$ctrl.isUpdate" type="button" ng-click="saveChoices($ctrl.registeredStd)" class="btn btn-danger" ng-disabled="examForm.$invalid" >Enrégistrer</button>
                    <span> <a href="home">Annuler</a></span>
                </div>
                <div class="col-md-2"></div>


                
            </div>
</div>

<div class="form-view-main">
    <div class="form-view">
        <div   ng-cloak class="md-inline-form">


    <md-content layout-padding >
        <form   name="examForm">

   
        <div layout-gt-sm='row' >
            <md-input-container class="md-block" flex-gt-sm flex='60'>
                  <label>Classe:</label>
                  <md-autocomplete  md-search-text="$ctrl.searchClasse" 
                                   md-selected-item="$ctrl.selectedClasse"  
                                   md-items="item in $ctrl.query($ctrl.searchClasse)" 
                                   md-item-text="item.code" 
                                   md-min-length="0"
                                   placeholder="Faites de la classe" 
                                   md-selected-item-change="$ctrl.selectedItemChange(item)"
                                   md-input-name="classe"
                                   md-no-asterisk
                                   required>
                      <md-item-template>
                        <span md-highlight-text="$ctrl.searchClasse" md-highlight-flags="^i">{{item.code}}</span>

                      </md-item-template>
                      <md-not-found>
                        Aucun élément correspondant à "{{$ctrl.searchClasse}}" n'a été trouvé.

                      </md-not-found>
                </md-autocomplete>
                      <div ng-messages="examForm.classe.$error">
                          <div ng-message="required">Ce champ est obligatoire</div>
                      </div> 
            </md-input-container >
        <div layout-gt-sm='column' flex="40" >
        <md-input-container>
        <label>Semestre</label>
        <md-select name="semester" ng-model="$ctrl.selectedSem" ng-model-options="{trackBy: '$value.code'}" md-on-open="$ctrl.asignedSemToClasse($ctrl.selectedClasse.code);" ng-change="$ctrl.activateUeSelect(); $ctrl.loadUE($ctrl.selectedClasse,$ctrl.selectedSem.id)"
                    md-no-asterisk required >
            <md-option ng-disabled="true"><em>---Choix du Semestre---</em></md-option>
          <md-option ng-repeat="sem in $ctrl.semesters" ng-value="sem"  >
            {{sem.name}}
          </md-option>
        </md-select>
        <div class="errors" ng-messages="examForm.semester.$error">
          <div ng-message="required">Champ obligatoire</div>
        </div>
      </md-input-container>  
        </div> 

    </div>
     
            <div layout-gt-sm='row' flex="100" style="margin-top:15px;">
        <md-input-container flex="50">
            <label>Unité d'enseignement</label>
            <md-select   name="ue" ng-disabled="!$ctrl.isActivatedUeSelect" ng-model="$ctrl.selectedUe"  
                       ng-model-options="{trackBy: '$value.id'}"  md-on-open="$ctrl.loadUE($ctrl.selectedClasse,$ctrl.selectedSem.id);" 
                       ng-change="$ctrl.loadPedagogicalRegStd($ctrl.selectedUe,$ctrl.selectedClasse);"  md-no-asterisk ng-required="true">
                <md-option ng-disabled="true" ng-selected="true" ng-value="{id:-1}"><em>Choisissez une UE</em></md-option>
              <md-option ng-repeat="ue in $ctrl.ues" ng-value="ue" >
                {{ue.code}}[{{ue.name}}]
                {{$ctrl.markCalculationStatus=$ctrl.selectedUe.mark_calculation_status}}
              </md-option>
            </md-select>
            <div class="errors" ng-messages="examForm.ue.$error">
                <div ng-message="required">Champ obligatoire</div>
            </div>
        </md-input-container>  
    
        <md-input-container flex="50">
            <label>Matière</label>
            <md-select ng-disabled="!$ctrl.isActivatedMatiereSelect " name="matiere" ng-model="$ctrl.selectedSubject" 
                       ng-model-options="{trackBy: '$value.id'}"  ng-required="$ctrl.isMatiereRequired"
                       ng-change="$ctrl.loadPedagogicalRegStd($ctrl.selectedSubject,$ctrl.selectedClasse);" md-no-asterisk>
              <md-option ng-disabled="true"><em>---Choix de la Matière---</em></md-option>

              <md-option ng-repeat="subject in $ctrl.subjects" ng-value="subject" >
                {{subject.subjectCode}}[{{subject.subjectName}}]
              </md-option>
            </md-select>
            <div class="errors" ng-messages="examForm.matiere.$error">
              <div ng-message="required">Champ obligatoire</div>
            </div>
        </md-input-container>  
        </div>           




        </form>
  </md-content>
</div>
        

        
<p>&nbsp;</p>
              <!--tabs widget-->
                <div class="row" >
                    <ul class="nav nav-tabs">
                        <li class="active"><a href=""> Etudiant inscrits à l'UE  <span style='font-weight: bold; color: red;'>{{$ctrl.selectedUe.code}} [{{$ctrl.selectedSubject.subjectCode}}] </span> &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<i title='Ajouter des étudiants' style="color:lightgrey;  font-size: 22px; cursor: pointer;" class="fa fa-pencil-square-o"   ng-click="$ctrl.addStdToSubject()"></i></a></li>
                       
                            
                            
                            <div class="pull-right" style="color:lightgrey; margin-left: 10px; margin-right: 2px; margin-top: 10px;">
                                            <div class="btn-group">
                                                <button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown">
                                                   --- Actions ---
                                                    <span class="caret"></span>
                                                </button>
                                                <ul class="dropdown-menu pull-right" role="menu">
                                                    <li><a href="" ng-click="$ctrl.printNotes()"><span>Imprimer la liste</span></a>
                                                    </li>
                                                    <li><a href="" ng-click="saveChoices($ctrl.registeredStd)"><span>Enregistrer</span></a>
                                                    </li>
                                                    <!--<li><a href="" ng-click="$ctrl.clotureCalculNotes($ctrl.selectedUe.ue_class_id)"><span>Imprimer liste étudiants</span></a>
                                                    </li> -->
                                                </ul>
                                            </div>
                            </div>                            
                            <li class="active" style="color:lightgrey; margin-top: 10px;float: right;" >
                            <md-checkbox class="md-primary" aria-label="Select All"
                                ng-checked="isChecked()"
                                md-indeterminate="isIndeterminate()"
                                ng-click="toggleAll()">
                                <span ng-if="isChecked()"></span>Tout Selctionner
                                
                            </md-checkbox>
                          
                        </li>
                    </ul>

                                        <table class="table table-striped table-condensed">
                                            <thead>
                                                <tr class="bg-primary">
                                                    <th>Num</th>
                                                    <th>Matricule</th>
                                                    <th>Nom</th>
                                                    <th >Classe</th>
                                                    <th >Inscription</th>


                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr ng-repeat="std in items">
                                                  <td ng-bind="std.num"></td>
                                                  <td ng-bind="std.matricule"></td>
                                                  <td ng-bind="std.nom"></td>
                                                  <td ng-bind="std.studentCurrentClasse"></td>
                                                  
                                                  <td style="vertical-align: middle;">  
                                            <md-checkbox  ng-model="std.status" ng-disabled="(std.isRepeated===1) && '<?=!$this->access('global.system.admin',null)?>'"  aria-label="Checkbox Indeterminate" 
                                                                  ng-true-value="1"
                                                           ng-checked="exists(std, selected)" ng-click="toggle(std, selected)"                   
                                                                  class="md-primary">

                                                    </md-checkbox>  
                                                </td>
                                                </tr>
                                            </tbody>
                                        </table>
                 </div>
                <!--End tab-->
                
            </div>  
        </div>

