
<style> 
.md-datepicker-calendar-pane{
z-index: 120000}

.md-select-menu-container {z-index: 120000;}



</style>
    
    <form  ng-submit=""  name="classForm" novalidate>
        <div class="well" style="margin-left: -30px; margin-right: -30px;" ng-init="$ctrl.init()">

            <div class="row">
                <div class='col-lg-6'>
                    <button  type="button" class="btn btn-danger" ng-click="$ctrl.updateClasse()" ng-show="$ctrl.isUpdate" ng-disabled="classForm.$invalid">Modifier</button>
                    <button  type="button" ng-click="$ctrl.addClasse()" class="btn btn-danger" ng-show="!$ctrl.isUpdate" ng-disabled="classForm.$invalid">Enrégistrer</button>
                    <span> <a href="#!/prospects">[Retour]</a></span>
                </div>
                <div class="col-lg-4">
                <div class="pul-middle" >
                    <div class="btn-group">
                        <button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown">
                            Autres options
                            <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu pull-right" role="menu">

                            <li><a href="" ng-click="$ctrl.showPaymentProof($ctrl.prospect)" ><span>visualiser les pièces jointes</span></a>
                            <li><a href="" ng-click="$ctrl.showPrintNotes()" ><span>fiche de candidature</span></a>    
                            </li>
                        </ul>
                    </div>
                </div>                    
                </div>
                <div class="col-lg-2">
                    
                    <button  type="button" ng-show="$ctrl.isUpdate" ng-click="$ctrl.deleteDegree()" ng-disabled="classForm.$invalid" class="btn btn-default">Supprimer</button>
                    
                    
                </div>
            </div>
        </div>
        <div class="form-view-main">
            <div class="form-view">



  
<div  layout="column" ng-cloak class="md-inline-form" >


    <md-content layout-padding >

    <div layout='row'>
        <div class="col-md-6"><strong>Numéro du dossier:</strong>&nbsp;&nbsp;&nbsp; &nbsp;    {{$ctrl.prospect.numDossier}}</div> <div class="col-md-6"></div>
    </div>
    <div layout='row'>
        <div class="col-md-6"><strong>Nom:</strong>&nbsp;&nbsp;&nbsp;&nbsp;     {{$ctrl.prospect.nom+" "+$ctrl.prospect.prenom}}</div><div class="col-md-6" ></div>
    </div>
    <div layout='row'>
        <div class="col-md-12"><strong> Choix de la Fomation :&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</strong>{{$ctrl.prospect.classe}}</div>
        <p>
        <div>
        <md-radio-group ng-model="$ctrl.prospect.classe" aria-labelledby="favoriteFruit">
          <md-radio-button ng-value="$ctrl.prospect.choixFormation1" class="md-primary">Premier choix ({{$ctrl.prospect.choixFormation1}})</md-radio-button>
          <md-radio-button ng-value="$ctrl.prospect.choixFormation2">Deuxième choix ({{$ctrl.prospect.choixFormation2}})</md-radio-button>
          <md-radio-button ng-value="$ctrl.prospect.choixFormation3"> Troisième choix ({{$ctrl.prospect.choixFormation3}})</md-radio-button>
        </md-radio-group>
        </div>
        </p>
    </div>

 
           
    
    <div layout='row' class="bg-info">
        <div class="col-md-4"><button class="btn btn-success form-control block" ng-click="$ctrl.acceptProspectivieStd($ctrl.prospect.numDossier)">Accpter la candidature</button></div>
        <div class="col-md-4"><button class="btn btn-warning block form-control" ng-click="$ctrl.rejectProspectivieStd($ctrl.prospect.numDossier)">Notifier Dossier </button></div>
        <div class="col-md-4"><button class="btn btn-danger block form-control" ng-click="$ctrl.rejectProspectivieStd($ctrl.prospect.numDossier)">Rejeter la candidature</button></div>
    </div>
   
    
        
        
    <div layout='row'>

        

    </div>      
          
    <div layout-gt-sm="row">

        
        </div>



        </form>
  </md-content>

</div>
<p>&nbsp;</p>
              <!--tabs widget-->
                <div class="row" style='padding: 25px;' >
                    <ul class="nav nav-tabs">
                      <li class="active"><a href="#">Cursus académique</a></li>

                    </ul>

                                        <table class="table table-striped table-condensed">
                                            <thead>
                                                <tr class="bg-primary">
                                                    <th >Num</th>
                                                    <th >Année</th>
                                                    <th>Etablissement</th>
                                                    <th>Diplôme</th>
                                                    <th>Mention</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr ng-repeat="cur in $ctrl.cursus" >
                                                  <td >{{cpt+$index}}</td>
                                                  <td ng-bind="cur.annee"></td>
                                                  <td ng-bind="cur.etablissement"></td>
                                                  <td ng-bind="cur.diplome"></td>
                                                  <td ng-bind="cur.mention"></td>
                                                </tr>
                                                
                                            </tbody>
                                        </table>
                    
                 </div>
                <!--End tab-->
                
            </div>  
        </div>

