<link rel="stylesheet" href='js/datatables-plugins/dataTables.bootstrap.css'>


<style> 
.md-datepicker-calendar-pane{
z-index: 120000}

.md-select-menu-container {z-index: 120000;}



</style>
    

<div class="well" style="margin-left: -30px; margin-right: -30px;" >
    <div class="row">
        &nbsp;&nbsp;<span> <a href="#!/students">[Retour]</a></span>
    </div>
</div>


<div  ng-controller="printStdCtrl as $ctrl"  ng-cloak class="md-inline-form" style="margin: -30px; " ng-init="$ctrl.init()">


    <md-content layout-padding >
        <form   name="examForm">

   
        <div layout-gt-sm='row' >
            <md-input-container class="md-block" flex-gt-sm flex='40'>
                  <label>Classe:</label>
                  <md-autocomplete  md-search-text="$ctrl.searchClasse" 
                                   md-selected-item="$ctrl.selectedClasse"  
                                   md-items="item in $ctrl.query($ctrl.searchClasse)" 
                                   md-item-text="item.code" 
                                   md-min-length="0"
                                   placeholder="Faites de la classe" 
                                   md-selected-item-change="$ctrl.selectedItemChange(item)"
                                   md-input-name="classe"
                                   md-no-asterisk
                                   required>
                      <md-item-template>
                        <span md-highlight-text="$ctrl.searchClasse" md-highlight-flags="^i">{{item.code}}</span>

                      </md-item-template>
                      <md-not-found>
                        Aucun élément correspondant à "{{$ctrl.searchClasse}}" n'a été trouvé.

                      </md-not-found>
                </md-autocomplete>
                      <div ng-messages="examForm.classe.$error">
                          <div ng-message="required">Ce champ est obligatoire</div>
                      </div> 
            </md-input-container >
            <div flex-gt-sm="50" style="padding-top:25px;">
              <md-checkbox class='md-primary' ng-model="$ctrl.isUeActive" aria-label="Checkbox 1">
                Par unité d'enseignement?
              </md-checkbox>
            </div>
        </div>
            
            <div layout-gt-sm="row" layout-padding ng-show="$ctrl.isUeActive">
            
        <div layout-gt-sm='column' flex="35" >
        <md-input-container>
        <label>Semestre</label>
        <md-select name="semester" ng-model="$ctrl.selectedSem" ng-model-options="{trackBy: '$value.code'}" md-on-open="$ctrl.asignedSemToClasse($ctrl.selectedClasse.code);" ng-change="$ctrl.activateUeSelect(); $ctrl.loadUE($ctrl.selectedClasse,$ctrl.selectedSem.id)"
                    md-no-asterisk ng-required="$ctrl.isUeActive" >
            <md-option ng-disabled="true"><em>---Choix du Semestre---</em></md-option>
          <md-option ng-repeat="sem in $ctrl.semesters" ng-value="sem"  >
            {{sem.name}}
          </md-option>
        </md-select>
        <div class="errors" ng-messages="examForm.semester.$error">
          <div ng-message="required">Champ obligatoire</div>
        </div>
      </md-input-container>  
        </div> 
        <div layout-gt-sm='column' flex="65" >
        <md-input-container>
            <label>Unité d'enseignement</label>
            <md-select   name="ue" ng-disabled="!$ctrl.isActivatedUeSelect" ng-model="$ctrl.selectedUe"  
                       ng-model-options="{trackBy: '$value.id'}"  md-on-open="$ctrl.loadUE($ctrl.selectedClasse,$ctrl.selectedSem.id);" 
                       ng-change="$ctrl.loadStd();"  md-no-asterisk ng-required="$ctrl.isUeActive">
                <md-option ng-disabled="true" ng-selected="true" ng-value="{id:-1}"><em>Choisissez une UE</em></md-option>
              <md-option ng-repeat="ue in $ctrl.ues" ng-value="ue" >
                {{ue.code}}[{{ue.name}}]
              </md-option>
            </md-select>
            <div class="errors" ng-messages="examForm.ue.$error">
                <div ng-message="required">Champ obligatoire</div>
            </div>
        </md-input-container>  
        </div>
         </div>   
            <div class="pull-right" flex="15" >
                <button  ng-click="$ctrl.printStdList($ctrl.selectedClasse,$ctrl.selectedUe.id)" class="btn btn-danger" id='newacadyr'><i class="fa fa-refresh"></i>&nbsp;Générer</button>
            </div>
        
   

    </form>
  </md-content>
</div>


