
<link rel="stylesheet" type="text/css" href="css/datatables.bootstrap.css">
<link rel="stylesheel" type="text/css" href="css/buttons.datables.min.css">
<style>
  /*.table th{
  background-color:#337ab7;
 // color:white;
  text-align:left;
  vertical-align:center;
}*/
  
md-sidenav,
md-sidenav.md-locked-open-add-active,
md-sidenav.md-closed.md-locked-open-add-active,
md-sidenav.md-locked-open {
  width: 750px;
  min-width: 750px;
  max-width: 750px;
}

.navbar-top-links li a {
    padding: 2px;
    min-height: 10px;
}
</style>
<div class="row" ng-init="$ctrl.init() " >
                <div class="col-lg-12">
                    <h4 class="page-header">Liste des étudiants</h4>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-12">
                    <!-- Panneau des boutton -->
                    <div class="panel panel-default small">
                        <div class="panel-heading" style="margin-bottom: 15px;">

                            
                            <div >
                            <a ng-show="<?=($this->access('global.system.admin', null))||($this->access('manage.student', null))?true:false?>" href="" class="btn btn-danger" id='newacadyr'>Créer</a>
                            <button  ng-show="<?=($this->access('global.system.admin', null))||($this->access('manage.student', null))?true:false?>" ng-disabled="false"  ng-click="$ctrl.loadStdData()" class="btn btn-primary" id='newacadyr'><i class="fa fa-upload"></i>&nbsp;Import étudiants</button>
                            <button ng-show="<?=($this->access('global.system.admin', null))||($this->access('manage.student', null))?true:false?>" ng-click="$ctrl.loadStdPvData()" class="btn btn-primary" id='newacadyr'><i class="fa fa-file"></i>&nbsp;Import PV des résultats</button>
                            <button  ng-show="<?=($this->access('global.system.admin', null))||($this->access('manage.student', null))?true:false?>" ng-disabled="false"  ng-click="$ctrl.updateStdMpc()" class="btn btn-primary" id='newacadyr'><i class="fa fa-refresh"></i>&nbsp;MPC update</button>
                            <button ng-show="<?=($this->access('global.system.admin', null))||($this->access('manage.student', null))?true:false?>" ng-click="$ctrl.picturesGenerator()" class="btn btn-primary" id='newacadyr' title="Générer les photos"><i class="fa fa-picture-o"></i></button>
                            <button ng-show="<?=($this->access('global.system.admin', null))||($this->access('manage.student', null))?true:false?>" ng-click="$ctrl.studentsDataGenerator()" class="btn btn-primary" id='newacadyr' title="Exporter les donnée d'étudiants"><i class="fa fa-file-excel-o"></i></button>
                            <a  href="#!/registrationStat" class="btn btn-primary" ><i class="fa fa-bar-chart-o" title="Statistiques d'inscription"></i></a>
                            <button   ng-click="$ctrl.init()" class="btn btn-default" id='newacadyr'><i class="fa fa-refresh" title="actualiser le tableau"></i></button>
                            
                            
                            <a  href="#!/stdList" class="btn btn-default" ><i class="fa fa-print" title="Impression liste d'étudiants"></i></a>  
                            <button ng-show="<?=($this->access('global.system.admin', null))||($this->access('manage.student', null))?true:false?>" ng-click="$ctrl.clearDuplicates()" class="btn btn-default" id='newacadyr' title="Supprimer les doublons d'inscription académique"><i class="fa fa-trash"></i></button>
                            
          <button ng-click="toggleRight()"
            ng-hide="isOpenRight()"
            class="btn btn-success pull-right">
            <i class="fa fa-filter" title="Filtre"></i>
          </button>
        </div>
                        </div>
                        
                  <!--class="table table-striped table-bordered table-hover table-condensed datatable"-->
                            <table  datatable="ng" dt-options="$ctrl.dtOptions"  dt-column-defs="$ctrl.dtColumnDefs"  class="row-border hover table table-striped table-hover table-condensed datatable" style="table-layout: fixed">
                                <thead>
                                    <tr class="highlight">
                                        <th style="width: 8%" >Mat</th>
                                        <th style="width: 30%">Nom</th>
                                        <th style="width: 10%" >Classe</th>
                                        <th style="width: 15%">Date de Naiss</th>
                                        <th style="width: 15%">Date ins</th>
                                       <!-- <th>Solde cpte</th>-->
                                        <th style="width: 5%" >Contact</th>
                                        <th style="width: 15%">Statut</th>
                                   </tr>
                                </thead>
                                <tbody>
                                    <tr ng-repeat="std in $ctrl.students " ng-dblclick="$ctrl.redirect(std.id)"  style="cursor: pointer;">
                                        <td ng-bind="std.matricule"></td>
                                      <td ng-bind='std.nom+" "+std.prenom'></td>
                                      
                                      <td ng-bind="std.class"></td>
                                      <td ng-bind="$ctrl.formatDate(std.dateNaissance) | date:'dd/MM/yyyy'"></td>
                                      <td ng-bind="$ctrl.formatDate(std.dateInscription) | date:'dd/MM/yyyy H:mm:ss'"></td>
                                      <!--<td ng-bind="std.fees"></td>-->
                                      <td>
                                            <ul class="nav navbar-top-links navbar-right"  >
                                                <li class="dropdown"  >
                                                    <a class="dropdown-toggle small" data-toggle="dropdown" href="" >
                                                        <i class="fa fa-caret-down " ></i>
                                                    </a>
                                                    <ul class="dropdown-menu dropdown-messages xx-small">
                                                        <li>
                                                            <a href="#">
                                                                <div>
                                                                    <strong>Contact de l'étudiant:</strong>

                                                                </div>
                                                                <div>
                                                                    <span class=" text-muted">
                                                                        
                                                                        <i class="fa fa-phone">&nbsp;&nbsp;</i> <em>{{std.phone_number}}</em> <br>
                                                                        <i class="fa fa-envelope">&nbsp;&nbsp;</i> <em>{{std.email}}</em>
                                                                    </span>
                                                                </div>
                                                            </a>
                                                        </li>
                                                        <li class="divider"></li>
                                                        <li>
                                                            <a href="#">
                                                                <div>
                                                                    <strong>Contact du père:</strong>

                                                                </div>
                                                                <div>
                                                                    <span class=" text-muted">
                                                                        
                                                                        <i class="fa fa-phone">&nbsp;&nbsp;</i> <em>{{std.fatherPhoneNumber}}</em> <br>
                                                                        <i class="fa fa-envelope">&nbsp;&nbsp;</i> <em>{{std.fatherEmail}}</em>
                                                                    </span>
                                                                </div>
                                                                
                                                            </a>
                                                        </li>
                                                        <li class="divider"></li>
                                                        <li>
                                                            <a href="">
                                                                <div>
                                                                    <strong>Contact de la mère:</strong>

                                                                </div>
                                                                <div>
                                                                    <span class=" text-muted">
                                                                        
                                                                        <i class="fa fa-phone">&nbsp;&nbsp;</i> <em>{{std.phone_number}}</em> <br>
                                                                        <i class="fa fa-envelope">&nbsp;&nbsp;</i> <em>{{std.email}}</em>
                                                                    </span>
                                                                </div>
                                                            </a>
                                                        </li>
                                                        <li class="divider"></li>
                                                        <li>
                                                            <a href="">
                                                                <div>
                                                                    <strong>Contact du sponsor:</strong>

                                                                </div>
                                                                <div>
                                                                    <span class=" text-muted">
                                                                        
                                                                        <i class="fa fa-phone">&nbsp;&nbsp;</i> <em>{{std.sponsorPhoneNumber}}</em> <br>
                                                                        <i class="fa fa-envelope">&nbsp;&nbsp;</i> <em>{{std.sponsorEmail}}</em>
                                                                    </span>
                                                                </div>
                                                            </a>
                                                        </li>                                                        
                                                        <li class="divider"></li>
                                                        <li>
                                                            <a  href="" >
                                                                <div class="text-primary">
                                                                    <strong>Solde des frais de scolarité:</strong>

                                                                    <span class="pull-right text-muted">
                                                                        
                                                                        <em>{{std.fees}}</em>
                                                                        
                                                                    </span>
                                                                </div>
                                                            </a>
                                                        </li>
                                                    </ul>
                                                    <!-- /.dropdown-messages -->
                                                </li>

                                            </ul>
                                      </td>
                                      <td ng-bind="(std.status===0)?'Attente inscription':(std.status===2)?'Inscription  administrative':(std.status===3)?'Inscription academique':(std.status===1)?'Terminer':(std.status===4)?'Suspendue':(std.status===5)?'Abandon':(std.status===6)?'Exclu':(std.status===7)?'Diplomé':''" ng-class="{'zf-bg-warn': (std.status===2||std.status===3),'zf-bg-green': (std.status===1 || std.status===7) ,'zf-bg-grey': std.status===4,'zf-bg-black': (std.status===5 || std.status===6), 'zf-bg-red': std.status===0 }"></td>
                                    </tr>
                                </tbody>
                            </table>

                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>
            
<!--- SIDE NAV ------>            
<div  layout="column" style="height:500px;" ng-cloak>
    <section layout="row" flex>
        <md-sidenav layout-padding class="md-sidenav-right md-whiteframe-4dp" md-component-id="right" >
            <br /><br />
            <md-toolbar layout-padding class="md-theme-light">
              <h1 class="md-toolbar-tools">Sidenav Right</h1>
            </md-toolbar>
            <md-content  layout-padding>
               <form>
                    <div layout-gt-sm='row'  >
                        <div layout-gt-sm='column' flex="100" >
                            <md-input-container>
                                <label>Faculté</label>
                          
                                <md-select name="faculty" placeholder="Choisir la faculté" ng-model="filiere.fac_id" md-on-open="loadFaculties()"  required>
                                     <md-option ng-disabled="true"><em>---Choix de la faculté---</em></md-option>
                                    <md-option ng-value="faculty.id" ng-repeat="faculty in faculties">{{faculty.name}}</md-option>
                                </md-select>
                               
                                <div class="errors" ng-messages="examForm.semester.$error">
                                  <div ng-message="required">Champ obligatoire</div>
                                </div>
                            </md-input-container>  
                        </div> 
                    </div> 
                    <div layout-gt-sm='row'  >                    
                        <div layout-gt-sm='column' flex="100" >
                            <md-select name="faculty" placeholder="Choisir la filiere" ng-model="filiere.fac_id" md-on-open="loadFaculties()"  required>
                                 <md-option ng-disabled="true"><em>---Choix de la faculté---</em></md-option>
                                <md-option ng-value="filiere.id" ng-repeat="filiere in filieres">{{filiere.name}}</md-option>
                            </md-select>
                        </div>
                    </div>
                    <div layout-gt-sm='row'  >                    
                        <div layout-gt-sm='column' flex="100" >
                            <md-select name="faculty" placeholder="Choisir la spécialité" ng-model="filiere.fac_id" md-on-open="loadFaculties()"  required>
                                 <md-option ng-disabled="true"><em>---Choix de la spécialité---</em></md-option>
                                <md-option ng-value="filiere.id" ng-repeat="filiere in filieres">{{filiere.name}}</md-option>
                            </md-select>
                        </div>
                    </div> 
                    <div layout-gt-sm='row'  >
                        <div layout-gt-sm='column' flex="100" >
                            <md-input-container>
                                <label>Faculté</label>
                          
                                <md-select name="degree" placeholder="Choisir le programm de froamtion" ng-model="filiere.fac_id" md-on-open="loadFaculties()"  required>
                                     <md-option ng-disabled="true"><em>---Choix du programme de formation---</em></md-option>
                                    <md-option ng-value="degree.id" ng-repeat="degree in degrees">{{degree.name}}</md-option>
                                </md-select>
                               
                                <div class="errors" ng-messages="examForm.semester.$error">
                                  <div ng-message="required">Champ obligatoire</div>
                                </div>
                            </md-input-container>  
                        </div> 
                    </div>                    
                    <div layout-gt-sm='row'  >                    
                        <div layout-gt-sm='column' flex="100" >
                            <md-select name="faculty" placeholder="Choisir du cycle" ng-model="filiere.fac_id" md-on-open="loadFaculties()"  required>
                                 <md-option ng-disabled="true"><em>---Choix du cycle---</em></md-option>
                                <md-option ng-value="filiere.id" >1</md-option>
                                <md-option ng-value="filiere.id" >2</md-option>
                                <md-option ng-value="filiere.id" >3</md-option>
                            </md-select>
                        </div>
                    </div>
                </form>
                
                <md-button ng-click="close()" class="md-primary">
                  Close Sidenav Right
                </md-button>
         </md-content>

                    </md-sidenav> 
                </section>
                </div>