<?= $this->doctype() ?>

<html lang="fr" >
    <head>
        <meta http-equiv="Content-Type" content="text/html"; charset="utf-8">
       
        <?= $this->headTitle('UdMAcademy Application')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink()
            ->prependStylesheet($this->basePath('css/style.css'))
            //
        ->prependStylesheet($this->basePath('css/angular-toastr.min.css'))
        ->prependStylesheet($this->basePath('css/loading-bar.css'))
        ->prependStylesheet($this->basePath('css/sb-admin-2.css'))
       // ->prependStylesheet($this->basePath('css/buttons.datables.min.css'))
        //->prependStylesheet($this->basePath('css/jquery.dataTables.min.css'))
        
        //->prependStylesheet($this->basePath('css/datatables.bootstrap.css'))
        
        ->prependStylesheet($this->basePath('js/datatables-responsive/dataTables.responsive.css'))
        ->prependStylesheet($this->basePath('js/datatables-plugins/dataTables.bootstrap.css'))
       // ->prependStylesheet($this->basePath('js/angular-dataTable/plugins/bootstrap/datatables.bootstrap.min.css'))
        ->prependStylesheet($this->basePath('js/metisMenu/metisMenu.min.css'))
        //->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ->prependStylesheet($this->basePath('bower_components/angular-animate/angular-animate.min.css'))
        ->prependStylesheet($this->basePath('bower_components/angular-material/angular-material.min.css'))
           // ->prependStylesheet($this->basePath('../vendor/onokumus/metismenu/dist/metisMenu.min.css'))
        
        
        //->prependStylesheet($this->basePath('js/morris.js-0.5.1/morris.css'))
        ->prependStylesheet($this->basePath('css/font-awesome/css/font-awesome.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
        ->prependFile($this->basePath('js/moment.min.js'))
        ->prependFile($this->basePath('js/morris.js-0.5.1/morris.min.js'))
        ->prependFile($this->basePath('js/raphael-js/raphaeljs.js'))
       //
        
        ->prependFile($this->basePath('js/datatables/js/buttons/buttons.colVis.min.js'))
        ->prependFile($this->basePath('js/datatables/js/buttons/buttons.flash.min.js'))
        ->prependFile($this->basePath('js/datatables/js/buttons/buttons.html5.min.js'))
        ->prependFile($this->basePath('js/datatables/js/buttons/buttons.print.min.js'))
        ->prependFile($this->basePath('js/datatables/js/buttons/dataTables.buttons.min.js'))
        ->prependFile($this->basePath('js/datatables/js/dataTables.fixedHeader.js'))
        ->prependFile($this->basePath('js/datatables/js/jquery.dataTables.js'))
        ->prependFile($this->basePath('js/angular-dataTable/plugins/fixedheader/angular-datatables.fixedheader.min.js'))
        ->prependFile($this->basePath('js/angular-dataTable/plugins/buttons/angular-datatables.buttons.min.js'))
        ->prependFile($this->basePath('js/angular-dataTable/angular-datatables.min.js'))
        ->prependFile($this->basePath('js/angular-dataTable/angular-datatables.min.js'))
        ->prependFile($this->basePath('js/datatables-responsive/dataTables.responsive.js'))
        ->prependFile($this->basePath('js/datatables/js/jquery.dataTables.min.js'))
        
        ->prependFile($this->basePath('js/metisMenu/metisMenu.min.js'))
        ->prependFile($this->basePath('js/angular-toastr.min.js'))
        ->prependFile($this->basePath('js/sb-admin-2.js'))
        ->prependFile($this->basePath('js/ui.utils.js'))
        ->prependFile($this->basePath('bower_components/angular-material/angular-material.min.js'))
        ->prependFile($this->basePath('bower_components/angular-messages/angular-messages.min.js'))
        ->prependFile($this->basePath('bower_components/angular-animate/angular-animate.min.js'))
        ->prependFile($this->basePath('bower_components/angular-aria/angular-aria.min.js'))
        
               
            
          ->prependFile($this->basePath('js/loading-bar.js'))   
         ->prependFile($this->basePath('js/my_js/globalconfig/angulartest.js')) 
        ->prependFile($this->basePath('js/ui-bootstrap-tpls-2.5.0.min.js'))
        ->prependFile($this->basePath('js/angular-animate.js'))
        ->prependFile($this->basePath('js/angular-route.js'))
           ->prependFile($this->basePath('js/angular-1.6.7/angular.js'))
        ->prependFile($this->basePath('js/bootstrap.min.js'))
        ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
        
           
        //->prependFile($this->basePath('../vendor/onokumus/metismenu/dist/metisMenu.min.js'))
        

        ?>
    
    <script src="js/app/usersandgroups/users.module.js"></script>
    <script src="js/app/usersandgroups/users.component.js"></script>     
    <script src="js/app/usersandgroups/new.user.component.js"></script>  
    <script src="js/app/usersandgroups/groups.component.js"></script> 
    <script src="js/app/usersandgroups/new.group.component.js"></script> 
    <script src="js/app/exam/exam.module.js"></script>
    <script src="js/app/exam/exam.component.js"></script>  
    <script src="js/app/exam/suivi.parcourt.component.js"></script>
    <script src="js/app/exam/new.exam.component.js"></script>
    <script src="js/app/exam/calcul.notes.component.js"></script>
    <script src="js/app/exam/calcul.mps.component.js"></script>
    <script src="js/app/exam/grade.component.js"></script> 
    <script src="js/app/exam/new.grade.component.js"></script>
    <script src="js/app/dashboard/dashboard.module.js"></script>
    <script src="js/app/dashboard/dashboard.component.js"></script>
    <script src="js/app/payment/payment.module.js"></script>
    <script src="js/app/payment/payment.component.js"></script>
    <script src="js/app/payment/paymentdetails.component.js"></script>
    <script src="js/app/payment/moratorium/moratorium.component.js"></script>
    <script src="js/app/payment/moratorium/newmoratorium.component.js"></script>
    <script src="js/app/faculty/faculty.module.js"></script>
    <script src="js/app/faculty/faculty.component.js"></script>
    <script src="js/app/filiere/filiere.module.js"></script>
    <script src="js/app/filiere/filiere.component.js"></script>
    <script src="js/app/degree/degree.module.js"></script>
    <script src="js/app/degree/degree.component.js"></script>
    <script src="js/app/degree/new.degree.component.js"></script>
    <script src="js/app/classes/classes.module.js"></script>
    <script src="js/app/classes/classes.component.js"></script>
    <script src="js/app/classes/new.classe.component.js"></script>
    <script src="js/app/teachingunit/teachingunit.module.js"></script>
    <script src="js/app/teachingunit/teachingunit.component.js"></script>
    <script src="js/app/teachingunit/new.teachingunit.component.js"></script> 
    <script src="js/app/student/student.module.js"></script>
    <script src="js/app/student/student.component.js"></script>
    <script src="js/app/student/admission.component.js"></script>
    <script src="js/app/student/subjectregistration.component.js"></script>
    <script src="js/app/app.js"></script>
  <script src="js/app/acadyr-list/acadyr-list.js"></script>
  <script src="js/app/acadyr/acadyr.js"></script>
  <script src="js/app/acadyr/teachingunit.component.js"></script>
  <script src="js/app/acadyr/newteachingunit.component.js"></script>
  <script src="js/app/components/version/version.js"></script>
  <script src="js/app/components/version/version-directive.js"></script>
  <script src="js/app/components/version/interpolate-filter.js"></script>
    </head>
<body ng-app="myApp" ng-cloak>
<div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand " href="index"><span class="zf-green">Agenla Academy</span></a>
            </div>
            <!-- /.navbar-header -->

            <ul class="nav navbar-top-links navbar-right">
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-envelope fa-fw"></i> <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-messages">
                        <li>
                            <a href="#">
                                <div>
                                    <strong>John Smith</strong>
                                    <span class="pull-right text-muted">
                                        <em>Yesterday</em>
                                    </span>
                                </div>
                                <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <strong>John Smith</strong>
                                    <span class="pull-right text-muted">
                                        <em>Yesterday</em>
                                    </span>
                                </div>
                                <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <strong>John Smith</strong>
                                    <span class="pull-right text-muted">
                                        <em>Yesterday</em>
                                    </span>
                                </div>
                                <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a class="text-center" href="#">
                                <strong>Read All Messages</strong>
                                <i class="fa fa-angle-right"></i>
                            </a>
                        </li>
                    </ul>
                    <!-- /.dropdown-messages -->
                </li>
                <!-- /.dropdown -->
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-tasks fa-fw"></i> <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-tasks">
                        <li>
                            <a href="#">
                                <div>
                                    <p>
                                        <strong>Task 1</strong>
                                        <span class="pull-right text-muted">40% Complete</span>
                                    </p>
                                    <div class="progress progress-striped active">
                                        <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%">
                                            <span class="sr-only">40% Complete (success)</span>
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <p>
                                        <strong>Task 2</strong>
                                        <span class="pull-right text-muted">20% Complete</span>
                                    </p>
                                    <div class="progress progress-striped active">
                                        <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100" style="width: 20%">
                                            <span class="sr-only">20% Complete</span>
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <p>
                                        <strong>Task 3</strong>
                                        <span class="pull-right text-muted">60% Complete</span>
                                    </p>
                                    <div class="progress progress-striped active">
                                        <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%">
                                            <span class="sr-only">60% Complete (warning)</span>
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <p>
                                        <strong>Task 4</strong>
                                        <span class="pull-right text-muted">80% Complete</span>
                                    </p>
                                    <div class="progress progress-striped active">
                                        <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: 80%">
                                            <span class="sr-only">80% Complete (danger)</span>
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a class="text-center" href="#">
                                <strong>See All Tasks</strong>
                                <i class="fa fa-angle-right"></i>
                            </a>
                        </li>
                    </ul>
                    <!-- /.dropdown-tasks -->
                </li>
                <!-- /.dropdown -->
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-bell fa-fw"></i> <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-alerts">
                        <li>
                            <a href="#">
                                <div>
                                    <i class="fa fa-comment fa-fw"></i> New Comment
                                    <span class="pull-right text-muted small">4 minutes ago</span>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="">
                                <div>
                                    <i class="fa fa-twitter fa-fw"></i> 3 New Followers
                                    <span class="pull-right text-muted small">12 minutes ago</span>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <i class="fa fa-envelope fa-fw"></i> Message Sent
                                    <span class="pull-right text-muted small">4 minutes ago</span>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="">
                                <div>
                                    <i class="fa fa-tasks fa-fw"></i> New Task
                                    <span class="pull-right text-muted small">4 minutes ago</span>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="">
                                <div>
                                    <i class="fa fa-upload fa-fw"></i> Server Rebooted
                                    <span class="pull-right text-muted small">4 minutes ago</span>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a class="text-center" href="">
                                <strong>See All Alerts</strong>
                                <i class="fa fa-angle-right"></i>
                            </a>
                        </li>
                    </ul>
                    <!-- /.dropdown-alerts -->
                </li>
                <!-- /.dropdown -->
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href=""> 
                        <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i> <?=$this->identity()?> 
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li><a href="#"><i class="fa fa-user fa-fw"></i> Profil utilisateur</a>
                        </li>
                        <li><a href="#"><i class="fa fa-gear fa-fw"></i> Paramètres</a>
                        </li>
                        <li class="divider"></li>
                        <li><a href="logout"><i class="fa fa-sign-out fa-fw"></i>Se déconnecter</a>
                        </li>
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
                <!-- /.dropdown -->
            </ul>
            <!-- /.navbar-top-links -->

            <div   class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li class="sidebar-search">
                            <div class="input-group custom-search-form">
                                <input type="text" class="form-control" placeholder="Search...">
                                <span class="input-group-btn">
                                <button class="btn btn-default" type="button">
                                    <i class="fa fa-search"></i>
                                </button>
                            </span>
                            </div>
                            <!-- /input-group -->
                        </li>
                        <li>
                            <a href="home"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-graduation-cap fa-fw"></i> Etudiants<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="#!/admission">Admission</a>
                                </li>
                                <li>
                                    <a href="#!/students">Inscription/Réinscription</a>
                                </li>
                                <li>
                                    <a href="">Diplomés</a>
                                </li>
                                <li>
                                    <a href="">Parents</a>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                        <li>
                            <a href=""><i class="fa fa-credit-card fa-fw"></i> Paiements<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li ng-show="<?=(($this->access('global.system.admin', ['user'=>$this->currentuser($this->identity())])==1)||($this->access('payment.manager', ['user'=>$this->currentuser($this->identity())])==1))?true:false?>">
                                    <a href="#!/payments">Gérer les créances</a>
                                </li>
                                <li ng-show="<?=(($this->access('global.system.admin', ['user'=>$this->currentuser($this->identity())])==1)||($this->access('payment.manager', ['user'=>$this->currentuser($this->identity())])==1))?true:false?>">
                                    <a href="#!/newStdRegistrationFeesMgt">Frais inscription nouveaux</a>
                                </li>                                
                                <li>
                                    <a href="">Dotation des frais</a>
                                </li>
                                <li>
                                    <a href="#!/moratorium">Moratoires</a>
                                </li>
                                <li>
                                    <a href="">Alerte SMS</a>
                                </li>
                                <li>
                                    <a href="">Ètats</a>
                                </li>
                            </ul>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-- fa-fw"></i> Enseignants</a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-envelope fa-fw"></i> Evaluations<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="#!/examlist">Gérer les évaluations</a>
                                </li>
                                <li>
                                    <a href="#!/calculnotes">Calcul des notes consolidées</a>
                                </li>
                                <li>
                                    <a href="#!/calculmps">Calcul moyenne pondérée</a>
                                </li>
                                <li>
                                    <a href="#!/suiviparcourt">Suivi parcourt étudiant</a>
                                </li>

                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-wrench fa-fw"></i> Etats et rapports<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="">Gérer les examens</a>
                                </li>
                              
                             </ul>
                            <!-- /.nav-second-level -->
                        </li>
                        <li>
                            <a href="#!/assignedteachingunit"><i class="fa fa-cogs">&nbsp;</i>Grilles d'enseignement</a>
                        </li>

                        <li ng-show="<?=($this->access('global.system.admin', ['user'=>$this->currentuser($this->identity())])==1)?true:false?>">
                            <a href="#"><i class="fa fas fa-cogs"></i> Configurations<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="#"><i class="fa fas fa-calendar-o"></i>&nbsp;Année académique<span class="fa arrow"></span></a>
                                        <ul class="nav nav-third-level">
                                            <li>
                                                <a href="#!/acadyr-list">Gérer année académique</a>
                                            </li>

                                            <li>
                                                <a href="#!/assignedteachingunit">Affecter les UEs</a>
                                            </li>

                                        </ul>
                                        <!-- /.nav-second-level -->
                                </li>
                                <li>
                                    <a href="#!/faculty">Facultés</a>
                                </li>
                                <li>
                                    <a href="#!/filiere">Filières</a>
                                </li>
                                <li>
                                    <a href="#!/degree">Diplômes</a>
                                </li>
                                <li>
                                    <a href="#!/classes">Niveaux d'etudes</a>
                                </li>
                                <li>
                                    <a href="#!/teachingunit">Unités d'enseignement</a>
                                </li>
                                <li>
                                    <a href="#!/gradeconfig">Configuration des grades</a>
                                </li>
                                <li>
                                    <a href="#">Frais de scolarité <span class="fa arrow"></span></a>
                                    <ul class="nav nav-third-level">
                                        <li>
                                            <a href="#">Gérer les frais de scolarité</a>
                                        </li>
                                        <li>
                                            <a href="#">Structure de frais</a>
                                        </li>
                                        <li>
                                            <a href="#">Third Level Item</a>
                                        </li>
                                        <li>
                                            <a href="#">Third Level Item</a>
                                        </li>
                                    </ul>
                                    <!-- /.nav-third-level -->
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                        <li ng-show="<?=($this->access('global.system.admin', ['user'=>$this->currentuser($this->identity())])==1)?true:false?>">
                            <a href="#"><i class="fa fa-users fa-fw"></i> Gestion des utilisaterus<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="#!/usermanagement">Utilisateurs</a>
                                </li>
                                <li>
                                    <a href="#!/groupmanagement">Groupe</a>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>

        <div id="page-wrapper">
            
            <div ng-view id="component-tpl"></div>
            
            <?php //$this->content ?>

         </div>
        </div>
        <!-- /#page-wrapper -->
        <div class="container" style="margin-left: auto; margin-right: auto;">           
            <hr>
            <footer>
                <p>&copy; 2018 - <?= date('Y') ?> by Service Informatique UdM.</p>
            </footer>

        <?= $this->inlineScript() ?>
  
    </div>
    <!-- /#wrapper -->

    </body>          
        
     
  

</html>
