<style>
.mat-datepicker-content .mat-calendar
{ 
     zoom: 0.85;
}
</style>

<div style="margin-top: 50px; ">
   <br /> <br /><br /><br /><br />
   <div class="alert alert-success text-center" ><span style="font-size: 1.5em;">Vos informations ont été enrégistrées avec succès. votre numéro d'admission est: <h2> <?=$this->numDossier?></h2>
         <a href="newstudentlogin">cliquez ici</a> pour continuer</span> .
    
    </div>

<br /> <br /><br /><br /><br />
  
    
</div>

