
<link rel="stylesheet" type="text/css" href="css/datatables.bootstrap.css">
<link rel="stylesheel" type="text/css" href="css/buttons.datables.min.css">
<style>
  /*.table th{
  background-color:#337ab7;
 // color:white;
  text-align:left;
  vertical-align:center;
}*/
  

</style>
<div class="row" ng-init="$ctrl.init() ">
                <div class="col-lg-12">
                    <h4 class="page-header">Liste des utilisateurs</h4>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-12">
                    <!-- Panneau des boutton -->
                    <div class="panel panel-default small">
                        <div class="panel-heading" style="margin-bottom: 15px;">

                            <a href="#!/newuser" class="btn btn-danger" id='newacadyr'>Créer</a>
                                                       
                        </div>
                        
                  <!--class="table table-striped table-bordered table-hover table-condensed datatable"-->
                            <table  datatable="ng" dt-options="$ctrl.dtOptions"  dt-column-defs="$ctrl.dtColumnDefs"  class="row-border hover table table-striped table-hover table-condensed datatable" style="table-layout: fixed">
                                <thead>
                                    <tr class="highlight ">
                                        <th style="width:5%">#</th>
                                        <th >Nom</th>
                                        <th>Email</th>
                                       
                                        <th>Date  création</th>
                                        <th>Dernière connexion</th>
                                        <th>Statut</th>
                                   </tr>
                                </thead>
                                <tbody>
                                    <tr ng-repeat="user in $ctrl.users " ng-dblclick="$ctrl.redirect(user.id)" style="cursor: pointer;" >
                                      <td ng-bind="user.num"></td>
                                      <td ng-bind="user.fullName"></td>
                                      <td ng-bind="user.email"></td>

                                      <td ng-bind="$ctrl.formatDate(user.dateCreated.date) | date:'dd/MM/yyyy HH:mm:ss'"></td>
                                      <td class="bg-info text-danger" ng-bind="$ctrl.formatDate(user.lastConnectedDate.date) | date:'dd/MM/yyyy HH:mm:ss'"></td>
                                      <td style="font-size: 16px;" ng-class="user.connectedStatus?'bg-warning text-success  ':'bg-danger text-info'" ><i ng-class="user.connectedStatus?'glyphicon glyphicon-user':'glyphicon glyphicon-remove-circle'"></i>{{user.connectedStatus?" Connecté":" Déconnecté"}}</td>
          <i class=""></i>                    
                                    </tr>
                                </tbody>
                            </table>

                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>

            