
<style> 
.md-datepicker-calendar-pane{
z-index: 120000}

.md-select-menu-container {z-index: 120000;}



</style>
    
    <form  ng-submit=""  name="userForm" validate>
        <div class="well" style="margin-left: -30px; margin-right: -30px;" ng-init="$ctrl.init()">

            <div class="row">
                <div class='col-lg-2'>
                    <button  type="submit" class="btn btn-danger" ng-click="$ctrl.updateGroup()" ng-show="$ctrl.isUpdate" ng-disabled="classForm.$invalid">Modifier</button>
                    <button  type="button" ng-click="$ctrl.addGroup()" class="btn btn-danger" ng-show="!$ctrl.isUpdate" ng-disabled="userForm.$invalid">Enrégistrer</button>
                    <span> <a href="#!/groupmanagement">Retour</a></span>
                </div>
                <div class="col-lg-4"></div>
                <div class="col-lg-2">
                    
                    <button  type="button" ng-show="$ctrl.isUpdate" ng-click="$ctrl.deleteGroup()" ng-disabled="classForm.$invalid" class="btn btn-default">Supprimer</button>
                    
                    
                </div>
            </div>
        </div>
        <div class="form-view-main">
            <div class="form-view">



  
<div  layout="column" ng-cloak class="md-inline-form">


    <md-content layout-padding >

        
    <div layout='row'>
        <input name="id" ng-model="$ctrl.group.id" hidden />
    <md-input-container class="md-block" flex='100' >
    <label>Nom:</label>          
        <input  name="nom"  ng-model="$ctrl.group.name"  md-no-asterisk  ng-required>
              <div ng-messages="userForm.nom.$error">
                  <div ng-message="required">Ce champ est obligatoire</div>
              </div> 
    </md-input-container>
   
        
    <md-input-container class="md-block" flex='100' >
        <label>Description:</label>          
        <input name="description"  ng-model="$ctrl.group.description" md-no-asterisk  required >
                <div ng-messages="userForm.description.$error">
                  <div ng-message="required">ce champ est obligatoire</div>

              </div>
    </md-input-container>
    </div>      


        
        <div layout-gt-sm='row' >
        <div class = "col-lg-12">

           
        </div>

         
        <div class = "col-lg-12"  style="background-color: #dfe4ea;" >
            <div class="row">  
            <div class="col-md-10"  style="margin-top:25px;">

            <md-input-container class="column md-block" flex-gt-sm>
            <label>liste des permissions:</label>
            <br />
            <table class="border table   table-condensed " style=" background-color: #dfe4ea; color: #0c2461;">
                <thead>
                    <tr class="bg-primary">
                        <th style="width:5%">#</th>
                        <th >permission</th>
                        <th>Description</th>

                   </tr>
                </thead>
                <tr ng-repeat="item in $ctrl.permissions">
                    <td>
                        <md-checkbox ng-checked="$ctrl.exists(item,$ctrl.selected)" ng-click="$ctrl.toggle(item,$ctrl.selected)"
                          ng-model="item.status"
                        ng-true-value="1"
                        ng-false-value="0">
                      </md-checkbox>
                    </td>
                    <td ng-bind="item.name "></td>
                    <td ng-bind="item.description "></td>
                </tr>
            </table>
            </md-input-container>

            </div>

        </div>
           
            <div class="col-md-9">
            <table>
               
                <tbody>
                    <tr ng-repeat="classe in $ctrl.classes">
                        <td class="text-primary" ng-bind="classe.code"></td>&nbsp;<td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td>
                        <td ><button class="btn btn-default" ng-click="$ctrl.removeClasseTouser(classe.id,$ctrl.user.id)"><i class="fa fa-trash"></i></button></td>
                    </tr>
                    
                </tbody>
            </table>
            </div>

           
        </div>            
        
        </div>

        </form>
  </md-content>

</div>
<p>&nbsp;</p>
              <!--tabs widget-->
              <!--  <div class="row" >
                    <ul class="nav nav-tabs">
                      <li class="active"><a href="#">Cyles de formation</a></li>

                    </ul>

                                        <table class="table table-striped">
                                            <thead>
                                                <tr class="bg-warning">
                                                    <th style='width:30%;'>Code</th>
                                                    <th>Nom</th>
                                                    <th>Durée</th>

                                                    <th style='width:12%;'></th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr ng-repeat="cycle in cycles" >
                                                  <td ng-bind="cycle.code"></td>
                                                  <td ng-bind="cycle.name"></td>
                                                  <td ng-bind="cycle.duration"></td>
                                                  <td>
                                                      
                                                      <button type="button" ng-click="showCurriculum(cycle)" class="btn btn-default btn"><i class="fa fa-edit"></i></button>
                                                      <button  type="button" ng-click="deleteCycle(cycle)" class="btn btn-default btn" ><i class="fa fa-trash-o"></i></button></td></span>
                                                    
                                                  </td>
                                                </tr>
                                            </tbody>
                                        </table>
                        <a class="btn btn-primary" ng-click="$ctrl.addCurriculum()">Ajouter un cycle</a>

                 </div>
              -->
                <!--End tab-->
                
            </div>  
        </div>

