
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<?php
//============================================================+
// File name   : example_048.php
// Begin       : 2009-03-20
// Last Update : 2013-05-14
//
// Description : Example 048 for TCPDF class
//               HTML tables and table headers
//
// Author: Nicola Asuni
//
// (c) Copyright:
//               Nicola Asuni
//               Tecnick.com LTD
//               www.tecnick.com
//               info@tecnick.com
//============================================================+

/**
 * Creates an example PDF TEST document using TCPDF
 * @package com.tecnick.tcpdf
 * @abstract TCPDF - Example: HTML tables and table headers
 * @author Nicola Asuni
 * @since 2009-03-20
 */

class PDF extends TCPDF {
    //
    // This class extends FPDF so we may customize the header and footer
    // of the PDFs that are created
    //
   //Page header
    public $faculty;
    public $facultyCode;
    public $filiere;
    public $personOnChargeOfFaculty;
    
    public function Header() {
        // Logo
        
        $headertext='';
        $image_file = K_PATH_IMAGES.'logo.gif';
        $this->Image($image_file,'', '', PDF_HEADER_LOGO_WIDTH,'', 'GIF', '', 'T', false, 300, 'L', false, false, 0, false, false, false);
        // Set font
        $this->SetFont('coopbl', '', 10);
        $this->SetX(15);
        $this->SetY(10);
        $this->SetX(-90);
        $this->Cell(75,PDF_MARGIN_LEFT, 'Institut Supérieure Agenla Academy ', 0, false, 'C', 0, '', 0, false, 'M', 'M');
        $this->SetY(15);
        $this->SetFont('arialce', '', 10);
        $this->SetX(-90);
        $this->Cell(75,25,$this->faculty, 0, false, 'C', 0, '', 0, false, 'M', 'M');
        $this->SetY(20);
        $this->SetX(-90);
        $this->Cell(75,25,$this->filiere, 0, false, 'C', 0, '', 0, false, 'M', 'M');
        // Title
        $this->SetY(25);
        $html ='<hr>';
        $this->writeHTML($html, true, false, true, false, '');
        
    }
    function Footer() {
        $footertext='Report generated with UdMAcademy 2.0 By WTECH (' . date("d-m-Y H:i") . ')';
        // Position at 15 mm from bottom
        $this->SetY(-15);
        $this->SetFont('helvetica', 'I', 5);
        // Page number
         
       // $this->Cell(0, 5, 'Page '.$this->getAliasNumPage().'/'.$this->getAliasNbPages(), 0, false, 'C', 0, '', 0, false, 'T', 'M');
        $html ='<hr>';
        $this->writeHTML($html, true, false, true, false, '');
        //$this->writeHTML($footertext, false, true, false, true);
        $this->Cell(0, 5, $footertext, 0, false, 'C', 0, '', 0, false, 'T', 'M');
        
        $this->SetY(-20);
        $this->SetFont('freesans','I',8);
        $this->SetTextColor(34,68,136);
        //$this->Cell(0, 5, 'BP 208-Bangangté Cameroun  Tél. : (237) 243 02 51 41  E-mail : info@udm.aed-cm.org    Site web :  www.udm.aed-cm.org', 0, false, 'C', 0, '', 0, false, 'T', 'M');
        $this->SetTextColor(0,0,0);
        $this->SetFont('garamond','I',10);
        $this->SetY(-75);
        $this->Cell(0, 5, 'Bangangté, le ________________________ ', 0, false, 'C', 0, '', 0, false, 'M', 'M');
        $this->SetFont('garamond','',10);
        $this->SetY(-50);
        if($this->facultyCode=="IEASSM")
            $this->Cell(0, 5, 'Le Directeur', 0, false, 'C', 0, '', 0, false, 'M', 'M');
        else $this->Cell(0, 5, 'Le Doyen/Le Vice Doyen', 0, false, 'C', 0, '', 0, false, 'M', 'M');
        $this->SetY(-25);
        //$this->Cell(0, 5, $this->personOnChargeOfFaculty, 0, false, 'C', 0, '', 0, false, 'M', 'M');        
    }  // end of the Footer function
}

// create new PDF document
$pdf = new PDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);

// set document information
$pdf->SetCreator(PDF_CREATOR);
$pdf->SetAuthor('Parfait Pascal Wangun');
$pdf->SetTitle('Universté des Montagnes');
$pdf->SetSubject('TCPDF Tutorial');
$pdf->SetKeywords('TCPDF, PDF, pv , test, guide');


// set default header data
$image_file = "logo.gif";
$pdf->faculty = $this->faculty;
$pdf->facultyCode = $this->facultyCode;
$pdf->personOnChargeOfFaculty = $this->personOnChargeOfFaculty;
$pdf->filiere = $this->filiere;

//$pdf->SetHeaderData("logo.gif", PDF_HEADER_LOGO_WIDTH, 'Universté des Montagnes', $this->faculty."\n".$this->filiere."\n".$this->acadYr."\n".$this->semestre);
//$pdf->Image($image_file, 10, 10, 15, '', 'JPG', '', 'T', false, 300, 'R', false, false, 0,     false, false, false);
// set header and footer fonts

$pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
$pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));

// set default monospaced font
$pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);

// set margins
$pdf->SetMargins(PDF_MARGIN_LEFT, PDF_MARGIN_TOP+5, PDF_MARGIN_RIGHT);
$pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
$pdf->SetFooterMargin(PDF_MARGIN_FOOTER);

// set auto page breaks
$pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM+5);

// set image scale factor
$pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);

// set some language-dependent strings (optional)
if (@file_exists(dirname(__FILE__).'/lang/eng.php')) {
    require_once(dirname(__FILE__).'/lang/eng.php');
    $pdf->setLanguageArray($l);
}

// ---------------------------------------------------------
// add a page
foreach($this->students as $student)
{
$pdf->startPageGroup(); 
$pdf->AddPage('P','A4');

$pdf->setFont("coopbl",'',16);    
$stud = $student["student"];
$html = <<<EOD
       
    <div style="width:100%; text-align:center; background-color:#8FBC8F; color:#191970;">CERTIFICAT DE SCOLARITE <br>
        <span style="font-family:helvetica; font-size: 18px; font-style:I; color: #DC143C;" >SCHOOL ATTENDANCE CERTIFICATE</span>
    </div>
EOD;

$pdf->writeHTML($html, true, false,true, false, 'c'); 

$pdf->SetFont('arialunicodems', '',12);

$text = '    <table  >
        <tr><td colspan="4" style=" text-align:center; ">A qui de droit<br> 
        <span style=" margin: 0px;  font-family:garamond; font-size: 12px;"><i>To whom it may concern</i></span><br>
        Num Ref:'. $student["referenceNumber"].'</td></tr>
        
        <tr><td colspan="4"><br></td></tr>
        
        <tr><td colspan="4">Le doyen de:   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'.$this->faculty.'<br>
        <span style=" margin: 0px;  font-family:garamond; font-size: 12px;"><i>The Dean of the: 
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'.$this->faculty.'</i></span></td>
        </tr>
        
        <tr style=" margin:0px;"><td colspan="2">certifie que l\'étudiant(e): <br>
        <span style=" margin: 0px;  font-family:garamond; font-size: 12px;"><i>certifies that the student"</i></span></td>
        <td colspan="2"><span style=" margin: 0px;  font-family:garamond; font-size: 12px;"> '.$student["nom"].' '.$student["prenom"].'</span></td></tr>

        <tr style=" margin:0px;"><td colspan="2">matricule n° : <br>
        <span style=" margin: 0px;  font-family:garamond; font-size: 12px;"><i>student ID: </i></span></td>
        <td colspan="2"><span style=" margin: 0px;  font-family:garamond; font-size: 12px;"> '.$student["matricule"].'</span></td></tr>
            
        <tr style=" margin:0px;"><td colspan="2">né(e) le : <br>
        <span style=" margin: 0px;  font-family:garamond; font-size: 12px;"><i>born on: </i></span></td>
        <td colspan="2"><span style=" margin: 0px;  font-family:garamond; font-size: 12px;"> '.$student["dateOfBirth"].'</span></td></tr>
            
        <tr style=" margin:0px;"><td colspan="2">à : <br>
        <span style=" margin: 0px;  font-family:garamond; font-size: 12px;"><i>at: </i></span></td>
        <td colspan="2"><span style=" margin: 0px;  font-family:garamond; font-size: 12px;"> '.$student["bornAt"].'</span></td></tr>
        
        <tr style=" margin:0px;"><td colspan="2">est inscrit pour l\'année académique : <br>
        <span style=" margin: 0px;  font-family:garamond; font-size: 12px;"><i>is registered for the academic year: </i></span></td>
        <td colspan="2"><span style=" margin: 0px;  font-family:garamond; font-size: 12px;"> '.$this->acadYrCode.'</span></td></tr>
            
        <tr style=" margin:0px;"><td >au niveau : <br>
        <span style=" margin: 0px;  font-family:garamond; font-size: 12px;"><i>at study level: </i></span></td>
        <td colspan=><span > '.$this->niveauEtude.'</span></td>
        <td colspan="3">de :  '.$this->diplome.' <br>
        <span style=" margin: 0px;  font-family:garamond; font-size: 12px;"><i>of: </i></span></td></tr>
            
        <tr style=" margin:0px;"><td >de la filière : <br>
        <span colspan="2" style=" margin: 0px;  font-family:garamond; font-size: 12px;"><i>in the field of study: </i></span></td>
        <td colspan="2"><span style=" margin: 0px;  font-family:garamond; font-size: 12px;"> '.$this->filiere.'</span></td>
      </tr>
      
        <tr style=" margin:0px;"><td >spécialité: <br>
        <span style=" margin: 0px;  font-family:garamond; font-size: 12px;"><i>speciality: </i></span></td>
        <td colspan=><span style=" margin: 0px;  font-family:garamond; font-size: 12px;"> </span></td>
        <td >Option: <br>
        <span style=" margin: 0px;  font-family:garamond; font-size: 12px;"><i>option: </i></span></td>
        <td colspan=><span style=" margin: 0px;  font-family:garamond; font-size: 12px;"> '.$this->option.'</span></td></tr>
            

        
        <tr><td colspan="4" >en foi de quoi le présent certificat lui est délivré pour servir et valoir ce que de droit.  <br> 
        <span style=" margin: 0px;  font-family:garamond; font-size: 12px;"><i>the present certificate is therefore issued to
        him/her to serve with all the rights and privileges thereonto appartaining.</i></span></td></tr>
        
    </table>';

$html = <<<EOD
       
    <table><tr><td style="width:10%"></td><td style="width:90%">$text</td><td style="width:10%"></td></tr></table>
EOD;

$pdf->writeHTML($html, true, false,true, false, 'c'); 

$pdf->SetFont('garamond', '', 8);

$etud ='<tr><td colspan="3">N° Matricule/<i>Registration Number</i> :</td><td>'.$stud["matricule"].'</td><td colspan="2"></td><td colspan="3" >N°REF :</td></tr>';
$etud.='<tr><td colspan="3">Nom(s) et Prénom(s)/<i>Name and surname</i> :</td><td colspan="4">'.$stud["nom"].' '.$stud["prenom"].'</td></tr>';
$etud .='<tr><td colspan="3">Né(e) le/<i>Born on</i> :</td><td>'.$stud["dateOfBirth"].'</td><td>à/<i>at</i> :</td><td colspan="2">'.$stud["bornAt"].'</td><td></td></tr>';
$etud .='<tr><td >Option/<i>Series</i> :</td><td colspan="3"> '.$this->diplome.' </td><td>Niveau/<i>Level</i> : '.$this->studyLevel.'</td><td></td><td colspan="3">Année Académique/<i>Academic Year</i> : '.$this->acadYrCode.' </td></tr>';
$etud = '<table>'.$etud.'</table>';

$etud = <<<EOD
    $etud
EOD;
//$pdf->writeHTML($etud, true, false,true, false, 'c');


}



ob_end_clean();
//Close and output PDF document

$pdf->Output($_SERVER["DOCUMENT_ROOT"].'impressions/'.preg_replace('/\s+/', '',"CertificatScolarite".$this->classe.$this->semestre).'-'.date("d-m-Y-H-i-S").'.pdf', 'F');
?>

        <style> 
.md-datepicker-calendar-pane{
z-index: 120000}

.md-select-menu-container {z-index: 120000;}
</style>

   <md-dialog style="max-width: 100%;
            max-height: 100%;
    width: 100%;
    height: 100%;
    border-radius: 0;" aria-label="Mango (Fruit)">
  <form ng-cloak>
    <md-toolbar>
      <div class="md-toolbar-tools">
        <h2>Impression certificat de scolarité</h2>
        <span flex></span>
        <md-button class="md-icon-button" ng-click="cancel()">
          <md-icon md-svg-src="img/ic_close_24px.svg" aria-label="Close dialog"></md-icon>
        </md-button>
      </div>
    </md-toolbar>

    <md-dialog-content>
      <div  class="md-dialog-content">

          <embed src=<?=$this->serverUrl().'/impressions/'.preg_replace('/\s+/', '',"CertificatScolarite".$this->classe.$this->semestre.'-').date("d-m-Y-H-i-S").'.pdf';?> type="application/pdf" style="width:100%;height:600px;"  />
                     


      </div>
    </md-dialog-content>

    <md-dialog-actions layout="row">

      <span flex></span>
      <md-button ng-click="cancel()">
       Fermer
      </md-button>

    </md-dialog-actions>
  </form>
</md-dialog>