
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<?php
//============================================================+
// File name   : example_048.php
// Begin       : 2009-03-20
// Last Update : 2013-05-14
//
// Description : Example 048 for TCPDF class
//               HTML tables and table headers
//
// Author: Nicola Asuni
//
// (c) Copyright:
//               Nicola Asuni
//               Tecnick.com LTD
//               www.tecnick.com
//               info@tecnick.com
//============================================================+

/**
 * Creates an example PDF TEST document using TCPDF
 * @package com.tecnick.tcpdf
 * @abstract TCPDF - Example: HTML tables and table headers
 * @author Nicola Asuni
 * @since 2009-03-20
 */



$defaultConfig = (new Mpdf\Config\ConfigVariables())->getDefaults();
$fontDirs = $defaultConfig['fontDir'];

$defaultFontConfig = (new Mpdf\Config\FontVariables())->getDefaults();
$fontData = $defaultFontConfig['fontdata'];

$pdf = new \Mpdf\Mpdf([
    'fontDir' => array_merge($fontDirs, [
        $_SERVER["DOCUMENT_ROOT"]. '/font/Roboto',
    ]),
    'fontdata' => $fontData + [ // lowercase letters only in font key
        'roboto' => [
            'R' => 'Roboto-Regular.ttf',
            'I' => 'Roboto-Italic.ttf',
        ]
    ],
    'default_font' => 'roboto',
    'margin_left' => 18,
    'margin_right' => 18,
    'margin_top' => 45,
    'margin_bottom' => 16,
    'margin_header' => 9,
    'margin_footer' => 9    
]);


$pdf->SetDocTemplate(__DIR__.'/template_header.pdf',1);

// ---------------------------------------------------------
// add a page
foreach($this->students as $student)
{

$pdf->AddPage('P','A4');

$pdf->setFont("roboto",'',16);    
$stud = $student["student"];
$html = '
       
    <div style="width:100%; text-align:center; font-weight: bold;">
        
        <div  style="width: 50%;  float: left; text-align:left; "> ____________/AGENLA/R/VR/CVSIAL/SVS</div>
        <div style="float: right; text-align: right;">Num Ref:'. $student["referenceNumber"].'</div>
    </div>
';

$pdf->writeHTML($html); 


$html = '
       
    <div style="width:100%; text-align:center; font-weight: bold; font-size: 30px; margin-top:50px;">
        
        CERTIFICAT DE SCOLARITE
    </div>
';

$pdf->writeHTML($html);

$html = '
       
    <div style="width:100%;  font-size: 14px;  line-height: normal; text-justify: auto; margin-top: 35px;">
    Je soussigné(e)____________________________,Recteur de l’Institut Universitaire Sous Régional Bilingue,
Agenla Academy, Yaoundé , atteste que:
      
    </div>
';

$pdf->writeHTML($html);

$pdf->SetFont('arialunicodems', '',12);

$html = '    <table style="margin-top: 50px; margin-left:20%" >
        

        
        <tr style=" margin:10px;"><td ><strong>Nom(s) et Prénom(s): </strong></td>
        <td><span > '.$student["nom"].' '.$student["prenom"].'</td></tr>

        <tr style=" margin:10px;"><td ><strong>matricule n° : <strong>/</td>
        <td><span > '.$student["matricule"].'</span></td></tr>
            
        <tr style=" margin:10px;"><td ><strong>né(e) le : </strong></td>
        <td><span > '.$student["dateOfBirth"].'</span></td></tr>
            
        <tr style=" margin:10px;"><td ><strong>à : </strong><br></td>
        <td><span > '.$student["bornAt"].'</span></td></tr>

        
    </table>';



$pdf->writeHTML($html); 

$html = '
       
    <div style="width:100%;  font-size: 14px;  line-height:1.5; text-justify: auto; margin-top: 15px;">
<p>est régulièrement inscrit(e) au niveau <strong>'.$this->niveauEtude.'</strong>   du Cycle de <strong>'.$this->diplome.'</strong>
dans la Filière: <strong>'.$this->filiere.'</strong>, Spécialité: <strong>'.$this->filiere.'</strong>, pour l’année
académique <strong>'.$this->acadYrCode.'</strong> à l\'école <strong>'.$this->faculty.'</strong> au sein de notre institution.</p>
<p>En foi de quoi le présent Certificat de Scolarité lui est établi pour servir et valoir ce que de droit.</p>
      
    </div>
';

$pdf->writeHTML($html);



$html = '
       
    <div style="width:100%; text-align: right;  margin-top: 50px;">
Fait à Yaoundé le _______________________<br /><br />
<strong>Le Recteur &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</strong>
    </div>
    
<div style="width:100%; text-align: center;  margin-top: 200px; font-size: 8px;">
<strong>NB: N\'est délivré qu\'un seul certificat de scolarité par année scolaire. l\'interessé(e) est autorisé(e) à faire autant de copies certifiées conformes auprès de l\'administration
de l\institution en cas de nécessité</strong>
</div>
';

$pdf->writeHTML($html); 



}



ob_end_clean();
//Close and output PDF document

$pdf->Output($_SERVER["DOCUMENT_ROOT"].'/impressions/'.preg_replace('/\s+/', '',"Releves notes".$this->classe.$this->semestre).'-'.date("d-m-Y-H-i-S").'.pdf', 'F');
?>

        <style> 
.md-datepicker-calendar-pane{
z-index: 120000}

.md-select-menu-container {z-index: 120000;}
</style>

   <md-dialog style="max-width: 100%;
            max-height: 100%;
    width: 100%;
    height: 100%;
    border-radius: 0;" aria-label="Mango (Fruit)">
  <form ng-cloak>
    <md-toolbar>
      <div class="md-toolbar-tools">
        <h2>Impression certificat de scolarité</h2>
        <span flex></span>
        <md-button class="md-icon-button" ng-click="cancel()">
          <md-icon md-svg-src="img/ic_close_24px.svg" aria-label="Close dialog"></md-icon>
        </md-button>
      </div>
    </md-toolbar>

    <md-dialog-content>
      <div  class="md-dialog-content">

          <embed src=<?=$this->serverUrl().'/impressions/'.preg_replace('/\s+/', '',"Releves notes".$this->classe.$this->semestre.'-').date("d-m-Y-H-i-S").'.pdf';?> type="application/pdf" style="width:100%;height:600px;"  />
                     


      </div>
    </md-dialog-content>

    <md-dialog-actions layout="row">

      <span flex></span>
      <md-button ng-click="cancel()">
       Fermer
      </md-button>

    </md-dialog-actions>
  </form>
</md-dialog>