

 <p>
 <div  style="margin-top: 55px;">
    
   

        
<div class='row'>
    
    <div class="col-md-4"></div>
    <div class="col-md-4">
    
    <h3>Modifier le mot de passe</h3>
    <p><br></p>
        <?php if ( $error): ?>
            <div class="alert alert-danger" role="alert">
                <?=$msge;?>
                <!--<a href="">Forgot password?</a> -->
            </div>
        <?php endif; ?>
    <form action="" method="POST">
            <div class="form-group">
            <label for="first_name">Mot de passe actuel</label>
            <input type="password" class="form-control" id="first_name" name="current_password">
            </div>    
            <div class="form-group">
            <label for="first_name">Nouveau mot de pase</label>
            <input type="password" class="form-control" id="first_name" name="new_password">
            </div>
            <div class="form-group">
            <label for="last_name">Confirmez le nouveau mot de passe</label>
            <input type="password" class="form-control" id="last_name" name="confirmed_password">
            </div>
            <button type="submit" class="btn btn-default">Submit</button>
        </form>
           
        </div>
    
    <div class="col-md-4"></div>
    </div>
</div>
    </div>
